In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
np.random.seed(42)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv(r"train.csv")
dfTest = pd.read_csv(r"test.csv")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [3]:
dfTest.drop(columns=['PassengerId'], inplace=True)
df.drop(columns=['PassengerId'], inplace=True)

"""dfTest.drop(columns=['SibSp'], inplace=True)
df.drop(columns=['SibSp'], inplace=True)"""

"""dfTest.drop(columns=['Parch'], inplace=True)
df.drop(columns=['Parch'], inplace=True)"""

"""dfTest.drop(columns=['Cabin'], inplace=True)
df.drop(columns=['Cabin'], inplace=True)"""

df['Embarked'].fillna('S', inplace=True)
dfTest['Fare'].fillna(10, inplace=True)

tickets=pd.concat([df['Ticket'],dfTest['Ticket']],ignore_index=True)

dfTest.drop(columns=['Ticket'], inplace=True)
df.drop(columns=['Ticket'], inplace=True)

In [4]:
dfTest.drop(columns=['Sex'], inplace=True)
df.drop(columns=['Sex'], inplace=True)

In [6]:
df['Family']=df['Parch']+df['SibSp']+1
dfTest['Family']=dfTest['Parch']+dfTest['SibSp']+1

In [315]:
"""for index,row in df.iterrows():
    isAlone=tickets.value_counts()[row['Ticket']]
    if(isAlone >1):
        df.loc[df.index[index],'Ticket'] = 1
    else:
        df.loc[df.index[index],'Ticket'] = 0

for index,row in dfTest.iterrows():
    isAlone=tickets.value_counts()[row['Ticket']]
    if(isAlone >1):
        dfTest.loc[dfTest.index[index],'Ticket'] = 1
    else:
        dfTest.loc[dfTest.index[index],'Ticket'] = 0"""

In [5]:
for index,row in df.iterrows():
    fare=row['Fare']
    df.loc[df.index[index],'Fare'] = int(fare)
    """if(fare <30):
        df.loc[df.index[index],'Fare'] = 1
    elif(fare <60):
        df.loc[df.index[index],'Fare'] = 2
    elif(fare <100):
        df.loc[df.index[index],'Fare'] = 3
    else:
        df.loc[df.index[index],'Fare'] = 4"""
        
for index,row in dfTest.iterrows():
    fare=row['Fare']
    dfTest.loc[dfTest.index[index],'Fare'] = int(fare)
    """if(fare <30):
        dfTest.loc[dfTest.index[index],'Fare'] = 1
    elif(fare <60):
        dfTest.loc[dfTest.index[index],'Fare'] = 2
    elif(fare <100):
        dfTest.loc[dfTest.index[index],'Fare'] = 3
    else:
        dfTest.loc[dfTest.index[index],'Fare'] = 4"""

In [9]:
df

,Survived,Pclass,Name,Age,SibSp,Parch,Fare,Cabin,Embarked,Family Size
0,0,3,"Braund, Mr. Owen Harris",22.00,1,0,7.2500,NaN,S,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.00,1,0,71.2833,C85,C,1
2,1,3,"Heikkinen, Miss. Laina",26.00,0,0,7.9250,NaN,S,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.00,1,0,53.1000,C123,S,1
4,0,3,"Allen, Mr. William Henry",35.00,0,0,8.0500,NaN,S,0
5,0,3,"Moran, Mr. James",NaN,0,0,8.4583,NaN,Q,0
6,0,1,"McCarthy, Mr. Timothy J",54.00,0,0,51.8625,E46,S,0
7,0,3,"Palsson, Master. Gosta Leonard",2.00,3,1,21.0750,NaN,S,2
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.00,0,2,11.1333,NaN,S,1
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.00,1,0,30.0708,NaN,C,1
10,1,3,"Sandstrom, Miss. Marguerite Rut",4.00,1,1,16.7000,G6,S,1
11,1,1,"Bonnell, Miss. Elizabeth",58.00,0,0,26.5500,C103,S,0
12,0,3,"Saundercock, Mr. William Henry",20.00,0,0,8.0500,NaN,S,0
13,0,3,"Andersson, Mr. Anders Johan",39.00,1,5,31.2750,NaN,S,2
14,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",14.00,0,0,7.8542,NaN,S,0
15,1,2,"Hewlett, Mrs. (Mary D Kingcome)",55.00,0,0,16.0000,NaN,S,0
16,0,3,"Rice, Master. Eugene",2.00,4,1,29.1250,NaN,Q,2
17,1,2,"Williams, Mr. Charles Eugene",NaN,0,0,13.0000,NaN,S,0
18,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",31.00,1,0,18.0000,NaN,S,1
19,1,3,"Masselmani, Mrs. Fatima",NaN,0,0,7.2250,NaN,C,0
20,0,2,"Fynney, Mr. Joseph J",35.00,0,0,26.0000,NaN,S,0
21,1,2,"Beesley, Mr. Lawrence",34.00,0,0,13.0000,D56,S,0
22,1,3,"McGowan, Miss. Anna ""Annie""",15.00,0,0,8.0292,NaN,Q,0
23,1,1,"Sloper, Mr. William Thompson",28.00,0,0,35.5000,A6,S,0
24,0,3,"Palsson, Miss. Torborg Danira",8.00,3,1,21.0750,NaN,S,2
25,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.00,1,5,31.3875,NaN,S,2
26,0,3,"Emir, Mr. Farred Chehab",NaN,0,0,7.2250,NaN,C,0
27,0,1,"Fortune, Mr. Charles Alexander",19.00,3,2,263.0000,C23 C25 C27,S,2
28,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",NaN,0,0,7.8792,NaN,Q,0
29,0,3,"Todoroff, Mr. Lalio",NaN,0,0,7.8958,NaN,S,0
30,0,1,"Uruchurtu, Don. Manuel E",40.00,0,0,27.7208,NaN,C,0
31,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN,1,0,146.5208,B78,C,1
32,1,3,"Glynn, Miss. Mary Agatha",NaN,0,0,7.7500,NaN,Q,0
33,0,2,"Wheadon, Mr. Edward H",66.00,0,0,10.5000,NaN,S,0
34,0,1,"Meyer, Mr. Edgar Joseph",28.00,1,0,82.1708,NaN,C,1
35,0,1,"Holverson, Mr. Alexander Oskar",42.00,1,0,52.0000,NaN,S,1
36,1,3,"Mamee, Mr. Hanna",NaN,0,0,7.2292,NaN,C,0
37,0,3,"Cann, Mr. Ernest Charles",21.00,0,0,8.0500,NaN,S,0
38,0,3,"Vander Planke, Miss. Augusta Maria",18.00,2,0,18.0000,NaN,S,1
39,1,3,"Nicola-Yarred, Miss. Jamila",14.00,1,0,11.2417,NaN,C,1
40,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",40.00,1,0,9.4750,NaN,S,1
41,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",27.00,1,0,21.0000,NaN,S,1
42,0,3,"Kraeff, Mr. Theodor",NaN,0,0,7.8958,NaN,C,0
43,1,2,"Laroche, Miss. Simonne Marie Anne Andree",3.00,1,2,41.5792,NaN,C,1
44,1,3,"Devaney, Miss. Margaret Delia",19.00,0,0,7.8792,NaN,Q,0
45,0,3,"Rogers, Mr. William John",NaN,0,0,8.0500,NaN,S,0
46,0,3,"Lennon, Mr. Denis",NaN,1,0,15.5000,NaN,Q,1
47,1,3,"O'Driscoll, Miss. Bridget",NaN,0,0,7.7500,NaN,Q,0
48,0,3,"Samaan, Mr. Youssef",NaN,2,0,21.6792,NaN,C,1
49,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",18.00,1,0,17.8000,NaN,S,1
50,0,3,"Panula, Master. Juha Niilo",7.00,4,1,39.6875,NaN,S,2
51,0,3,"Nosworthy, Mr. Richard Cater",21.00,0,0,7.8000,NaN,S,0
52,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",49.00,1,0,76.7292,D33,C,1
53,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",29.00,1,0,26.0000,NaN,S,1
54,0,1,"Ostby, Mr. Engelhart Cornelius",65.00,0,1,61.9792,B30,C,1
55,1,1,"Woolner, Mr. Hugh",NaN,0,0,35.5000,C52,S,0
56,1,2,"Rugg, Miss. Emily",21.00,0,0,10.5000,NaN,S,0
57,0,3,"Novel, Mr. Mansouer",28.50,0,0,7.2292,NaN,C,0
58,1,2,"West, Miss. Constance Mirium",5.00,1,2,27.7500,NaN,S,1
59,0,3,"Goodwin, Master. William Frederick",11.00,5,2,46.9000,NaN,S,3
60,0,3,"Sirayanian, Mr. Orsen",22.00,0,0,7.2292,NaN,C,0
61,1,1,"Icard, Miss. Amelie",38.00,0,0,80.0000,B28,S,0
62,0,1,"Harris, Mr. Henry Birkhardt",45.00,1,0,83.4750,C83,S,1
63,0,3,"Skoog, Master. Harald",4.00,3,2,27.9000,NaN,S,2
64,0,1,"Stewart, Mr. Albert A",NaN,0,0,27.7208,NaN,C,0
65,1,3,"Moubarek, Master. Gerios",NaN,1,1,15.2458,NaN,C,1
66,1,2,"Nye, Mrs. (Elizabeth Ramell)",29.00,0,0,10.5000,F33,S,0
67,0,3,"Crease, Mr. Ernest James",19.00,0,0,8.1583,NaN,S,0
68,1,3,"Andersson, Miss. Erna Alexandra",17.00,4,2,7.9250,NaN,S,2
69,0,3,"Kink, Mr. Vincenz",26.00,2,0,8.6625,NaN,S,1
70,0,2,"Jenkin, Mr. Stephen Curnow",32.00,0,0,10.5000,NaN,S,0
71,0,3,"Goodwin, Miss. Lillian Amy",16.00,5,2,46.9000,NaN,S,3
72,0,2,"Hood, Mr. Ambrose Jr",21.00,0,0,73.5000,NaN,S,0
73,0,3,"Chronopoulos, Mr. Apostolos",26.00,1,0,14.4542,NaN,C,1
74,1,3,"Bing, Mr. Lee",32.00,0,0,56.4958,NaN,S,0
75,0,3,"Moen, Mr. Sigurd Hansen",25.00,0,0,7.6500,F G73,S,0
76,0,3,"Staneff, Mr. Ivan",NaN,0,0,7.8958,NaN,S,0
77,0,3,"Moutal, Mr. Rahamin Haim",NaN,0,0,8.0500,NaN,S,0
78,1,2,"Caldwell, Master. Alden Gates",0.83,0,2,29.0000,NaN,S,1
79,1,3,"Dowdell, Miss. Elizabeth",30.00,0,0,12.4750,NaN,S,0
80,0,3,"Waelens, Mr. Achille",22.00,0,0,9.0000,NaN,S,0
81,1,3,"Sheerlinck, Mr. Jan Baptist",29.00,0,0,9.5000,NaN,S,0
82,1,3,"McDermott, Miss. Brigdet Delia",NaN,0,0,7.7875,NaN,Q,0
83,0,1,"Carrau, Mr. Francisco M",28.00,0,0,47.1000,NaN,S,0
84,1,2,"Ilett, Miss. Bertha",17.00,0,0,10.5000,NaN,S,0
85,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",33.00,3,0,15.8500,NaN,S,1
86,0,3,"Ford, Mr. William Neal",16.00,1,3,34.3750,NaN,S,2
87,0,3,"Slocovski, Mr. Selman Francis",NaN,0,0,8.0500,NaN,S,0
88,1,1,"Fortune, Miss. Mabel Helen",23.00,3,2,263.0000,C23 C25 C27,S,2
89,0,3,"Celotti, Mr. Francesco",24.00,0,0,8.0500,NaN,S,0
90,0,3,"Christmann, Mr. Emil",29.00,0,0,8.0500,NaN,S,0
91,0,3,"Andreasson, Mr. Paul Edvin",20.00,0,0,7.8542,NaN,S,0
92,0,1,"Chaffee, Mr. Herbert Fuller",46.00,1,0,61.1750,E31,S,1
93,0,3,"Dean, Mr. Bertram Frank",26.00,1,2,20.5750,NaN,S,1
94,0,3,"Coxon, Mr. Daniel",59.00,0,0,7.2500,NaN,S,0
95,0,3,"Shorney, Mr. Charles Joseph",NaN,0,0,8.0500,NaN,S,0
96,0,1,"Goldschmidt, Mr. George B",71.00,0,0,34.6542,A5,C,0
97,1,1,"Greenfield, Mr. William Bertram",23.00,0,1,63.3583,D10 D12,C,1
98,1,2,"Doling, Mrs. John T (Ada Julia Bone)",34.00,0,1,23.0000,NaN,S,1
99,0,2,"Kantor, Mr. Sinai",34.00,1,0,26.0000,NaN,S,1
100,0,3,"Petranec, Miss. Matilda",28.00,0,0,7.8958,NaN,S,0
101,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",NaN,0,0,7.8958,NaN,S,0
102,0,1,"White, Mr. Richard Frasar",21.00,0,1,77.2875,D26,S,1
103,0,3,"Johansson, Mr. Gustaf Joel",33.00,0,0,8.6542,NaN,S,0
104,0,3,"Gustafsson, Mr. Anders Vilhelm",37.00,2,0,7.9250,NaN,S,1
105,0,3,"Mionoff, Mr. Stoytcho",28.00,0,0,7.8958,NaN,S,0
106,1,3,"Salkjelsvik, Miss. Anna Kristine",21.00,0,0,7.6500,NaN,S,0
107,1,3,"Moss, Mr. Albert Johan",NaN,0,0,7.7750,NaN,S,0
108,0,3,"Rekic, Mr. Tido",38.00,0,0,7.8958,NaN,S,0
109,1,3,"Moran, Miss. Bertha",NaN,1,0,24.1500,NaN,Q,1
110,0,1,"Porter, Mr. Walter Chamberlain",47.00,0,0,52.0000,C110,S,0
111,0,3,"Zabour, Miss. Hileni",14.50,1,0,14.4542,NaN,C,1
112,0,3,"Barton, Mr. David John",22.00,0,0,8.0500,NaN,S,0
113,0,3,"Jussila, Miss. Katriina",20.00,1,0,9.8250,NaN,S,1
114,0,3,"Attalah, Miss. Malake",17.00,0,0,14.4583,NaN,C,0
115,0,3,"Pekoniemi, Mr. Edvard",21.00,0,0,7.9250,NaN,S,0
116,0,3,"Connors, Mr. Patrick",70.50,0,0,7.7500,NaN,Q,0
117,0,2,"Turpin, Mr. William John Robert",29.00,1,0,21.0000,NaN,S,1
118,0,1,"Baxter, Mr. Quigg Edmond",24.00,0,1,247.5208,B58 B60,C,1
119,0,3,"Andersson, Miss. Ellis Anna Maria",2.00,4,2,31.2750,NaN,S,2
120,0,2,"Hickman, Mr. Stanley George",21.00,2,0,73.5000,NaN,S,1
121,0,3,"Moore, Mr. Leonard Charles",NaN,0,0,8.0500,NaN,S,0
122,0,2,"Nasser, Mr. Nicholas",32.50,1,0,30.0708,NaN,C,1
123,1,2,"Webber, Miss. Susan",32.50,0,0,13.0000,E101,S,0
124,0,1,"White, Mr. Percival Wayland",54.00,0,1,77.2875,D26,S,1
125,1,3,"Nicola-Yarred, Master. Elias",12.00,1,0,11.2417,NaN,C,1
126,0,3,"McMahon, Mr. Martin",NaN,0,0,7.7500,NaN,Q,0
127,1,3,"Madsen, Mr. Fridtjof Arne",24.00,0,0,7.1417,NaN,S,0
128,1,3,"Peter, Miss. Anna",NaN,1,1,22.3583,F E69,C,1
129,0,3,"Ekstrom, Mr. Johan",45.00,0,0,6.9750,NaN,S,0
130,0,3,"Drazenoic, Mr. Jozef",33.00,0,0,7.8958,NaN,C,0
131,0,3,"Coelho, Mr. Domingos Fernandeo",20.00,0,0,7.0500,NaN,S,0
132,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",47.00,1,0,14.5000,NaN,S,1
133,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",29.00,1,0,26.0000,NaN,S,1
134,0,2,"Sobey, Mr. Samuel James Hayden",25.00,0,0,13.0000,NaN,S,0
135,0,2,"Richard, Mr. Emile",23.00,0,0,15.0458,NaN,C,0
136,1,1,"Newsom, Miss. Helen Monypeny",19.00,0,2,26.2833,D47,S,1
137,0,1,"Futrelle, Mr. Jacques Heath",37.00,1,0,53.1000,C123,S,1
138,0,3,"Osen, Mr. Olaf Elon",16.00,0,0,9.2167,NaN,S,0
139,0,1,"Giglio, Mr. Victor",24.00,0,0,79.2000,B86,C,0
140,0,3,"Boulos, Mrs. Joseph (Sultana)",NaN,0,2,15.2458,NaN,C,1
141,1,3,"Nysten, Miss. Anna Sofia",22.00,0,0,7.7500,NaN,S,0
142,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",24.00,1,0,15.8500,NaN,S,1
143,0,3,"Burke, Mr. Jeremiah",19.00,0,0,6.7500,NaN,Q,0
144,0,2,"Andrew, Mr. Edgardo Samuel",18.00,0,0,11.5000,NaN,S,0
145,0,2,"Nicholls, Mr. Joseph Charles",19.00,1,1,36.7500,NaN,S,1
146,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",27.00,0,0,7.7958,NaN,S,0
147,0,3,"Ford, Miss. Robina Maggie ""Ruby""",9.00,2,2,34.3750,NaN,S,2
148,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",36.50,0,2,26.0000,F2,S,1
149,0,2,"Byles, Rev. Thomas Roussel Davids",42.00,0,0,13.0000,NaN,S,0
150,0,2,"Bateman, Rev. Robert James",51.00,0,0,12.5250,NaN,S,0
151,1,1,"Pears, Mrs. Thomas (Edith Wearne)",22.00,1,0,66.6000,C2,S,1
152,0,3,"Meo, Mr. Alfonzo",55.50,0,0,8.0500,NaN,S,0
153,0,3,"van Billiard, Mr. Austin Blyler",40.50,0,2,14.5000,NaN,S,1
154,0,3,"Olsen, Mr. Ole Martin",NaN,0,0,7.3125,NaN,S,0
155,0,1,"Williams, Mr. Charles Duane",51.00,0,1,61.3792,NaN,C,1
156,1,3,"Gilnagh, Miss. Katherine ""Katie""",16.00,0,0,7.7333,NaN,Q,0
157,0,3,"Corn, Mr. Harry",30.00,0,0,8.0500,NaN,S,0
158,0,3,"Smiljanic, Mr. Mile",NaN,0,0,8.6625,NaN,S,0
159,0,3,"Sage, Master. Thomas Henry",NaN,8,2,69.5500,NaN,S,3
160,0,3,"Cribb, Mr. John Hatfield",44.00,0,1,16.1000,NaN,S,1
161,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",40.00,0,0,15.7500,NaN,S,0
162,0,3,"Bengtsson, Mr. John Viktor",26.00,0,0,7.7750,NaN,S,0
163,0,3,"Calic, Mr. Jovo",17.00,0,0,8.6625,NaN,S,0
164,0,3,"Panula, Master. Eino Viljami",1.00,4,1,39.6875,NaN,S,2
165,1,3,"Goldsmith, Master. Frank John William ""Frankie""",9.00,0,2,20.5250,NaN,S,1
166,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",NaN,0,1,55.0000,E33,S,1
167,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",45.00,1,4,27.9000,NaN,S,2
168,0,1,"Baumann, Mr. John D",NaN,0,0,25.9250,NaN,S,0
169,0,3,"Ling, Mr. Lee",28.00,0,0,56.4958,NaN,S,0
170,0,1,"Van der hoef, Mr. Wyckoff",61.00,0,0,33.5000,B19,S,0
171,0,3,"Rice, Master. Arthur",4.00,4,1,29.1250,NaN,Q,2
172,1,3,"Johnson, Miss. Eleanor Ileen",1.00,1,1,11.1333,NaN,S,1
173,0,3,"Sivola, Mr. Antti Wilhelm",21.00,0,0,7.9250,NaN,S,0
174,0,1,"Smith, Mr. James Clinch",56.00,0,0,30.6958,A7,C,0
175,0,3,"Klasen, Mr. Klas Albin",18.00,1,1,7.8542,NaN,S,1
176,0,3,"Lefebre, Master. Henry Forbes",NaN,3,1,25.4667,NaN,S,2
177,0,1,"Isham, Miss. Ann Elizabeth",50.00,0,0,28.7125,C49,C,0
178,0,2,"Hale, Mr. Reginald",30.00,0,0,13.0000,NaN,S,0
179,0,3,"Leonard, Mr. Lionel",36.00,0,0,0.0000,NaN,S,0
180,0,3,"Sage, Miss. Constance Gladys",NaN,8,2,69.5500,NaN,S,3
181,0,2,"Pernot, Mr. Rene",NaN,0,0,15.0500,NaN,C,0
182,0,3,"Asplund, Master. Clarence Gustaf Hugo",9.00,4,2,31.3875,NaN,S,2
183,1,2,"Becker, Master. Richard F",1.00,2,1,39.0000,F4,S,1
184,1,3,"Kink-Heilmann, Miss. Luise Gretchen",4.00,0,2,22.0250,NaN,S,1
185,0,1,"Rood, Mr. Hugh Roscoe",NaN,0,0,50.0000,A32,S,0
186,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",NaN,1,0,15.5000,NaN,Q,1
187,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",45.00,0,0,26.5500,NaN,S,0
188,0,3,"Bourke, Mr. John",40.00,1,1,15.5000,NaN,Q,1
189,0,3,"Turcin, Mr. Stjepan",36.00,0,0,7.8958,NaN,S,0
190,1,2,"Pinsky, Mrs. (Rosa)",32.00,0,0,13.0000,NaN,S,0
191,0,2,"Carbines, Mr. William",19.00,0,0,13.0000,NaN,S,0
192,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",19.00,1,0,7.8542,NaN,S,1
193,1,2,"Navratil, Master. Michel M",3.00,1,1,26.0000,F2,S,1
194,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",44.00,0,0,27.7208,B4,C,0
195,1,1,"Lurette, Miss. Elise",58.00,0,0,146.5208,B80,C,0
196,0,3,"Mernagh, Mr. Robert",NaN,0,0,7.7500,NaN,Q,0
197,0,3,"Olsen, Mr. Karl Siegwart Andreas",42.00,0,1,8.4042,NaN,S,1
198,1,3,"Madigan, Miss. Margaret ""Maggie""",NaN,0,0,7.7500,NaN,Q,0
199,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",24.00,0,0,13.0000,NaN,S,0
200,0,3,"Vande Walle, Mr. Nestor Cyriel",28.00,0,0,9.5000,NaN,S,0
201,0,3,"Sage, Mr. Frederick",NaN,8,2,69.5500,NaN,S,3
202,0,3,"Johanson, Mr. Jakob Alfred",34.00,0,0,6.4958,NaN,S,0
203,0,3,"Youseff, Mr. Gerious",45.50,0,0,7.2250,NaN,C,0
204,1,3,"Cohen, Mr. Gurshon ""Gus""",18.00,0,0,8.0500,NaN,S,0
205,0,3,"Strom, Miss. Telma Matilda",2.00,0,1,10.4625,G6,S,1
206,0,3,"Backstrom, Mr. Karl Alfred",32.00,1,0,15.8500,NaN,S,1
207,1,3,"Albimona, Mr. Nassef Cassem",26.00,0,0,18.7875,NaN,C,0
208,1,3,"Carr, Miss. Helen ""Ellen""",16.00,0,0,7.7500,NaN,Q,0
209,1,1,"Blank, Mr. Henry",40.00,0,0,31.0000,A31,C,0
210,0,3,"Ali, Mr. Ahmed",24.00,0,0,7.0500,NaN,S,0
211,1,2,"Cameron, Miss. Clear Annie",35.00,0,0,21.0000,NaN,S,0
212,0,3,"Perkin, Mr. John Henry",22.00,0,0,7.2500,NaN,S,0
213,0,2,"Givard, Mr. Hans Kristensen",30.00,0,0,13.0000,NaN,S,0
214,0,3,"Kiernan, Mr. Philip",NaN,1,0,7.7500,NaN,Q,1
215,1,1,"Newell, Miss. Madeleine",31.00,1,0,113.2750,D36,C,1
216,1,3,"Honkanen, Miss. Eliina",27.00,0,0,7.9250,NaN,S,0
217,0,2,"Jacobsohn, Mr. Sidney Samuel",42.00,1,0,27.0000,NaN,S,1
218,1,1,"Bazzani, Miss. Albina",32.00,0,0,76.2917,D15,C,0
219,0,2,"Harris, Mr. Walter",30.00,0,0,10.5000,NaN,S,0
220,1,3,"Sunderland, Mr. Victor Francis",16.00,0,0,8.0500,NaN,S,0
221,0,2,"Bracken, Mr. James H",27.00,0,0,13.0000,NaN,S,0
222,0,3,"Green, Mr. George Henry",51.00,0,0,8.0500,NaN,S,0
223,0,3,"Nenkoff, Mr. Christo",NaN,0,0,7.8958,NaN,S,0
224,1,1,"Hoyt, Mr. Frederick Maxfield",38.00,1,0,90.0000,C93,S,1
225,0,3,"Berglund, Mr. Karl Ivar Sven",22.00,0,0,9.3500,NaN,S,0
226,1,2,"Mellors, Mr. William John",19.00,0,0,10.5000,NaN,S,0
227,0,3,"Lovell, Mr. John Hall (""Henry"")",20.50,0,0,7.2500,NaN,S,0
228,0,2,"Fahlstrom, Mr. Arne Jonas",18.00,0,0,13.0000,NaN,S,0
229,0,3,"Lefebre, Miss. Mathilde",NaN,3,1,25.4667,NaN,S,2
230,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",35.00,1,0,83.4750,C83,S,1
231,0,3,"Larsson, Mr. Bengt Edvin",29.00,0,0,7.7750,NaN,S,0
232,0,2,"Sjostedt, Mr. Ernst Adolf",59.00,0,0,13.5000,NaN,S,0
233,1,3,"Asplund, Miss. Lillian Gertrud",5.00,4,2,31.3875,NaN,S,2
234,0,2,"Leyson, Mr. Robert William Norman",24.00,0,0,10.5000,NaN,S,0
235,0,3,"Harknett, Miss. Alice Phoebe",NaN,0,0,7.5500,NaN,S,0
236,0,2,"Hold, Mr. Stephen",44.00,1,0,26.0000,NaN,S,1
237,1,2,"Collyer, Miss. Marjorie ""Lottie""",8.00,0,2,26.2500,NaN,S,1
238,0,2,"Pengelly, Mr. Frederick William",19.00,0,0,10.5000,NaN,S,0
239,0,2,"Hunt, Mr. George Henry",33.00,0,0,12.2750,NaN,S,0
240,0,3,"Zabour, Miss. Thamine",NaN,1,0,14.4542,NaN,C,1
241,1,3,"Murphy, Miss. Katherine ""Kate""",NaN,1,0,15.5000,NaN,Q,1
242,0,2,"Coleridge, Mr. Reginald Charles",29.00,0,0,10.5000,NaN,S,0
243,0,3,"Maenpaa, Mr. Matti Alexanteri",22.00,0,0,7.1250,NaN,S,0
244,0,3,"Attalah, Mr. Sleiman",30.00,0,0,7.2250,NaN,C,0
245,0,1,"Minahan, Dr. William Edward",44.00,2,0,90.0000,C78,Q,1
246,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",25.00,0,0,7.7750,NaN,S,0
247,1,2,"Hamalainen, Mrs. William (Anna)",24.00,0,2,14.5000,NaN,S,1
248,1,1,"Beckwith, Mr. Richard Leonard",37.00,1,1,52.5542,D35,S,1
249,0,2,"Carter, Rev. Ernest Courtenay",54.00,1,0,26.0000,NaN,S,1
250,0,3,"Reed, Mr. James George",NaN,0,0,7.2500,NaN,S,0
251,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",29.00,1,1,10.4625,G6,S,1
252,0,1,"Stead, Mr. William Thomas",62.00,0,0,26.5500,C87,S,0
253,0,3,"Lobb, Mr. William Arthur",30.00,1,0,16.1000,NaN,S,1
254,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",41.00,0,2,20.2125,NaN,S,1
255,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",29.00,0,2,15.2458,NaN,C,1
256,1,1,"Thorne, Mrs. Gertrude Maybelle",NaN,0,0,79.2000,NaN,C,0
257,1,1,"Cherry, Miss. Gladys",30.00,0,0,86.5000,B77,S,0
258,1,1,"Ward, Miss. Anna",35.00,0,0,512.3292,NaN,C,0
259,1,2,"Parrish, Mrs. (Lutie Davis)",50.00,0,1,26.0000,NaN,S,1
260,0,3,"Smith, Mr. Thomas",NaN,0,0,7.7500,NaN,Q,0
261,1,3,"Asplund, Master. Edvin Rojj Felix",3.00,4,2,31.3875,NaN,S,2
262,0,1,"Taussig, Mr. Emil",52.00,1,1,79.6500,E67,S,1
263,0,1,"Harrison, Mr. William",40.00,0,0,0.0000,B94,S,0
264,0,3,"Henry, Miss. Delia",NaN,0,0,7.7500,NaN,Q,0
265,0,2,"Reeves, Mr. David",36.00,0,0,10.5000,NaN,S,0
266,0,3,"Panula, Mr. Ernesti Arvid",16.00,4,1,39.6875,NaN,S,2
267,1,3,"Persson, Mr. Ernst Ulrik",25.00,1,0,7.7750,NaN,S,1
268,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",58.00,0,1,153.4625,C125,S,1
269,1,1,"Bissette, Miss. Amelia",35.00,0,0,135.6333,C99,S,0
270,0,1,"Cairns, Mr. Alexander",NaN,0,0,31.0000,NaN,S,0
271,1,3,"Tornquist, Mr. William Henry",25.00,0,0,0.0000,NaN,S,0
272,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",41.00,0,1,19.5000,NaN,S,1
273,0,1,"Natsch, Mr. Charles H",37.00,0,1,29.7000,C118,C,1
274,1,3,"Healy, Miss. Hanora ""Nora""",NaN,0,0,7.7500,NaN,Q,0
275,1,1,"Andrews, Miss. Kornelia Theodosia",63.00,1,0,77.9583,D7,S,1
276,0,3,"Lindblom, Miss. Augusta Charlotta",45.00,0,0,7.7500,NaN,S,0
277,0,2,"Parkes, Mr. Francis ""Frank""",NaN,0,0,0.0000,NaN,S,0
278,0,3,"Rice, Master. Eric",7.00,4,1,29.1250,NaN,Q,2
279,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",35.00,1,1,20.2500,NaN,S,1
280,0,3,"Duane, Mr. Frank",65.00,0,0,7.7500,NaN,Q,0
281,0,3,"Olsson, Mr. Nils Johan Goransson",28.00,0,0,7.8542,NaN,S,0
282,0,3,"de Pelsmaeker, Mr. Alfons",16.00,0,0,9.5000,NaN,S,0
283,1,3,"Dorking, Mr. Edward Arthur",19.00,0,0,8.0500,NaN,S,0
284,0,1,"Smith, Mr. Richard William",NaN,0,0,26.0000,A19,S,0
285,0,3,"Stankovic, Mr. Ivan",33.00,0,0,8.6625,NaN,C,0
286,1,3,"de Mulder, Mr. Theodore",30.00,0,0,9.5000,NaN,S,0
287,0,3,"Naidenoff, Mr. Penko",22.00,0,0,7.8958,NaN,S,0
288,1,2,"Hosono, Mr. Masabumi",42.00,0,0,13.0000,NaN,S,0
289,1,3,"Connolly, Miss. Kate",22.00,0,0,7.7500,NaN,Q,0
290,1,1,"Barber, Miss. Ellen ""Nellie""",26.00,0,0,78.8500,NaN,S,0
291,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",19.00,1,0,91.0792,B49,C,1
292,0,2,"Levy, Mr. Rene Jacques",36.00,0,0,12.8750,D,C,0
293,0,3,"Haas, Miss. Aloisia",24.00,0,0,8.8500,NaN,S,0
294,0,3,"Mineff, Mr. Ivan",24.00,0,0,7.8958,NaN,S,0
295,0,1,"Lewy, Mr. Ervin G",NaN,0,0,27.7208,NaN,C,0
296,0,3,"Hanna, Mr. Mansour",23.50,0,0,7.2292,NaN,C,0
297,0,1,"Allison, Miss. Helen Loraine",2.00,1,2,151.5500,C22 C26,S,1
298,1,1,"Saalfeld, Mr. Adolphe",NaN,0,0,30.5000,C106,S,0
299,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",50.00,0,1,247.5208,B58 B60,C,1
300,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",NaN,0,0,7.7500,NaN,Q,0
301,1,3,"McCoy, Mr. Bernard",NaN,2,0,23.2500,NaN,Q,1
302,0,3,"Johnson, Mr. William Cahoone Jr",19.00,0,0,0.0000,NaN,S,0
303,1,2,"Keane, Miss. Nora A",NaN,0,0,12.3500,E101,Q,0
304,0,3,"Williams, Mr. Howard Hugh ""Harry""",NaN,0,0,8.0500,NaN,S,0
305,1,1,"Allison, Master. Hudson Trevor",0.92,1,2,151.5500,C22 C26,S,1
306,1,1,"Fleming, Miss. Margaret",NaN,0,0,110.8833,NaN,C,0
307,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",17.00,1,0,108.9000,C65,C,1
308,0,2,"Abelson, Mr. Samuel",30.00,1,0,24.0000,NaN,C,1
309,1,1,"Francatelli, Miss. Laura Mabel",30.00,0,0,56.9292,E36,C,0
310,1,1,"Hays, Miss. Margaret Bechstein",24.00,0,0,83.1583,C54,C,0
311,1,1,"Ryerson, Miss. Emily Borie",18.00,2,2,262.3750,B57 B59 B63 B66,C,2
312,0,2,"Lahtinen, Mrs. William (Anna Sylfven)",26.00,1,1,26.0000,NaN,S,1
313,0,3,"Hendekovic, Mr. Ignjac",28.00,0,0,7.8958,NaN,S,0
314,0,2,"Hart, Mr. Benjamin",43.00,1,1,26.2500,NaN,S,1
315,1,3,"Nilsson, Miss. Helmina Josefina",26.00,0,0,7.8542,NaN,S,0

In [7]:
df['Family Size']=pd.cut(df.Family, [0,1,4,7,11], labels=[0,1,2,3])
dfTest['Family Size']=pd.cut(dfTest.Family, [0,1,4,7,11], labels=[0,1,2,3])

In [8]:
dfTest.drop(columns=['Family'], inplace=True)
df.drop(columns=['Family'], inplace=True)

In [141]:
emptySer=pd.Series([])
for i,r in df.iterrows():
    tmp=r['Cabin']
    if(type(tmp)==str):
        tmpSer=pd.Series([tmp[0]])
        emptySer=pd.concat([emptySer,tmpSer],ignore_index=True)
    else:
        tmpSer=pd.Series(['M'])
        emptySer=pd.concat([emptySer,tmpSer],ignore_index=True)

emptySerT=pd.Series([])
for i,r in dfTest.iterrows():
    tmp=r['Cabin']
    if(type(tmp)==str):
        tmpSer=pd.Series([tmp[0]])
        emptySerT=pd.concat([emptySerT,tmpSer],ignore_index=True)
    else:
        tmpSer=pd.Series(['M'])
        emptySerT=pd.concat([emptySerT,tmpSer],ignore_index=True)
emptySerT

0      M
1      M
2      M
3      M
4      M
5      M
6      M
7      M
8      M
9      M
10     M
11     M
12     B
13     M
14     E
15     M
16     M
17     M
18     M
19     M
20     M
21     M
22     M
23     M
24     B
25     M
26     B
27     M
28     A
29     M
30     M
31     M
32     M
33     M
34     C
35     M
36     M
37     M
38     M
39     M
40     M
41     D
42     M
43     M
44     D
45     M
46     A
47     M
48     D
49     M
50     C
51     M
52     M
53     C
54     M
55     M
56     M
57     F
58     M
59     B
60     M
61     M
62     M
63     M
64     B
65     M
66     M
67     M
68     C
69     C
70     M
71     M
72     M
73     D
74     C
75     C
76     M
77     C
78     M
79     M
80     M
81     C
82     M
83     M
84     M
85     M
86     M
87     M
88     M
89     M
90     M
91     M
92     B
93     M
94     M
95     M
96     C
97     M
98     M
99     M
100    C
101    M
102    M
103    M
104    M
105    M
106    M
107    M
108    M
109    F
110    M
111    M
112    A
113    M
114    C
115    M
116    M
117    G
118    C
119    M
120    M
121    M
122    C
123    M
124    M
125    M
126    M
127    M
128    M
129    M
130    M
131    C
132    M
133    M
134    M
135    M
136    M
137    M
138    M
139    M
140    M
141    M
142    B
143    M
144    M
145    M
146    E
147    M
148    M
149    M
150    C
151    M
152    M
153    M
154    M
155    M
156    C
157    M
158    D
159    M
160    M
161    M
162    M
163    M
164    M
165    M
166    B
167    M
168    M
169    M
170    M
171    M
172    M
173    M
174    M
175    M
176    M
177    C
178    F
179    E
180    M
181    E
182    D
183    M
184    B
185    M
186    M
187    M
188    M
189    M
190    M
191    M
192    M
193    M
194    M
195    M
196    E
197    M
198    M
199    M
200    M
201    M
202    C
203    M
204    M
205    M
206    M
207    M
208    A
209    M
210    M
211    M
212    M
213    M
214    M
215    B
216    M
217    M
218    C
219    M
220    M
221    M
222    F
223    M
224    M
225    M
226    M
227    M
228    M
229    M
230    M
231    M
232    M
233    M
234    C
235    M
236    D
237    M
238    M
239    C
240    M
241    M
242    E
243    M
244    M
245    D
246    M
247    M
248    M
249    M
250    M
251    M
252    C
253    M
254    M
255    M
256    M
257    M
258    M
259    M
260    M
261    M
262    M
263    M
264    M
265    M
266    M
267    M
268    M
269    M
270    C
271    M
272    C
273    M
274    M
275    M
276    M
277    M
278    M
279    M
280    M
281    M
282    M
283    M
284    M
285    M
286    M
287    B
288    F
289    M
290    M
291    M
292    M
293    A
294    M
295    M
296    M
297    M
298    M
299    M
300    M
301    D
302    M
303    M
304    M
305    B
306    C
307    M
308    B
309    M
310    M
311    M
312    M
313    M
314    C
315    M
316    B
317    M
318    M
319    M
320    M
321    F
322    F
323    M
324    M
325    M
326    F
327    M
328    M
329    M
330    M
331    A
332    M
333    M
334    M
335    C
336    M
337    M
338    M
339    M
340    M
341    M
342    M
343    B
344    M
345    M
346    M
347    M
348    M
349    M
350    D
351    M
352    M
353    M
354    M
355    E
356    C
357    M
358    M
359    M
360    M
361    M
362    M
363    M
364    E
365    M
366    M
367    M
368    M
369    M
370    M
371    E
372    B
373    M
374    A
375    M
376    M
377    M
378    C
379    M
380    M
381    M
382    M
383    M
384    M
385    M
386    M
387    M
388    M
389    M
390    B
391    D
392    M
393    M
394    M
395    C
396    M
397    B
398    M
399    M
400    C
401    M
402    M
403    M
404    D
405    D
406    M
407    C
408    M
409    M
410    M
411    C
412    M
413    M
414    C
415    M
416    M
417    M
dtype: object

In [9]:
emptySer=pd.Series([])
df['Cabin Letter']=emptySer

In [10]:
dfTest.drop(columns=['Cabin'], inplace=True)
df.drop(columns=['Cabin'], inplace=True)

In [ ]:
"""df['Ticket'] = df['Ticket'].astype("category").cat.as_ordered()
dfTest['Ticket'] = dfTest['Ticket'].astype("category").cat.as_ordered()

df['Ticket'] = pd.Categorical(df['Ticket']).codes
dfTest['Ticket'] = pd.Categorical(dfTest['Ticket']).codes"""

In [107]:
df["cabin_is_missing"] = pd.isnull(df['Cabin'])
dfTest["cabin_is_missing"] = pd.isnull(dfTest['Cabin'])

In [10]:

for index, row in df.iterrows():
    cabin=row['Cabin']
    if (type(cabin)==str):
        #print(cabin)
        spl=cabin.split( )
        #print(x[0],len(x[0]))
        #print(x[0][1])
        if(len(spl[0]) ==2):
            #cb1.append([ord(x[0][0])-ord('A'),0])
            x=(ord(spl[0][0])-ord('A'))+1
            df.loc[df.index[index],['Cabin Letter']]=x
            x=0
            y=0
            k=x*10+y
            #print(x,y,k)
            df.loc[df.index[index],['Cabin']]=k
        elif(len(spl[0]) == 3):
            #cb1.append([ord(x[0][0])-ord('A'),int(x[0][1])])
            x=(ord(spl[0][0])-ord('A'))+1
            df.loc[df.index[index],['Cabin Letter']]=x
            x=0
            y=int(spl[0][1])
            k=x*10+y
            #print(x,y,k)
            df.loc[df.index[index],['Cabin']]=k
        elif(len(spl[0]) == 4):
            #cb1.append([ord(x[0][0])-ord('A'),int(x[0][1]),int(x[0][2])])
            x=(ord(spl[0][0])-ord('A'))+1
            df.loc[df.index[index],['Cabin Letter']]=x
            x=0
            y=int(spl[0][1])
            z=int(spl[0][2])
            k=x*100+y*10+z
            #print(x,y,z,k)
            df.loc[df.index[index],['Cabin']]=k
        else:
            df.loc[df.index[index],['Cabin']]=9
            df.loc[df.index[index],['Cabin Letter']]=9
    else:
        df.loc[df.index[index],['Cabin']]=0
        df.loc[df.index[index],['Cabin Letter']]=0



for index, row in dfTest.iterrows():
    cabin=row['Cabin']
    if (type(cabin)==str):
        #print(cabin)
        spl=cabin.split( )
        #print(x[0],len(x[0]))
        #print(x[0][1])
        if(len(spl[0]) ==2):
            #cb1.append([ord(x[0][0])-ord('A'),0])
            x=(ord(spl[0][0])-ord('A'))+1
            dfTest.loc[df.index[index],['Cabin Letter']]=x
            x=0
            y=0
            k=x*10+y
            #print(x,y,k)
            dfTest.loc[df.index[index],['Cabin']]=k
        elif(len(spl[0]) == 3):
            #cb1.append([ord(x[0][0])-ord('A'),int(x[0][1])])
            x=(ord(spl[0][0])-ord('A'))+1
            dfTest.loc[df.index[index],['Cabin Letter']]=x
            x=0
            y=int(spl[0][1])
            k=x*10+y
            #print(x,y,k)
            dfTest.loc[df.index[index],['Cabin']]=k
        elif(len(spl[0]) == 4):
            #cb1.append([ord(x[0][0])-ord('A'),int(x[0][1]),int(x[0][2])])
            x=(ord(spl[0][0])-ord('A'))+1
            dfTest.loc[df.index[index],['Cabin Letter']]=x
            x=0
            y=int(spl[0][1])
            z=int(spl[0][2])
            k=x*100+y*10+z
            #print(x,y,z,k)
            dfTest.loc[df.index[index],['Cabin']]=k
        else:
            dfTest.loc[df.index[index],['Cabin']]=9
            dfTest.loc[df.index[index],['Cabin Letter']]=9
    else:
        dfTest.loc[df.index[index],['Cabin']]=0
        dfTest.loc[df.index[index],['Cabin Letter']]=0

In [11]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Family Size,Cabin Letter
0,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,7.0,0,S,1,0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,71.0,8,C,1,3
2,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,7.0,0,S,0,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,53.0,12,S,1,3
4,0,3,"Allen, Mr. William Henry",male,35.00,0,0,8.0,0,S,0,0
5,0,3,"Moran, Mr. James",male,NaN,0,0,8.0,0,Q,0,0
6,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,51.0,4,S,0,5
7,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,21.0,0,S,2,0
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,11.0,0,S,1,0
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,30.0,0,C,1,0
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,16.0,0,S,1,7
11,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,26.0,10,S,0,3
12,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,8.0,0,S,0,0
13,0,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,31.0,0,S,2,0
14,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,7.0,0,S,0,0
15,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,16.0,0,S,0,0
16,0,3,"Rice, Master. Eugene",male,2.00,4,1,29.0,0,Q,2,0
17,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,13.0,0,S,0,0
18,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,18.0,0,S,1,0
19,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,7.0,0,C,0,0
20,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,26.0,0,S,0,0
21,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,13.0,5,S,0,4
22,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,8.0,0,Q,0,0
23,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,35.0,0,S,0,1
24,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,21.0,0,S,2,0
25,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.00,1,5,31.0,0,S,2,0
26,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,7.0,0,C,0,0
27,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,263.0,2,S,2,3
28,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,7.0,0,Q,0,0
29,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,7.0,0,S,0,0
30,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,27.0,0,C,0,0
31,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,146.0,7,C,1,2
32,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,7.0,0,Q,0,0
33,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,10.0,0,S,0,0
34,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,82.0,0,C,1,0
35,0,1,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,52.0,0,S,1,0
36,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,7.0,0,C,0,0
37,0,3,"Cann, Mr. Ernest Charles",male,21.00,0,0,8.0,0,S,0,0
38,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,18.0,0,S,1,0
39,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,11.0,0,C,1,0
40,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,9.0,0,S,1,0
41,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.00,1,0,21.0,0,S,1,0
42,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,7.0,0,C,0,0
43,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,41.0,0,C,1,0
44,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,7.0,0,Q,0,0
45,0,3,"Rogers, Mr. William John",male,NaN,0,0,8.0,0,S,0,0
46,0,3,"Lennon, Mr. Denis",male,NaN,1,0,15.0,0,Q,1,0
47,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,7.0,0,Q,0,0
48,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,21.0,0,C,1,0
49,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,17.0,0,S,1,0
50,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,39.0,0,S,2,0
51,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,7.0,0,S,0,0
52,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,76.0,3,C,1,4
53,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.00,1,0,26.0,0,S,1,0
54,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,61.0,3,C,1,2
55,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,35.0,5,S,0,3
56,1,2,"Rugg, Miss. Emily",female,21.00,0,0,10.0,0,S,0,0
57,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,7.0,0,C,0,0
58,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,27.0,0,S,1,0
59,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,46.0,0,S,3,0
60,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,7.0,0,C,0,0
61,1,1,"Icard, Miss. Amelie",female,38.00,0,0,80.0,2,S,0,2
62,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,83.0,8,S,1,3
63,0,3,"Skoog, Master. Harald",male,4.00,3,2,27.0,0,S,2,0
64,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,27.0,0,C,0,0
65,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,15.0,0,C,1,0
66,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,10.0,3,S,0,6
67,0,3,"Crease, Mr. Ernest James",male,19.00,0,0,8.0,0,S,0,0
68,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,7.0,0,S,2,0
69,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,8.0,0,S,1,0
70,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,10.0,0,S,0,0
71,0,3,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,46.0,0,S,3,0
72,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,73.0,0,S,0,0
73,0,3,"Chronopoulos, Mr. Apostolos",male,26.00,1,0,14.0,0,C,1,0
74,1,3,"Bing, Mr. Lee",male,32.00,0,0,56.0,0,S,0,0
75,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,7.0,9,S,0,9
76,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,7.0,0,S,0,0
77,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,8.0,0,S,0,0
78,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,29.0,0,S,1,0
79,1,3,"Dowdell, Miss. Elizabeth",female,30.00,0,0,12.0,0,S,0,0
80,0,3,"Waelens, Mr. Achille",male,22.00,0,0,9.0,0,S,0,0
81,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,9.0,0,S,0,0
82,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,7.0,0,Q,0,0
83,0,1,"Carrau, Mr. Francisco M",male,28.00,0,0,47.0,0,S,0,0
84,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,10.0,0,S,0,0
85,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.00,3,0,15.0,0,S,1,0
86,0,3,"Ford, Mr. William Neal",male,16.00,1,3,34.0,0,S,2,0
87,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,8.0,0,S,0,0
88,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,263.0,2,S,2,3
89,0,3,"Celotti, Mr. Francesco",male,24.00,0,0,8.0,0,S,0,0
90,0,3,"Christmann, Mr. Emil",male,29.00,0,0,8.0,0,S,0,0
91,0,3,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,7.0,0,S,0,0
92,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,61.0,3,S,1,5
93,0,3,"Dean, Mr. Bertram Frank",male,26.00,1,2,20.0,0,S,1,0
94,0,3,"Coxon, Mr. Daniel",male,59.00,0,0,7.0,0,S,0,0
95,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,8.0,0,S,0,0
96,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,34.0,0,C,0,1
97,1,1,"Greenfield, Mr. William Bertram",male,23.00,0,1,63.0,1,C,1,4
98,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,23.0,0,S,1,0
99,0,2,"Kantor, Mr. Sinai",male,34.00,1,0,26.0,0,S,1,0
100,0,3,"Petranec, Miss. Matilda",female,28.00,0,0,7.0,0,S,0,0
101,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,7.0,0,S,0,0
102,0,1,"White, Mr. Richard Frasar",male,21.00,0,1,77.0,2,S,1,4
103,0,3,"Johansson, Mr. Gustaf Joel",male,33.00,0,0,8.0,0,S,0,0
104,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.00,2,0,7.0,0,S,1,0
105,0,3,"Mionoff, Mr. Stoytcho",male,28.00,0,0,7.0,0,S,0,0
106,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.00,0,0,7.0,0,S,0,0
107,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,7.0,0,S,0,0
108,0,3,"Rekic, Mr. Tido",male,38.00,0,0,7.0,0,S,0,0
109,1,3,"Moran, Miss. Bertha",female,NaN,1,0,24.0,0,Q,1,0
110,0,1,"Porter, Mr. Walter Chamberlain",male,47.00,0,0,52.0,11,S,0,3
111,0,3,"Zabour, Miss. Hileni",female,14.50,1,0,14.0,0,C,1,0
112,0,3,"Barton, Mr. David John",male,22.00,0,0,8.0,0,S,0,0
113,0,3,"Jussila, Miss. Katriina",female,20.00,1,0,9.0,0,S,1,0
114,0,3,"Attalah, Miss. Malake",female,17.00,0,0,14.0,0,C,0,0
115,0,3,"Pekoniemi, Mr. Edvard",male,21.00,0,0,7.0,0,S,0,0
116,0,3,"Connors, Mr. Patrick",male,70.50,0,0,7.0,0,Q,0,0
117,0,2,"Turpin, Mr. William John Robert",male,29.00,1,0,21.0,0,S,1,0
118,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,247.0,5,C,1,2
119,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,31.0,0,S,2,0
120,0,2,"Hickman, Mr. Stanley George",male,21.00,2,0,73.0,0,S,1,0
121,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,8.0,0,S,0,0
122,0,2,"Nasser, Mr. Nicholas",male,32.50,1,0,30.0,0,C,1,0
123,1,2,"Webber, Miss. Susan",female,32.50,0,0,13.0,10,S,0,5
124,0,1,"White, Mr. Percival Wayland",male,54.00,0,1,77.0,2,S,1,4
125,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,11.0,0,C,1,0
126,0,3,"McMahon, Mr. Martin",male,NaN,0,0,7.0,0,Q,0,0
127,1,3,"Madsen, Mr. Fridtjof Arne",male,24.00,0,0,7.0,0,S,0,0
128,1,3,"Peter, Miss. Anna",female,NaN,1,1,22.0,9,C,1,9
129,0,3,"Ekstrom, Mr. Johan",male,45.00,0,0,6.0,0,S,0,0
130,0,3,"Drazenoic, Mr. Jozef",male,33.00,0,0,7.0,0,C,0,0
131,0,3,"Coelho, Mr. Domingos Fernandeo",male,20.00,0,0,7.0,0,S,0,0
132,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.00,1,0,14.0,0,S,1,0
133,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.00,1,0,26.0,0,S,1,0
134,0,2,"Sobey, Mr. Samuel James Hayden",male,25.00,0,0,13.0,0,S,0,0
135,0,2,"Richard, Mr. Emile",male,23.00,0,0,15.0,0,C,0,0
136,1,1,"Newsom, Miss. Helen Monypeny",female,19.00,0,2,26.0,4,S,1,4
137,0,1,"Futrelle, Mr. Jacques Heath",male,37.00,1,0,53.0,12,S,1,3
138,0,3,"Osen, Mr. Olaf Elon",male,16.00,0,0,9.0,0,S,0,0
139,0,1,"Giglio, Mr. Victor",male,24.00,0,0,79.0,8,C,0,2
140,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,15.0,0,C,1,0
141,1,3,"Nysten, Miss. Anna Sofia",female,22.00,0,0,7.0,0,S,0,0
142,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.00,1,0,15.0,0,S,1,0
143,0,3,"Burke, Mr. Jeremiah",male,19.00,0,0,6.0,0,Q,0,0
144,0,2,"Andrew, Mr. Edgardo Samuel",male,18.00,0,0,11.0,0,S,0,0
145,0,2,"Nicholls, Mr. Joseph Charles",male,19.00,1,1,36.0,0,S,1,0
146,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.00,0,0,7.0,0,S,0,0
147,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,34.0,0,S,2,0
148,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.50,0,2,26.0,0,S,1,6
149,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.00,0,0,13.0,0,S,0,0
150,0,2,"Bateman, Rev. Robert James",male,51.00,0,0,12.0,0,S,0,0
151,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.00,1,0,66.0,0,S,1,3
152,0,3,"Meo, Mr. Alfonzo",male,55.50,0,0,8.0,0,S,0,0
153,0,3,"van Billiard, Mr. Austin Blyler",male,40.50,0,2,14.0,0,S,1,0
154,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,7.0,0,S,0,0
155,0,1,"Williams, Mr. Charles Duane",male,51.00,0,1,61.0,0,C,1,0
156,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,7.0,0,Q,0,0
157,0,3,"Corn, Mr. Harry",male,30.00,0,0,8.0,0,S,0,0
158,0,3,"Smiljanic, Mr. Mile",male,NaN,0,0,8.0,0,S,0,0
159,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,69.0,0,S,3,0
160,0,3,"Cribb, Mr. John Hatfield",male,44.00,0,1,16.0,0,S,1,0
161,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",female,40.00,0,0,15.0,0,S,0,0
162,0,3,"Bengtsson, Mr. John Viktor",male,26.00,0,0,7.0,0,S,0,0
163,0,3,"Calic, Mr. Jovo",male,17.00,0,0,8.0,0,S,0,0
164,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,39.0,0,S,2,0
165,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,20.0,0,S,1,0
166,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,55.0,3,S,1,5
167,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.00,1,4,27.0,0,S,2,0
168,0,1,"Baumann, Mr. John D",male,NaN,0,0,25.0,0,S,0,0
169,0,3,"Ling, Mr. Lee",male,28.00,0,0,56.0,0,S,0,0
170,0,1,"Van der hoef, Mr. Wyckoff",male,61.00,0,0,33.0,1,S,0,2
171,0,3,"Rice, Master. Arthur",male,4.00,4,1,29.0,0,Q,2,0
172,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,11.0,0,S,1,0
173,0,3,"Sivola, Mr. Antti Wilhelm",male,21.00,0,0,7.0,0,S,0,0
174,0,1,"Smith, Mr. James Clinch",male,56.00,0,0,30.0,0,C,0,1
175,0,3,"Klasen, Mr. Klas Albin",male,18.00,1,1,7.0,0,S,1,0
176,0,3,"Lefebre, Master. Henry Forbes",male,NaN,3,1,25.0,0,S,2,0
177,0,1,"Isham, Miss. Ann Elizabeth",female,50.00,0,0,28.0,4,C,0,3
178,0,2,"Hale, Mr. Reginald",male,30.00,0,0,13.0,0,S,0,0
179,0,3,"Leonard, Mr. Lionel",male,36.00,0,0,0.0,0,S,0,0
180,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,69.0,0,S,3,0
181,0,2,"Pernot, Mr. Rene",male,NaN,0,0,15.0,0,C,0,0
182,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,31.0,0,S,2,0
183,1,2,"Becker, Master. Richard F",male,1.00,2,1,39.0,0,S,1,6
184,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,22.0,0,S,1,0
185,0,1,"Rood, Mr. Hugh Roscoe",male,NaN,0,0,50.0,3,S,0,1
186,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,NaN,1,0,15.0,0,Q,1,0
187,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.00,0,0,26.0,0,S,0,0
188,0,3,"Bourke, Mr. John",male,40.00,1,1,15.0,0,Q,1,0
189,0,3,"Turcin, Mr. Stjepan",male,36.00,0,0,7.0,0,S,0,0
190,1,2,"Pinsky, Mrs. (Rosa)",female,32.00,0,0,13.0,0,S,0,0
191,0,2,"Carbines, Mr. William",male,19.00,0,0,13.0,0,S,0,0
192,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.00,1,0,7.0,0,S,1,0
193,1,2,"Navratil, Master. Michel M",male,3.00,1,1,26.0,0,S,1,6
194,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.00,0,0,27.0,0,C,0,2
195,1,1,"Lurette, Miss. Elise",female,58.00,0,0,146.0,8,C,0,2
196,0,3,"Mernagh, Mr. Robert",male,NaN,0,0,7.0,0,Q,0,0
197,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.00,0,1,8.0,0,S,1,0
198,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,7.0,0,Q,0,0
199,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.00,0,0,13.0,0,S,0,0
200,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28.00,0,0,9.0,0,S,0,0
201,0,3,"Sage, Mr. Frederick",male,NaN,8,2,69.0,0,S,3,0
202,0,3,"Johanson, Mr. Jakob Alfred",male,34.00,0,0,6.0,0,S,0,0
203,0,3,"Youseff, Mr. Gerious",male,45.50,0,0,7.0,0,C,0,0
204,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18.00,0,0,8.0,0,S,0,0
205,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,10.0,0,S,1,7
206,0,3,"Backstrom, Mr. Karl Alfred",male,32.00,1,0,15.0,0,S,1,0
207,1,3,"Albimona, Mr. Nassef Cassem",male,26.00,0,0,18.0,0,C,0,0
208,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,7.0,0,Q,0,0
209,1,1,"Blank, Mr. Henry",male,40.00,0,0,31.0,3,C,0,1
210,0,3,"Ali, Mr. Ahmed",male,24.00,0,0,7.0,0,S,0,0
211,1,2,"Cameron, Miss. Clear Annie",female,35.00,0,0,21.0,0,S,0,0
212,0,3,"Perkin, Mr. John Henry",male,22.00,0,0,7.0,0,S,0,0
213,0,2,"Givard, Mr. Hans Kristensen",male,30.00,0,0,13.0,0,S,0,0
214,0,3,"Kiernan, Mr. Philip",male,NaN,1,0,7.0,0,Q,1,0
215,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,113.0,3,C,1,4
216,1,3,"Honkanen, Miss. Eliina",female,27.00,0,0,7.0,0,S,0,0
217,0,2,"Jacobsohn, Mr. Sidney Samuel",male,42.00,1,0,27.0,0,S,1,0
218,1,1,"Bazzani, Miss. Albina",female,32.00,0,0,76.0,1,C,0,4
219,0,2,"Harris, Mr. Walter",male,30.00,0,0,10.0,0,S,0,0
220,1,3,"Sunderland, Mr. Victor Francis",male,16.00,0,0,8.0,0,S,0,0
221,0,2,"Bracken, Mr. James H",male,27.00,0,0,13.0,0,S,0,0
222,0,3,"Green, Mr. George Henry",male,51.00,0,0,8.0,0,S,0,0
223,0,3,"Nenkoff, Mr. Christo",male,NaN,0,0,7.0,0,S,0,0
224,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.00,1,0,90.0,9,S,1,3
225,0,3,"Berglund, Mr. Karl Ivar Sven",male,22.00,0,0,9.0,0,S,0,0
226,1,2,"Mellors, Mr. William John",male,19.00,0,0,10.0,0,S,0,0
227,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.50,0,0,7.0,0,S,0,0
228,0,2,"Fahlstrom, Mr. Arne Jonas",male,18.00,0,0,13.0,0,S,0,0
229,0,3,"Lefebre, Miss. Mathilde",female,NaN,3,1,25.0,0,S,2,0
230,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.00,1,0,83.0,8,S,1,3
231,0,3,"Larsson, Mr. Bengt Edvin",male,29.00,0,0,7.0,0,S,0,0
232,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.00,0,0,13.0,0,S,0,0
233,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,31.0,0,S,2,0
234,0,2,"Leyson, Mr. Robert William Norman",male,24.00,0,0,10.0,0,S,0,0
235,0,3,"Harknett, Miss. Alice Phoebe",female,NaN,0,0,7.0,0,S,0,0
236,0,2,"Hold, Mr. Stephen",male,44.00,1,0,26.0,0,S,1,0
237,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,26.0,0,S,1,0
238,0,2,"Pengelly, Mr. Frederick William",male,19.00,0,0,10.0,0,S,0,0
239,0,2,"Hunt, Mr. George Henry",male,33.00,0,0,12.0,0,S,0,0
240,0,3,"Zabour, Miss. Thamine",female,NaN,1,0,14.0,0,C,1,0
241,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,15.0,0,Q,1,0
242,0,2,"Coleridge, Mr. Reginald Charles",male,29.00,0,0,10.0,0,S,0,0
243,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22.00,0,0,7.0,0,S,0,0
244,0,3,"Attalah, Mr. Sleiman",male,30.00,0,0,7.0,0,C,0,0
245,0,1,"Minahan, Dr. William Edward",male,44.00,2,0,90.0,7,Q,1,3
246,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25.00,0,0,7.0,0,S,0,0
247,1,2,"Hamalainen, Mrs. William (Anna)",female,24.00,0,2,14.0,0,S,1,0
248,1,1,"Beckwith, Mr. Richard Leonard",male,37.00,1,1,52.0,3,S,1,4
249,0,2,"Carter, Rev. Ernest Courtenay",male,54.00,1,0,26.0,0,S,1,0
250,0,3,"Reed, Mr. James George",male,NaN,0,0,7.0,0,S,0,0
251,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.00,1,1,10.0,0,S,1,7
252,0,1,"Stead, Mr. William Thomas",male,62.00,0,0,26.0,8,S,0,3
253,0,3,"Lobb, Mr. William Arthur",male,30.00,1,0,16.0,0,S,1,0
254,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.00,0,2,20.0,0,S,1,0
255,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.00,0,2,15.0,0,C,1,0
256,1,1,"Thorne, Mrs. Gertrude Maybelle",female,NaN,0,0,79.0,0,C,0,0
257,1,1,"Cherry, Miss. Gladys",female,30.00,0,0,86.0,7,S,0,2
258,1,1,"Ward, Miss. Anna",female,35.00,0,0,512.0,0,C,0,0
259,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.00,0,1,26.0,0,S,1,0
260,0,3,"Smith, Mr. Thomas",male,NaN,0,0,7.0,0,Q,0,0
261,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,31.0,0,S,2,0
262,0,1,"Taussig, Mr. Emil",male,52.00,1,1,79.0,6,S,1,5
263,0,1,"Harrison, Mr. William",male,40.00,0,0,0.0,9,S,0,2
264,0,3,"Henry, Miss. Delia",female,NaN,0,0,7.0,0,Q,0,0
265,0,2,"Reeves, Mr. David",male,36.00,0,0,10.0,0,S,0,0
266,0,3,"Panula, Mr. Ernesti Arvid",male,16.00,4,1,39.0,0,S,2,0
267,1,3,"Persson, Mr. Ernst Ulrik",male,25.00,1,0,7.0,0,S,1,0
268,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,153.0,12,S,1,3
269,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,135.0,9,S,0,3
270,0,1,"Cairns, Mr. Alexander",male,NaN,0,0,31.0,0,S,0,0
271,1,3,"Tornquist, Mr. William Henry",male,25.00,0,0,0.0,0,S,0,0
272,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.00,0,1,19.0,0,S,1,0
273,0,1,"Natsch, Mr. Charles H",male,37.00,0,1,29.0,11,C,1,3
274,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,7.0,0,Q,0,0
275,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,77.0,0,S,1,4
276,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.00,0,0,7.0,0,S,0,0
277,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,0.0,0,S,0,0
278,0,3,"Rice, Master. Eric",male,7.00,4,1,29.0,0,Q,2,0
279,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.00,1,1,20.0,0,S,1,0
280,0,3,"Duane, Mr. Frank",male,65.00,0,0,7.0,0,Q,0,0
281,0,3,"Olsson, Mr. Nils Johan Goransson",male,28.00,0,0,7.0,0,S,0,0
282,0,3,"de Pelsmaeker, Mr. Alfons",male,16.00,0,0,9.0,0,S,0,0
283,1,3,"Dorking, Mr. Edward Arthur",male,19.00,0,0,8.0,0,S,0,0
284,0,1,"Smith, Mr. Richard William",male,NaN,0,0,26.0,1,S,0,1
285,0,3,"Stankovic, Mr. Ivan",male,33.00,0,0,8.0,0,C,0,0
286,1,3,"de Mulder, Mr. Theodore",male,30.00,0,0,9.0,0,S,0,0
287,0,3,"Naidenoff, Mr. Penko",male,22.00,0,0,7.0,0,S,0,0
288,1,2,"Hosono, Mr. Masabumi",male,42.00,0,0,13.0,0,S,0,0
289,1,3,"Connolly, Miss. Kate",female,22.00,0,0,7.0,0,Q,0,0
290,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.00,0,0,78.0,0,S,0,0
291,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.00,1,0,91.0,4,C,1,2
292,0,2,"Levy, Mr. Rene Jacques",male,36.00,0,0,12.0,9,C,0,9
293,0,3,"Haas, Miss. Aloisia",female,24.00,0,0,8.0,0,S,0,0
294,0,3,"Mineff, Mr. Ivan",male,24.00,0,0,7.0,0,S,0,0
295,0,1,"Lewy, Mr. Ervin G",male,NaN,0,0,27.0,0,C,0,0
296,0,3,"Hanna, Mr. Mansour",male,23.50,0,0,7.0,0,C,0,0
297,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,151.0,2,S,1,3
298,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,30.0,10,S,0,3
299,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,247.0,5,C,1,2
300,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,7.0,0,Q,0,0
301,1,3,"McCoy, Mr. Bernard",male,NaN,2,0,23.0,0,Q,1,0
302,0,3,"Johnson, Mr. William Cahoone Jr",male,19.00,0,0,0.0,0,S,0,0
303,1,2,"Keane, Miss. Nora A",female,NaN,0,0,12.0,10,Q,0,5

In [89]:
cb=["x","1","2","3"]
for i in range(0,891):
    #print(df.loc[df.index == i, 'Cabin'],df.iloc[i]['Cabin'])
    if (type(df.loc[df.index[i],'Cabin']) == str):
       #df.loc[df.index[i],'Cabin']=df.loc[df.index[i],'Cabin'][0]+cb[df.loc[df.index[i],'Pclass']]
        df.loc[df.index[i],'Cabin']=df.loc[df.index[i],'Cabin'][0]
    else:
        df.loc[df.index[i],'Cabin']='M'

for i in range(0,418):
    #print(df.loc[df.index == i, 'Cabin'],df.iloc[i]['Cabin'])
    if (type(dfTest.loc[df.index[i],'Cabin']) == str):
       #dfTest.loc[dfTest.index[i],'Cabin']=dfTest.loc[dfTest.index[i],'Cabin'][0]+cb[dfTest.loc[dfTest.index[i],'Pclass']]
        dfTest.loc[dfTest.index[i],'Cabin']=dfTest.loc[dfTest.index[i],'Cabin'][0]
    else:
        dfTest.loc[dfTest.index[i],'Cabin']='M'

In [11]:

titlesTrain=df['Name'].str.extract(' ([a-zA-Z]+)\.', expand= False).unique()
titlesTest=dfTest['Name'].str.extract(' ([a-zA-Z]+)\.', expand= False).unique()

emTrain=df['Embarked'].unique()
emTest=dfTest['Embarked'].unique()

"""cabinTrain=df['Cabin'].unique()
cabinTest=dfTest['Cabin'].unique()"""

print(emTrain,emTest)
titles=np.append(titlesTest,titlesTrain)
embark=np.append(emTest,emTrain)
#cabin=np.append(cabinTrain, cabinTest)
print(embark)


titles=np.unique(titles)
embark=np.unique(embark)
#cabin=np.unique(cabin)

titles[2]='the'
sex=[0,1]
#print(titles, embark,cabin)

['S' 'C' 'Q'] ['Q' 'S' 'C']
['Q' 'S' 'C' 'S' 'C' 'Q']

In [12]:
for i in range(0,891):
    s=df.loc[df.index[i], 'Sex'].split(",")
    if(s[0] == 'male'):
        df.loc[df.index[i], 'Sex']=sex[0]
    else:
        df.loc[df.index[i], 'Sex']=sex[1]

for i in range(0,418):
    s=dfTest.loc[dfTest.index[i], 'Sex'].split(",")
    if(s[0] == 'male'):
        dfTest.loc[dfTest.index[i], 'Sex']=sex[0]
    else:
        dfTest.loc[dfTest.index[i], 'Sex']=sex[1]

KeyError: 'Sex'

In [158]:
for i in range(0,891):
    s=df.loc[df.index[i], 'Cabin']
    #print(s)
    df.loc[df.index[i], 'Cabin']=np.where(cabin == s)[0][0].astype(int)
    #print(np.where(cabin == s)[0][0],i)
for i in range(0,418):
    s=dfTest.loc[dfTest.index[i], 'Cabin']
    dfTest.loc[dfTest.index[i], 'Cabin']=np.where(cabin == s)[0][0].astype(int)
    #print(np.where(cabin == s)[0][0],i)

KeyError: 'Cabin'

In [13]:
for i in range(0,891):
    s=df.loc[df.index[i], 'Embarked']
    #print(s)
    df.loc[df.index[i], 'Embarked']=np.where(embark == s)[0][0].astype(int)
    #print(np.where(embark == s)[0][0],i)
for i in range(0,418):
    s=dfTest.loc[dfTest.index[i], 'Embarked']
    dfTest.loc[dfTest.index[i], 'Embarked']=np.where(embark == s)[0][0].astype(int)
    #print(np.where(embark == s)[0][0],i)

In [14]:
for i in range(0,891):
    tmp=df.loc[df.index[i], 'Name'].split(",")
    t=tmp[1].split(".")
    #print(t)
    t=t[0].split()
    print(t)
    df.loc[df.index[i], 'Name']=np.where(titles == t[0])[0][0].astype(int)
    print(np.where(titles == t[0])[0][0],i)

['Mr']
13 0
['Mrs']
14 1
['Miss']
10 2
['Mrs']
14 3
['Mr']
13 4
['Mr']
13 5
['Mr']
13 6
['Master']
9 7
['Mrs']
14 8
['Mrs']
14 9
['Miss']
10 10
['Miss']
10 11
['Mr']
13 12
['Mr']
13 13
['Miss']
10 14
['Mrs']
14 15
['Master']
9 16
['Mr']
13 17
['Mrs']
14 18
['Mrs']
14 19
['Mr']
13 20
['Mr']
13 21
['Miss']
10 22
['Mr']
13 23
['Miss']
10 24
['Mrs']
14 25
['Mr']
13 26
['Mr']
13 27
['Miss']
10 28
['Mr']
13 29
['Don']
3 30
['Mrs']
14 31
['Miss']
10 32
['Mr']
13 33
['Mr']
13 34
['Mr']
13 35
['Mr']
13 36
['Mr']
13 37
['Miss']
10 38
['Miss']
10 39
['Mrs']
14 40
['Mrs']
14 41
['Mr']
13 42
['Miss']
10 43
['Miss']
10 44
['Mr']
13 45
['Mr']
13 46
['Miss']
10 47
['Mr']
13 48
['Mrs']
14 49
['Master']
9 50
['Mr']
13 51
['Mrs']
14 52
['Mrs']
14 53
['Mr']
13 54
['Mr']
13 55
['Miss']
10 56
['Mr']
13 57
['Miss']
10 58
['Master']
9 59
['Mr']
13 60
['Miss']
10 61
['Mr']
13 62
['Master']
9 63
['Mr']
13 64
['Master']
9 65
['Mrs']
14 66
['Mr']
13 67
['Miss']
10 68
['Mr']
13 69
['Mr']
13 70
['Miss']
10 71
['Mr']
13 72
['Mr']
13 73
['Mr']
13 74
['Mr']
13 75
['Mr']
13 76
['Mr']
13 77
['Master']
9 78
['Miss']
10 79
['Mr']
13 80
['Mr']
13 81
['Miss']
10 82
['Mr']
13 83
['Miss']
10 84
['Mrs']
14 85
['Mr']
13 86
['Mr']
13 87
['Miss']
10 88
['Mr']
13 89
['Mr']
13 90
['Mr']
13 91
['Mr']
13 92
['Mr']
13 93
['Mr']
13 94
['Mr']
13 95
['Mr']
13 96
['Mr']
13 97
['Mrs']
14 98
['Mr']
13 99
['Miss']
10 100
['Mr']
13 101
['Mr']
13 102
['Mr']
13 103
['Mr']
13 104
['Mr']
13 105
['Miss']
10 106
['Mr']
13 107
['Mr']
13 108
['Miss']
10 109
['Mr']
13 110
['Miss']
10 111
['Mr']
13 112
['Miss']
10 113
['Miss']
10 114
['Mr']
13 115
['Mr']
13 116
['Mr']
13 117
['Mr']
13 118
['Miss']
10 119
['Mr']
13 120
['Mr']
13 121
['Mr']
13 122
['Miss']
10 123
['Mr']
13 124
['Master']
9 125
['Mr']
13 126
['Mr']
13 127
['Miss']
10 128
['Mr']
13 129
['Mr']
13 130
['Mr']
13 131
['Mrs']
14 132
['Mrs']
14 133
['Mr']
13 134
['Mr']
13 135
['Miss']
10 136
['Mr']
13 137
['Mr']
13 138
['Mr']
13 139
['Mrs']
14 140
['Miss']
10 141
['Mrs']
14 142
['Mr']
13 143
['Mr']
13 144
['Mr']
13 145
['Mr']
13 146
['Miss']
10 147
['Mr']
13 148
['Rev']
16 149
['Rev']
16 150
['Mrs']
14 151
['Mr']
13 152
['Mr']
13 153
['Mr']
13 154
['Mr']
13 155
['Miss']
10 156
['Mr']
13 157
['Mr']
13 158
['Master']
9 159
['Mr']
13 160
['Mrs']
14 161
['Mr']
13 162
['Mr']
13 163
['Master']
9 164
['Master']
9 165
['Mrs']
14 166
['Mrs']
14 167
['Mr']
13 168
['Mr']
13 169
['Mr']
13 170
['Master']
9 171
['Miss']
10 172
['Mr']
13 173
['Mr']
13 174
['Mr']
13 175
['Master']
9 176
['Miss']
10 177
['Mr']
13 178
['Mr']
13 179
['Miss']
10 180
['Mr']
13 181
['Master']
9 182
['Master']
9 183
['Miss']
10 184
['Mr']
13 185
['Mrs']
14 186
['Mr']
13 187
['Mr']
13 188
['Mr']
13 189
['Mrs']
14 190
['Mr']
13 191
['Miss']
10 192
['Master']
9 193
['Mrs']
14 194
['Miss']
10 195
['Mr']
13 196
['Mr']
13 197
['Miss']
10 198
['Miss']
10 199
['Mr']
13 200
['Mr']
13 201
['Mr']
13 202
['Mr']
13 203
['Mr']
13 204
['Miss']
10 205
['Mr']
13 206
['Mr']
13 207
['Miss']
10 208
['Mr']
13 209
['Mr']
13 210
['Miss']
10 211
['Mr']
13 212
['Mr']
13 213
['Mr']
13 214
['Miss']
10 215
['Miss']
10 216
['Mr']
13 217
['Miss']
10 218
['Mr']
13 219
['Mr']
13 220
['Mr']
13 221
['Mr']
13 222
['Mr']
13 223
['Mr']
13 224
['Mr']
13 225
['Mr']
13 226
['Mr']
13 227
['Mr']
13 228
['Miss']
10 229
['Mrs']
14 230
['Mr']
13 231
['Mr']
13 232
['Miss']
10 233
['Mr']
13 234
['Miss']
10 235
['Mr']
13 236
['Miss']
10 237
['Mr']
13 238
['Mr']
13 239
['Miss']
10 240
['Miss']
10 241
['Mr']
13 242
['Mr']
13 243
['Mr']
13 244
['Dr']
5 245
['Miss']
10 246
['Mrs']
14 247
['Mr']
13 248
['Rev']
16 249
['Mr']
13 250
['Mrs']
14 251
['Mr']
13 252
['Mr']
13 253
['Mrs']
14 254
['Mrs']
14 255
['Mrs']
14 256
['Miss']
10 257
['Miss']
10 258
['Mrs']
14 259
['Mr']
13 260
['Master']
9 261
['Mr']
13 262
['Mr']
13 263
['Miss']
10 264
['Mr']
13 265
['Mr']
13 266
['Mr']
13 267
['Mrs']
14 268
['Miss']
10 269
['Mr']
13 270
['Mr']
13 271
['Mrs']
14 272
['Mr']
13 273
['Miss']
10 274
['Miss']
10 275
['Miss']
10 276
['Mr']
13 277
['Master']
9 278
['Mrs']
14 279
['Mr']
13 280
['Mr']
13 281
['Mr']
13 282
['Mr']
13 283
['Mr']
13 284
['Mr']
13 285
['Mr']
13 286
['Mr']
13 287
['Mr']
13 288
['Miss']
10 289
['Miss']
10 290
['Mrs']
14 291
['Mr']
13 292
['Miss']
10 293
['Mr']
13 294
['Mr']
13 295
['Mr']
13 296
['Miss']
10 297
['Mr']
13 298
['Mrs']
14 299
['Miss']
10 300
['Mr']
13 301
['Mr']
13 302
['Miss']
10 303
['Mr']
13 304
['Master']
9 305
['Miss']
10 306
['Mrs']
14 307
['Mr']
13 308
['Miss']
10 309
['Miss']
10 310
['Miss']
10 311
['Mrs']
14 312
['Mr']
13 313
['Mr']
13 314
['Miss']
10 315
['Mrs']
14 316
['Dr']
5 317
['Miss']
10 318
['Mrs']
14 319
['Mr']
13 320
['Mr']
13 321
['Miss']
10 322
['Mrs']
14 323
['Mr']
13 324
['Miss']
10 325
['Mr']
13 326
['Mrs']
14 327
['Mrs']
14 328
['Miss']
10 329
['Miss']
10 330
['Mr']
13 331
['Mr']
13 332
['Mr']
13 333
['Mrs']
14 334
['Mr']
13 335
['Mr']
13 336
['Miss']
10 337
['Mr']
13 338
['Mr']
13 339
['Master']
9 340
['Miss']
10 341
['Mr']
13 342
['Mr']
13 343
['Mr']
13 344
['Miss']
10 345
['Miss']
10 346
['Mrs']
14 347
['Master']
9 348
['Mr']
13 349
['Mr']
13 350
['Mr']
13 351
['Mr']
13 352
['Mr']
13 353
['Mr']
13 354
['Mr']
13 355
['Miss']
10 356
['Miss']
10 357
['Miss']
10 358
['Miss']
10 359
['Mr']
13 360
['Mr']
13 361
['Mrs']
14 362
['Mr']
13 363
['Mr']
13 364
['Mr']
13 365
['Mrs']
14 366
['Mrs']
14 367
['Miss']
10 368
['Mme']
12 369
['Mr']
13 370
['Mr']
13 371
['Mr']
13 372
['Mr']
13 373
['Miss']
10 374
['Mrs']
14 375
['Miss']
10 376
['Mr']
13 377
['Mr']
13 378
['Mr']
13 379
['Miss']
10 380
['Miss']
10 381
['Mr']
13 382
['Mrs']
14 383
['Mr']
13 384
['Mr']
13 385
['Master']
9 386
['Miss']
10 387
['Mr']
13 388
['Miss']
10 389
['Mr']
13 390
['Mr']
13 391
['Mr']
13 392
['Miss']
10 393
['Mrs']
14 394
['Mr']
13 395
['Miss']
10 396
['Mr']
13 397
['Dr']
5 398
['Mrs']
14 399
['Mr']
13 400
['Mr']
13 401
['Miss']
10 402
['Mr']
13 403
['Miss']
10 404
['Mr']
13 405
['Mr']
13 406
['Master']
9 407
['Mr']
13 408
['Miss']
10 409
['Mr']
13 410
['Mr']
13 411
['Miss']
10 412
['Mr']
13 413
['Mr']
13 414
['Mrs']
14 415
['Mrs']
14 416
['Miss']
10 417
['Mr']
13 418
['Miss']
10 419
['Mr']
13 420
['Mr']
13 421
['Mr']
13 422
['Mrs']
14 423
['Mr']
13 424
['Mr']
13 425
['Mrs']
14 426
['Miss']
10 427
['Mr']
13 428
['Mr']
13 429
['Mr']
13 430
['Mrs']
14 431
['Mrs']
14 432
['Mr']
13 433
['Mr']
13 434
['Miss']
10 435
['Miss']
10 436
['Mrs']
14 437
['Mr']
13 438
['Mr']
13 439
['Mrs']
14 440
['Mr']
13 441
['Mr']
13 442
['Ms']
15 443
['Mr']
13 444
['Master']
9 445
['Miss']
10 446
['Mr']
13 447
['Miss']
10 448
['Major']
8 449
['Mr']
13 450
['Mr']
13 451
['Mr']
13 452
['Mr']
13 453
['Mr']
13 454
['Mr']
13 455
['Mr']
13 456
['Mrs']
14 457
['Miss']
10 458
['Mr']
13 459
['Mr']
13 460
['Mr']
13 461
['Mr']
13 462
['Mr']
13 463
['Mr']
13 464
['Mr']
13 465
['Mr']
13 466
['Mr']
13 467
['Mr']
13 468
['Miss']
10 469
['Mr']
13 470
['Mr']
13 471
['Mrs']
14 472
['Mrs']
14 473
['Miss']
10 474
['Mr']
13 475
['Mr']
13 476
['Mr']
13 477
['Mr']
13 478
['Miss']
10 479
['Master']
9 480
['Mr']
13 481
['Mr']
13 482
['Mrs']
14 483
['Mr']
13 484
['Miss']
10 485
['Mrs']
14 486
['Mr']
13 487
['Mr']
13 488
['Master']
9 489
['Mr']
13 490
['Mr']
13 491
['Mr']
13 492
['Mr']
13 493
['Mr']
13 494
['Mr']
13 495
['Miss']
10 496
['Mr']
13 497
['Mrs']
14 498
['Mr']
13 499
['Mr']
13 500
['Miss']
10 501
['Miss']
10 502
['Miss']
10 503
['Miss']
10 504
['Mr']
13 505
['Mrs']
14 506
['Mr']
13 507
['Mr']
13 508
['Mr']
13 509
['Mr']
13 510
['Mr']
13 511
['Mr']
13 512
['Mrs']
14 513
['Mr']
13 514
['Mr']
13 515
['Mrs']
14 516
['Mr']
13 517
['Mrs']
14 518
['Mr']
13 519
['Miss']
10 520
['Mr']
13 521
['Mr']
13 522
['Mrs']
14 523
['Mr']
13 524
['Mr']
13 525
['Miss']
10 526
['Mr']
13 527
['Mr']
13 528
['Mr']
13 529
['Miss']
10 530
['Mr']
13 531
['Mr']
13 532
['Mrs']
14 533
['Miss']
10 534
['Miss']
10 535
['Major']
8 536
['Miss']
10 537
['Mr']
13 538
['Miss']
10 539
['Miss']
10 540
['Miss']
10 541
['Miss']
10 542
['Mr']
13 543
['Mr']
13 544
['Mr']
13 545
['Mrs']
14 546
['Mr']
13 547
['Mr']
13 548
['Master']
9 549
['Mr']
13 550
['Mr']
13 551
['Mr']
13 552
['Mr']
13 553
['Miss']
10 554
['Mr']
13 555
['Lady']
7 556
['Mr']
13 557
['Mrs']
14 558
['Mrs']
14 559
['Mr']
13 560
['Mr']
13 561
['Mr']
13 562
['Mr']
13 563
['Miss']
10 564
['Mr']
13 565
['Mr']
13 566
['Mrs']
14 567
['Mr']
13 568
['Mr']
13 569
['Mr']
13 570
['Mrs']
14 571
['Mr']
13 572
['Miss']
10 573
['Mr']
13 574
['Mr']
13 575
['Miss']
10 576
['Mrs']
14 577
['Mrs']
14 578
['Mr']
13 579
['Miss']
10 580
['Mrs']
14 581
['Mr']
13 582
['Mr']
13 583
['Mr']
13 584
['Miss']
10 585
['Mr']
13 586
['Mr']
13 587
['Mr']
13 588
['Mr']
13 589
['Mr']
13 590
['Mrs']
14 591
['Mr']
13 592
['Miss']
10 593
['Mr']
13 594
['Mr']
13 595
['Miss']
10 596
['Mr']
13 597
['Mr']
13 598
['Sir']
17 599
['Mrs']
14 600
['Mr']
13 601
['Mr']
13 602
['Mr']
13 603
['Mr']
13 604
['Mr']
13 605
['Mr']
13 606
['Mr']
13 607
['Mrs']
14 608
['Miss']
10 609
['Mrs']
14 610
['Mr']
13 611
['Miss']
10 612
['Mr']
13 613
['Mr']
13 614
['Miss']
10 615
['Mr']
13 616
['Mrs']
14 617
['Miss']
10 618
['Mr']
13 619
['Mr']
13 620
['Mr']
13 621
['Mr']
13 622
['Mr']
13 623
['Mr']
13 624
['Mr']
13 625
['Rev']
16 626
['Miss']
10 627
['Mr']
13 628
['Mr']
13 629
['Mr']
13 630
['Mr']
13 631
['Dr']
5 632
['Mr']
13 633
['Miss']
10 634
['Miss']
10 635
['Mr']
13 636
['Mr']
13 637
['Mrs']
14 638
['Mr']
13 639
['Mr']
13 640
['Mlle']
11 641
['Miss']
10 642
['Mr']
13 643
['Miss']
10 644
['Mr']
13 645
['Mr']
13 646
['Col']
1 647
['Mr']
13 648
['Miss']
10 649
['Mr']
13 650
['Miss']
10 651
['Mr']
13 652
['Miss']
10 653
['Miss']
10 654
['Mr']
13 655
['Mr']
13 656
['Mrs']
14 657
['Mr']
13 658
['Mr']
13 659
['Dr']
5 660
['Mr']
13 661
['Mr']
13 662
['Mr']
13 663
['Mr']
13 664
['Mr']
13 665
['Mr']
13 666
['Mr']
13 667
['Mr']
13 668
['Mrs']
14 669
['Mrs']
14 670
['Mr']
13 671
['Mr']
13 672
['Mr']
13 673
['Mr']
13 674
['Mr']
13 675
['Mr']
13 676
['Miss']
10 677
['Mrs']
14 678
['Mr']
13 679
['Miss']
10 680
['Mr']
13 681
['Mr']
13 682
['Mr']
13 683
['Mr']
13 684
['Mr']
13 685
['Mr']
13 686
['Mr']
13 687
['Mr']
13 688
['Miss']
10 689
['Mr']
13 690
['Miss']
10 691
['Mr']
13 692
['Mr']
13 693
['Col']
1 694
['Mr']
13 695
['Mr']
13 696
['Miss']
10 697
['Mr']
13 698
['Mr']
13 699
['Mrs']
14 700
['Mr']
13 701
['Miss']
10 702
['Mr']
13 703
['Mr']
13 704
['Mr']
13 705
['Mrs']
14 706
['Mr']
13 707
['Miss']
10 708
['Master']
9 709
['Mlle']
11 710
['Mr']
13 711
['Mr']
13 712
['Mr']
13 713
['Mr']
13 714
['Mr']
13 715
['Miss']
10 716
['Miss']
10 717
['Mr']
13 718
['Mr']
13 719
['Miss']
10 720
['Mr']
13 721
['Mr']
13 722
['Mr']
13 723
['Mr']
13 724
['Mr']
13 725
['Mrs']
14 726
['Miss']
10 727
['Mr']
13 728
['Miss']
10 729
['Miss']
10 730
['Mr']
13 731
['Mr']
13 732
['Mr']
13 733
['Mr']
13 734
['Mr']
13 735
['Mrs']
14 736
['Mr']
13 737
['Mr']
13 738
['Mr']
13 739
['Mr']
13 740
['Mr']
13 741
['Miss']
10 742
['Mr']
13 743
['Mr']
13 744
['Capt']
0 745
['Mr']
13 746
['Miss']
10 747
['Mr']
13 748
['Mr']
13 749
['Miss']
10 750
['Master']
9 751
['Mr']
13 752
['Mr']
13 753
['Mrs']
14 754
['Master']
9 755
['Mr']
13 756
['Mr']
13 757
['Mr']
13 758
['the', 'Countess']
2 759
['Mr']
13 760
['Mr']
13 761
['Mr']
13 762
['Mrs']
14 763
['Mr']
13 764
['Mrs']
14 765
['Dr']
5 766
['Miss']
10 767
['Mr']
13 768
['Mr']
13 769
['Mr']
13 770
['Mr']
13 771
['Mrs']
14 772
['Mr']
13 773
['Mrs']
14 774
['Mr']
13 775
['Mr']
13 776
['Miss']
10 777
['Mr']
13 778
['Mrs']
14 779
['Miss']
10 780
['Mrs']
14 781
['Mr']
13 782
['Mr']
13 783
['Mr']
13 784
['Mr']
13 785
['Miss']
10 786
['Master']
9 787
['Master']
9 788
['Mr']
13 789
['Mr']
13 790
['Mr']
13 791
['Miss']
10 792
['Mr']
13 793
['Mr']
13 794
['Mr']
13 795
['Dr']
5 796
['Mrs']
14 797
['Mr']
13 798
['Mrs']
14 799
['Mr']
13 800
['Mrs']
14 801
['Master']
9 802
['Master']
9 803
['Mr']
13 804
['Mr']
13 805
['Mr']
13 806
['Miss']
10 807
['Mr']
13 808
['Mrs']
14 809
['Mr']
13 810
['Mr']
13 811
['Mr']
13 812
['Miss']
10 813
['Mr']
13 814
['Mr']
13 815
['Miss']
10 816
['Mr']
13 817
['Mr']
13 818
['Master']
9 819
['Mrs']
14 820
['Mr']
13 821
['Jonkheer']
6 822
['Mrs']
14 823
['Master']
9 824
['Mr']
13 825
['Mr']
13 826
['Master']
9 827
['Mr']
13 828
['Mrs']
14 829
['Mrs']
14 830
['Master']
9 831
['Mr']
13 832
['Mr']
13 833
['Mr']
13 834
['Miss']
10 835
['Mr']
13 836
['Mr']
13 837
['Mr']
13 838
['Mr']
13 839
['Mr']
13 840
['Mr']
13 841
['Miss']
10 842
['Mr']
13 843
['Mr']
13 844
['Mr']
13 845
['Mr']
13 846
['Mr']
13 847
['Rev']
16 848
['Mrs']
14 849
['Master']
9 850
['Mr']
13 851
['Miss']
10 852
['Miss']
10 853
['Mrs']
14 854
['Mrs']
14 855
['Mrs']
14 856
['Mr']
13 857
['Mrs']
14 858
['Mr']
13 859
['Mr']
13 860
['Mr']
13 861
['Mrs']
14 862
['Miss']
10 863
['Mr']
13 864
['Mrs']
14 865
['Miss']
10 866
['Mr']
13 867
['Mr']
13 868
['Master']
9 869
['Mr']
13 870
['Mrs']
14 871
['Mr']
13 872
['Mr']
13 873
['Mrs']
14 874
['Miss']
10 875
['Mr']
13 876
['Mr']
13 877
['Mr']
13 878
['Mrs']
14 879
['Mrs']
14 880
['Mr']
13 881
['Miss']
10 882
['Mr']
13 883
['Mr']
13 884
['Mrs']
14 885
['Rev']
16 886
['Miss']
10 887
['Miss']
10 888
['Mr']
13 889
['Mr']
13 890

In [15]:
for i in range(0,418):
    tmp=dfTest.loc[dfTest.index[i], 'Name'].split(",")
    t=tmp[1].split(".")
    #print(t)
    t=t[0].split()
    print(t)
    dfTest.loc[dfTest.index[i], 'Name']=np.where(titles == t[0])[0][0].astype(int)
    print(np.where(titles == t[0])[0][0],i)

['Mr']
13 0
['Mrs']
14 1
['Mr']
13 2
['Mr']
13 3
['Mrs']
14 4
['Mr']
13 5
['Miss']
10 6
['Mr']
13 7
['Mrs']
14 8
['Mr']
13 9
['Mr']
13 10
['Mr']
13 11
['Mrs']
14 12
['Mr']
13 13
['Mrs']
14 14
['Mrs']
14 15
['Mr']
13 16
['Mr']
13 17
['Miss']
10 18
['Mrs']
14 19
['Mr']
13 20
['Master']
9 21
['Mrs']
14 22
['Mr']
13 23
['Mrs']
14 24
['Mr']
13 25
['Miss']
10 26
['Mr']
13 27
['Mr']
13 28
['Mr']
13 29
['Mr']
13 30
['Mr']
13 31
['Mrs']
14 32
['Mrs']
14 33
['Mr']
13 34
['Mr']
13 35
['Miss']
10 36
['Miss']
10 37
['Mr']
13 38
['Mr']
13 39
['Mr']
13 40
['Mr']
13 41
['Mr']
13 42
['Mrs']
14 43
['Mrs']
14 44
['Mr']
13 45
['Mr']
13 46
['Mr']
13 47
['Mrs']
14 48
['Mrs']
14 49
['Mr']
13 50
['Mr']
13 51
['Miss']
10 52
['Miss']
10 53
['Mr']
13 54
['Master']
9 55
['Mr']
13 56
['Mr']
13 57
['Mr']
13 58
['Miss']
10 59
['Mr']
13 60
['Mr']
13 61
['Mr']
13 62
['Miss']
10 63
['Master']
9 64
['Mrs']
14 65
['Miss']
10 66
['Mr']
13 67
['Mr']
13 68
['Mrs']
14 69
['Miss']
10 70
['Mr']
13 71
['Miss']
10 72
['Mr']
13 73
['Miss']
10 74
['Mr']
13 75
['Mr']
13 76
['Mrs']
14 77
['Mr']
13 78
['Miss']
10 79
['Master']
9 80
['Mr']
13 81
['Mr']
13 82
['Mr']
13 83
['Mr']
13 84
['Mr']
13 85
['Miss']
10 86
['Miss']
10 87
['Ms']
15 88
['Master']
9 89
['Mrs']
14 90
['Mr']
13 91
['Mrs']
14 92
['Mr']
13 93
['Mr']
13 94
['Mr']
13 95
['Mrs']
14 96
['Mr']
13 97
['Miss']
10 98
['Mr']
13 99
['Mrs']
14 100
['Mr']
13 101
['Mr']
13 102
['Mr']
13 103
['Mrs']
14 104
['Mr']
13 105
['Mr']
13 106
['Mr']
13 107
['Mr']
13 108
['Mr']
13 109
['Mr']
13 110
['Miss']
10 111
['Miss']
10 112
['Miss']
10 113
['Mrs']
14 114
['Mr']
13 115
['Mr']
13 116
['Miss']
10 117
['Mr']
13 118
['Mrs']
14 119
['Miss']
10 120
['Mr']
13 121
['Mrs']
14 122
['Mr']
13 123
['Mr']
13 124
['Miss']
10 125
['Mr']
13 126
['Miss']
10 127
['Mr']
13 128
['Mr']
13 129
['Mr']
13 130
['Col']
1 131
['Mrs']
14 132
['Mr']
13 133
['Mr']
13 134
['Mr']
13 135
['Mr']
13 136
['Mr']
13 137
['Miss']
10 138
['Mr']
13 139
['Miss']
10 140
['Miss']
10 141
['Mr']
13 142
['Mr']
13 143
['Mr']
13 144
['Mr']
13 145
['Mr']
13 146
['Mr']
13 147
['Mr']
13 148
['Rev']
16 149
['Mrs']
14 150
['Mr']
13 151
['Mr']
13 152
['Mrs']
14 153
['Master']
9 154
['Mr']
13 155
['Miss']
10 156
['Miss']
10 157
['Mr']
13 158
['Mrs']
14 159
['Miss']
10 160
['Master']
9 161
['Miss']
10 162
['Mr']
13 163
['Rev']
16 164
['Mrs']
14 165
['Mr']
13 166
['Mr']
13 167
['Mrs']
14 168
['Miss']
10 169
['Mr']
13 170
['Mr']
13 171
['Mr']
13 172
['Mr']
13 173
['Mr']
13 174
['Miss']
10 175
['Miss']
10 176
['Mr']
13 177
['Mrs']
14 178
['Mrs']
14 179
['Mr']
13 180
['Mr']
13 181
['Mrs']
14 182
['Mr']
13 183
['Mrs']
14 184
['Mr']
13 185
['Miss']
10 186
['Mr']
13 187
['Miss']
10 188
['Mr']
13 189
['Mr']
13 190
['Mr']
13 191
['Master']
9 192
['Mr']
13 193
['Master']
9 194
['Mr']
13 195
['Master']
9 196
['Miss']
10 197
['Mr']
13 198
['Mrs']
14 199
['Miss']
10 200
['Master']
9 201
['Col']
1 202
['Miss']
10 203
['Mr']
13 204
['Mr']
13 205
['Miss']
10 206
['Mr']
13 207
['Miss']
10 208
['Mr']
13 209
['Mr']
13 210
['Mr']
13 211
['Mr']
13 212
['Mrs']
14 213
['Miss']
10 214
['Mr']
13 215
['Miss']
10 216
['Mr']
13 217
['Mrs']
14 218
['Mr']
13 219
['Miss']
10 220
['Mr']
13 221
['Mrs']
14 222
['Mr']
13 223
['Mrs']
14 224
['Mrs']
14 225
['Mr']
13 226
['Miss']
10 227
['Mr']
13 228
['Mr']
13 229
['Mr']
13 230
['Miss']
10 231
['Mr']
13 232
['Mr']
13 233
['Mr']
13 234
['Mr']
13 235
['Mr']
13 236
['Mr']
13 237
['Miss']
10 238
['Mrs']
14 239
['Mrs']
14 240
['Mrs']
14 241
['Mr']
13 242
['Mr']
13 243
['Master']
9 244
['Mr']
13 245
['Mrs']
14 246
['Mr']
13 247
['Mrs']
14 248
['Mrs']
14 249
['Miss']
10 250
['Mr']
13 251
['Mr']
13 252
['Mr']
13 253
['Mr']
13 254
['Mr']
13 255
['Mr']
13 256
['Mr']
13 257
['Miss']
10 258
['Mr']
13 259
['Mr']
13 260
['Mr']
13 261
['Mrs']
14 262
['Miss']
10 263
['Mr']
13 264
['Mr']
13 265
['Mr']
13 266
['Mr']
13 267
['Miss']
10 268
['Mr']
13 269
['Mr']
13 270
['Mr']
13 271
['Mrs']
14 272
['Miss']
10 273
['Mr']
13 274
['Miss']
10 275
['Mr']
13 276
['Mr']
13 277
['Mr']
13 278
['Mr']
13 279
['Miss']
10 280
['Master']
9 281
['Miss']
10 282
['Miss']
10 283
['Miss']
10 284
['Mr']
13 285
['Mr']
13 286
['Mr']
13 287
['Mr']
13 288
['Mr']
13 289
['Mr']
13 290
['Miss']
10 291
['Mr']
13 292
['Dr']
5 293
['Mr']
13 294
['Mr']
13 295
['Miss']
10 296
['Mr']
13 297
['Mr']
13 298
['Mr']
13 299
['Mr']
13 300
['Mr']
13 301
['Mr']
13 302
['Mr']
13 303
['Miss']
10 304
['Mrs']
14 305
['Mr']
13 306
['Master']
9 307
['Mr']
13 308
['Mrs']
14 309
['Mr']
13 310
['Mr']
13 311
['Mr']
13 312
['Miss']
10 313
['Mrs']
14 314
['Miss']
10 315
['Mr']
13 316
['Mr']
13 317
['Mr']
13 318
['Mr']
13 319
['Mr']
13 320
['Mr']
13 321
['Mr']
13 322
['Mr']
13 323
['Miss']
10 324
['Mr']
13 325
['Miss']
10 326
['Mr']
13 327
['Mr']
13 328
['Mr']
13 329
['Mrs']
14 330
['Mr']
13 331
['Mr']
13 332
['Mrs']
14 333
['Mr']
13 334
['Mr']
13 335
['Mr']
13 336
['Mr']
13 337
['Mr']
13 338
['Master']
9 339
['Mr']
13 340
['Mr']
13 341
['Mr']
13 342
['Mrs']
14 343
['Master']
9 344
['Miss']
10 345
['Mr']
13 346
['Mrs']
14 347
['Mr']
13 348
['Miss']
10 349
['Mrs']
14 350
['Mr']
13 351
['Mr']
13 352
['Mr']
13 353
['Miss']
10 354
['Mr']
13 355
['Mrs']
14 356
['Mr']
13 357
['Mr']
13 358
['Mrs']
14 359
['Master']
9 360
['Mrs']
14 361
['Mrs']
14 362
['Mr']
13 363
['Mrs']
14 364
['Mrs']
14 365
['Mr']
13 366
['Miss']
10 367
['Mrs']
14 368
['Mr']
13 369
['Mr']
13 370
['Miss']
10 371
['Mr']
13 372
['Mr']
13 373
['Mrs']
14 374
['Miss']
10 375
['Miss']
10 376
['Mr']
13 377
['Mr']
13 378
['Master']
9 379
['Mr']
13 380
['Mr']
13 381
['Mrs']
14 382
['Mrs']
14 383
['Mr']
13 384
['Miss']
10 385
['Mr']
13 386
['Mr']
13 387
['Mr']
13 388
['Master']
9 389
['Mr']
13 390
['Mrs']
14 391
['Master']
9 392
['Mr']
13 393
['Mr']
13 394
['Mrs']
14 395
['Mr']
13 396
['Mrs']
14 397
['Mr']
13 398
['Mr']
13 399
['Miss']
10 400
['Mr']
13 401
['Miss']
10 402
['Mr']
13 403
['Mr']
13 404
['Mr']
13 405
['Mr']
13 406
['Mr']
13 407
['Miss']
10 408
['Miss']
10 409
['Miss']
10 410
['Mrs']
14 411
['Miss']
10 412
['Mr']
13 413
['Dona']
4 414
['Mr']
13 415
['Mr']
13 416
['Master']
9 417

In [16]:
df

     Survived  Pclass Name    Age  SibSp  Parch      Fare Embarked Family Size
0           0       3   13  22.00      1      0    7.2500        2           1
1           1       1   14  38.00      1      0   71.2833        0           1
2           1       3   10  26.00      0      0    7.9250        2           0
3           1       1   14  35.00      1      0   53.1000        2           1
4           0       3   13  35.00      0      0    8.0500        2           0
5           0       3   13    NaN      0      0    8.4583        1           0
6           0       1   13  54.00      0      0   51.8625        2           0
7           0       3    9   2.00      3      1   21.0750        2           2
8           1       3   14  27.00      0      2   11.1333        2           1
9           1       2   14  14.00      1      0   30.0708        0           1
10          1       3   10   4.00      1      1   16.7000        2           1
11          1       1   10  58.00      0      0   26.5500        2           0
12          0       3   13  20.00      0      0    8.0500        2           0
13          0       3   13  39.00      1      5   31.2750        2           2
14          0       3   10  14.00      0      0    7.8542        2           0
15          1       2   14  55.00      0      0   16.0000        2           0
16          0       3    9   2.00      4      1   29.1250        1           2
17          1       2   13    NaN      0      0   13.0000        2           0
18          0       3   14  31.00      1      0   18.0000        2           1
19          1       3   14    NaN      0      0    7.2250        0           0
20          0       2   13  35.00      0      0   26.0000        2           0
21          1       2   13  34.00      0      0   13.0000        2           0
22          1       3   10  15.00      0      0    8.0292        1           0
23          1       1   13  28.00      0      0   35.5000        2           0
24          0       3   10   8.00      3      1   21.0750        2           2
25          1       3   14  38.00      1      5   31.3875        2           2
26          0       3   13    NaN      0      0    7.2250        0           0
27          0       1   13  19.00      3      2  263.0000        2           2
28          1       3   10    NaN      0      0    7.8792        1           0
29          0       3   13    NaN      0      0    7.8958        2           0
30          0       1    3  40.00      0      0   27.7208        0           0
31          1       1   14    NaN      1      0  146.5208        0           1
32          1       3   10    NaN      0      0    7.7500        1           0
33          0       2   13  66.00      0      0   10.5000        2           0
34          0       1   13  28.00      1      0   82.1708        0           1
35          0       1   13  42.00      1      0   52.0000        2           1
36          1       3   13    NaN      0      0    7.2292        0           0
37          0       3   13  21.00      0      0    8.0500        2           0
38          0       3   10  18.00      2      0   18.0000        2           1
39          1       3   10  14.00      1      0   11.2417        0           1
40          0       3   14  40.00      1      0    9.4750        2           1
41          0       2   14  27.00      1      0   21.0000        2           1
42          0       3   13    NaN      0      0    7.8958        0           0
43          1       2   10   3.00      1      2   41.5792        0           1
44          1       3   10  19.00      0      0    7.8792        1           0
45          0       3   13    NaN      0      0    8.0500        2           0
46          0       3   13    NaN      1      0   15.5000        1           1
47          1       3   10    NaN      0      0    7.7500        1           0
48          0       3   13    NaN      2      0   21.6792        0           1
49          0       3   14  18.00      1      0   17.8000        2           1
50          0       3    9   7.00      4      1   39.6875        2           2
51          0       3   13  21.00      0      0    7.8000        2           0
52          1       1   14  49.00      1      0   76.7292        0           1
53          1       2   14  29.00      1      0   26.0000        2           1
54          0       1   13  65.00      0      1   61.9792        0           1
55          1       1   13    NaN      0      0   35.5000        2           0
56          1       2   10  21.00      0      0   10.5000        2           0
57          0       3   13  28.50      0      0    7.2292        0           0
58          1       2   10   5.00      1      2   27.7500        2           1
59          0       3    9  11.00      5      2   46.9000        2           3
60          0       3   13  22.00      0      0    7.2292        0           0
61          1       1   10  38.00      0      0   80.0000        2           0
62          0       1   13  45.00      1      0   83.4750        2           1
63          0       3    9   4.00      3      2   27.9000        2           2
64          0       1   13    NaN      0      0   27.7208        0           0
65          1       3    9    NaN      1      1   15.2458        0           1
66          1       2   14  29.00      0      0   10.5000        2           0
67          0       3   13  19.00      0      0    8.1583        2           0
68          1       3   10  17.00      4      2    7.9250        2           2
69          0       3   13  26.00      2      0    8.6625        2           1
70          0       2   13  32.00      0      0   10.5000        2           0
71          0       3   10  16.00      5      2   46.9000        2           3
72          0       2   13  21.00      0      0   73.5000        2           0
73          0       3   13  26.00      1      0   14.4542        0           1
74          1       3   13  32.00      0      0   56.4958        2           0
75          0       3   13  25.00      0      0    7.6500        2           0
76          0       3   13    NaN      0      0    7.8958        2           0
77          0       3   13    NaN      0      0    8.0500        2           0
78          1       2    9   0.83      0      2   29.0000        2           1
79          1       3   10  30.00      0      0   12.4750        2           0
80          0       3   13  22.00      0      0    9.0000        2           0
81          1       3   13  29.00      0      0    9.5000        2           0
82          1       3   10    NaN      0      0    7.7875        1           0
83          0       1   13  28.00      0      0   47.1000        2           0
84          1       2   10  17.00      0      0   10.5000        2           0
85          1       3   14  33.00      3      0   15.8500        2           1
86          0       3   13  16.00      1      3   34.3750        2           2
87          0       3   13    NaN      0      0    8.0500        2           0
88          1       1   10  23.00      3      2  263.0000        2           2
89          0       3   13  24.00      0      0    8.0500        2           0
90          0       3   13  29.00      0      0    8.0500        2           0
91          0       3   13  20.00      0      0    7.8542        2           0
92          0       1   13  46.00      1      0   61.1750        2           1
93          0       3   13  26.00      1      2   20.5750        2           1
94          0       3   13  59.00      0      0    7.2500        2           0
95          0       3   13    NaN      0      0    8.0500        2           0
96          0       1   13  71.00      0      0   34.6542        0           0
97          1       1   13  23.00      0      1   63.3583        0           1
98          1       2   14  34.00      0      1   23.0000        2           1
99          0       2   13  34.00      1      0   26.0000        2           1
100         0       3   10  28.00      0      0    7.8958        2           0
101         0       3   13    NaN      0      0    7.8958        2           0
102         0       1   13  21.00      0      1   77.2875        2           1
103         0       3   13  33.00      0      0    8.6542        2           0
104         0       3   13  37.00      2      0    7.9250        2           1
105         0       3   13  28.00      0      0    7.8958        2           0
106         1       3   10  21.00      0      0    7.6500        2           0
107         1       3   13    NaN      0      0    7.7750        2           0
108         0       3   13  38.00      0      0    7.8958        2           0
109         1       3   10    NaN      1      0   24.1500        1           1
110         0       1   13  47.00      0      0   52.0000        2           0
111         0       3   10  14.50      1      0   14.4542        0           1
112         0       3   13  22.00      0      0    8.0500        2           0
113         0       3   10  20.00      1      0    9.8250        2           1
114         0       3   10  17.00      0      0   14.4583        0           0
115         0       3   13  21.00      0      0    7.9250        2           0
116         0       3   13  70.50      0      0    7.7500        1           0
117         0       2   13  29.00      1      0   21.0000        2           1
118         0       1   13  24.00      0      1  247.5208        0           1
119         0       3   10   2.00      4      2   31.2750        2           2
120         0       2   13  21.00      2      0   73.5000        2           1
121         0       3   13    NaN      0      0    8.0500        2           0
122         0       2   13  32.50      1      0   30.0708        0           1
123         1       2   10  32.50      0      0   13.0000        2           0
124         0       1   13  54.00      0      1   77.2875        2           1
125         1       3    9  12.00      1      0   11.2417        0           1
126         0       3   13    NaN      0      0    7.7500        1           0
127         1       3   13  24.00      0      0    7.1417        2           0
128         1       3   10    NaN      1      1   22.3583        0           1
129         0       3   13  45.00      0      0    6.9750        2           0
130         0       3   13  33.00      0      0    7.8958        0           0
131         0       3   13  20.00      0      0    7.0500        2           0
132         0       3   14  47.00      1      0   14.5000        2           1
133         1       2   14  29.00      1      0   26.0000        2           1
134         0       2   13  25.00      0      0   13.0000        2           0
135         0       2   13  23.00      0      0   15.0458        0           0
136         1       1   10  19.00      0      2   26.2833        2           1
137         0       1   13  37.00      1      0   53.1000        2           1
138         0       3   13  16.00      0      0    9.2167        2           0
139         0       1   13  24.00      0      0   79.2000        0           0
140         0       3   14    NaN      0      2   15.2458        0           1
141         1       3   10  22.00      0      0    7.7500        2           0
142         1       3   14  24.00      1      0   15.8500        2           1
143         0       3   13  19.00      0      0    6.7500        1           0
144         0       2   13  18.00      0      0   11.5000        2           0
145         0       2   13  19.00      1      1   36.7500        2           1
146         1       3   13  27.00      0      0    7.7958        2           0
147         0       3   10   9.00      2      2   34.3750        2           2
148         0       2   13  36.50      0      2   26.0000        2           1
149         0       2   16  42.00      0      0   13.0000        2           0
150         0       2   16  51.00      0      0   12.5250        2           0
151         1       1   14  22.00      1      0   66.6000        2           1
152         0       3   13  55.50      0      0    8.0500        2           0
153         0       3   13  40.50      0      2   14.5000        2           1
154         0       3   13    NaN      0      0    7.3125        2           0
155         0       1   13  51.00      0      1   61.3792        0           1
156         1       3   10  16.00      0      0    7.7333        1           0
157         0       3   13  30.00      0      0    8.0500        2           0
158         0       3   13    NaN      0      0    8.6625        2           0
159         0       3    9    NaN      8      2   69.5500        2           3
160         0       3   13  44.00      0      1   16.1000        2           1
161         1       2   14  40.00      0      0   15.7500        2           0
162         0       3   13  26.00      0      0    7.7750        2           0
163         0       3   13  17.00      0      0    8.6625        2           0
164         0       3    9   1.00      4      1   39.6875        2           2
165         1       3    9   9.00      0      2   20.5250        2           1
166         1       1   14    NaN      0      1   55.0000        2           1
167         0       3   14  45.00      1      4   27.9000        2           2
168         0       1   13    NaN      0      0   25.9250        2           0
169         0       3   13  28.00      0      0   56.4958        2           0
170         0       1   13  61.00      0      0   33.5000        2           0
171         0       3    9   4.00      4      1   29.1250        1           2
172         1       3   10   1.00      1      1   11.1333        2           1
173         0       3   13  21.00      0      0    7.9250        2           0
174         0       1   13  56.00      0      0   30.6958        0           0
175         0       3   13  18.00      1      1    7.8542        2           1
176         0       3    9    NaN      3      1   25.4667        2           2
177         0       1   10  50.00      0      0   28.7125        0           0
178         0       2   13  30.00      0      0   13.0000        2           0
179         0       3   13  36.00      0      0    0.0000        2           0
180         0       3   10    NaN      8      2   69.5500        2           3
181         0       2   13    NaN      0      0   15.0500        0           0
182         0       3    9   9.00      4      2   31.3875        2           2
183         1       2    9   1.00      2      1   39.0000        2           1
184         1       3   10   4.00      0      2   22.0250        2           1
185         0       1   13    NaN      0      0   50.0000        2           0
186         1       3   14    NaN      1      0   15.5000        1           1
187         1       1   13  45.00      0      0   26.5500        2           0
188         0       3   13  40.00      1      1   15.5000        1           1
189         0       3   13  36.00      0      0    7.8958        2           0
190         1       2   14  32.00      0      0   13.0000        2           0
191         0       2   13  19.00      0      0   13.0000        2           0
192         1       3   10  19.00      1      0    7.8542        2           1
193         1       2    9   3.00      1      1   26.0000        2           1
194         1       1   14  44.00      0      0   27.7208        0           0
195         1       1   10  58.00      0      0  146.5208        0           0
196         0       3   13    NaN      0      0    7.7500        1           0
197         0       3   13  42.00      0      1    8.4042        2           1
198         1       3   10    NaN      0      0    7.7500        1           0
199         0       2   10  24.00      0      0   13.0000        2           0
200         0       3   13  28.00      0      0    9.5000        2           0
201         0       3   13    NaN      8      2   69.5500        2           3
202         0       3   13  34.00      0      0    6.4958        2           0
203         0       3   13  45.50      0      0    7.2250        0           0
204         1       3   13  18.00      0      0    8.0500        2           0
205         0       3   10   2.00      0      1   10.4625        2           1
206         0       3   13  32.00      1      0   15.8500        2           1
207         1       3   13  26.00      0      0   18.7875        0           0
208         1       3   10  16.00      0      0    7.7500        1           0
209         1       1   13  40.00      0      0   31.0000        0           0
210         0       3   13  24.00      0      0    7.0500        2           0
211         1       2   10  35.00      0      0   21.0000        2           0
212         0       3   13  22.00      0      0    7.2500        2           0
213         0       2   13  30.00      0      0   13.0000        2           0
214         0       3   13    NaN      1      0    7.7500        1           1
215         1       1   10  31.00      1      0  113.2750        0           1
216         1       3   10  27.00      0      0    7.9250        2           0
217         0       2   13  42.00      1      0   27.0000        2           1
218         1       1   10  32.00      0      0   76.2917        0           0
219         0       2   13  30.00      0      0   10.5000        2           0
220         1       3   13  16.00      0      0    8.0500        2           0
221         0       2   13  27.00      0      0   13.0000        2           0
222         0       3   13  51.00      0      0    8.0500        2           0
223         0       3   13    NaN      0      0    7.8958        2           0
224         1       1   13  38.00      1      0   90.0000        2           1
225         0       3   13  22.00      0      0    9.3500        2           0
226         1       2   13  19.00      0      0   10.5000        2           0
227         0       3   13  20.50      0      0    7.2500        2           0
228         0       2   13  18.00      0      0   13.0000        2           0
229         0       3   10    NaN      3      1   25.4667        2           2
230         1       1   14  35.00      1      0   83.4750        2           1
231         0       3   13  29.00      0      0    7.7750        2           0
232         0       2   13  59.00      0      0   13.5000        2           0
233         1       3   10   5.00      4      2   31.3875        2           2
234         0       2   13  24.00      0      0   10.5000        2           0
235         0       3   10    NaN      0      0    7.5500        2           0
236         0       2   13  44.00      1      0   26.0000        2           1
237         1       2   10   8.00      0      2   26.2500        2           1
238         0       2   13  19.00      0      0   10.5000        2           0
239         0       2   13  33.00      0      0   12.2750        2           0
240         0       3   10    NaN      1      0   14.4542        0           1
241         1       3   10    NaN      1      0   15.5000        1           1
242         0       2   13  29.00      0      0   10.5000        2           0
243         0       3   13  22.00      0      0    7.1250        2           0
244         0       3   13  30.00      0      0    7.2250        0           0
245         0       1    5  44.00      2      0   90.0000        1           1
246         0       3   10  25.00      0      0    7.7750        2           0
247         1       2   14  24.00      0      2   14.5000        2           1
248         1       1   13  37.00      1      1   52.5542        2           1
249         0       2   16  54.00      1      0   26.0000        2           1
250         0       3   13    NaN      0      0    7.2500        2           0
251         0       3   14  29.00      1      1   10.4625        2           1

In [17]:
dfTest.drop(columns=['Embarked'], inplace=True)
df.drop(columns=['Embarked'], inplace=True)
dfTest.drop(columns=['Age'], inplace=True)
df.drop(columns=['Age'], inplace=True)
dfTest.drop(columns=['Fare'], inplace=True)
df.drop(columns=['Fare'], inplace=True)

In [18]:
for label, content in df.items():
    if pd.api.types.is_object_dtype(content):
        df[label] = content.astype(int)
for label, content in dfTest.items():
    if pd.api.types.is_object_dtype(content):
        dfTest[label] = content.astype(int)
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       418 non-null    int64
 1   Name         418 non-null    int32
 2   SibSp        418 non-null    int64
 3   Parch        418 non-null    int64
 4   Family Size  418 non-null    category
dtypes: category(1), int32(1), int64(3)
memory usage: 12.2 KB

In [19]:

df['Family Size'] = pd.Categorical(df['Family Size']).codes
dfTest['Family Size'] = pd.Categorical(dfTest['Family Size']).codes

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Survived     891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Name         891 non-null    int32
 3   SibSp        891 non-null    int64
 4   Parch        891 non-null    int64
 5   Family Size  891 non-null    int8
dtypes: int32(1), int64(4), int8(1)
memory usage: 32.3 KB

In [53]:
df.isnull().sum()

Survived        0
Pclass          0
Name            0
Age             0
SibSp           0
Parch           0
Fare            0
Cabin           0
Embarked        0
Family Size     0
Cabin Letter    0
dtype: int64

In [21]:
one= pd.concat([df[df['Pclass'] == 1]['Age'],dfTest[dfTest['Pclass'] == 1]['Age']], ignore_index=True)
two= pd.concat([df[df['Pclass'] == 2]['Age'],dfTest[dfTest['Pclass'] == 2]['Age']], ignore_index=True)
there= pd.concat([df[df['Pclass'] == 2]['Age'],dfTest[dfTest['Pclass'] == 2]['Age']], ignore_index=True)
Pcl=[0,one.median(),two.median(),there.median()]
j=0;
for label,content in df.items():
    if (label== 'Age'):
        for i in range(0,891):
            if(np.isnan(df.iloc[i][label])):
                P=int(df.iloc[i]['Pclass'])
                #print(Pcl[P])
                df.loc[df.index[i],'Age']=Pcl[P]

for label,content in dfTest.items():
    if (label== 'Age'):
        for i in range(0,418):
            if(np.isnan(dfTest.iloc[i][label])):
                P=int(dfTest.iloc[i]['Pclass'])
                dfTest.loc[dfTest.index[i],'Age']=Pcl[P]

In [42]:
for index,row in df.iterrows():
    fare=row['Age']
    if(fare <15):
        df.loc[df.index[index],'Age'] = 1
    elif(fare <30):
        df.loc[df.index[index],'Age'] = 3
    elif(fare <40):
        df.loc[df.index[index],'Age'] = 4
    elif(fare <60):
        df.loc[df.index[index],'Age'] = 5
    else:
        df.loc[df.index[index],'Age'] = 8
        
for index,row in dfTest.iterrows():
    fare=row['Age']
    if(fare <15):
        dfTest.loc[dfTest.index[index],'Age'] = 1
    elif(fare <30):
        dfTest.loc[dfTest.index[index],'Age'] = 3
    elif(fare <40):
        dfTest.loc[dfTest.index[index],'Age'] = 4
    elif(fare <60):
        dfTest.loc[dfTest.index[index],'Age'] = 5
    else:
        dfTest.loc[dfTest.index[index],'Age'] = 8

In [21]:
np.random.seed(42)

X = df.drop("Survived", axis =1)
y = df.Survived.values


X_train,X_valid, y_train, y_valid = train_test_split(X,y,test_size=0.5,random_state=42)

In [26]:
modelReg= LogisticRegression(solver="liblinear",random_state=42)
modelReg.fit(X_train, y_train)
modelReg.score(X_valid,y_valid)

0.7062780269058296

In [25]:
modelRF= RandomForestClassifier(n_estimators=450, random_state=42,min_samples_split=4,min_samples_leaf=2,max_depth=None)
modelRF.fit(X_train, y_train)


v_acc = cross_val_score(modelRF,
                         X,
                         y,
                         cv=kfold_splitter, # 5-fold cross-validation
                         scoring="accuracy")

print(v_acc,np.mean(v_acc),modelRF.score(X_valid, y_valid))

[0.80446927 0.80898876 0.84269663 0.76966292 0.82022472] 0.8092084614901764 0.8183856502242153

In [220]:
modelDT= DecisionTreeClassifier(random_state=42)
modelDT.fit(X_train, y_train)
modelDT.score(X_valid, y_valid)

v_accDT = cross_val_score(modelDT,
                         X,
                         y,
                         cv=kfold_splitter, # 5-fold cross-validation
                         scoring="accuracy")

print(v_accDT,np.mean(v_accDT))

[0.79329609 0.73595506 0.78651685 0.80337079 0.8258427 ] 0.7889962965287804

In [24]:
from sklearn.model_selection import KFold

kfold_splitter = KFold(n_splits=5, random_state = 42, shuffle=True)

In [26]:
log_reg_grid = {"C": np.logspace(-4, 4, 20),
                "solver": ["liblinear"]}

# Different RandomForestClassifier hyperparameters
rf_grid = {"n_estimators": np.arange(10, 500, 50),
           "max_depth": [None],
           "random_state": [42],
           "min_samples_split": np.arange(2, 13, 2),
           "min_samples_leaf": np.arange(1, 13, 2),
          }

"""rs_rf= RandomizedSearchCV(RandomForestClassifier(),
                          param_distributions=rf_grid,
                          cv=5,
                          n_iter=100,
                          verbose=True)"""

gr_rf= GridSearchCV(RandomForestClassifier(),
                    param_grid=rf_grid,
                    cv=kfold_splitter,
                    n_jobs= -1,
                    verbose=True)


reg= GridSearchCV(LogisticRegression(),
                    param_grid=log_reg_grid,
                    cv=kfold_splitter,
                      n_jobs= -1,
                    verbose=True)

In [29]:
reg.fit(X_train,y_train)
reg.score(X_valid,y_valid)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

0.8026905829596412

In [30]:
reg.best_params_

{'C': 1.623776739188721, 'solver': 'liblinear'}

In [47]:
finalModel2=RandomForestClassifier(n_estimators=450, random_state=42,min_samples_split=4,min_samples_leaf=2,max_depth=None)
finalModel=LogisticRegression(solver="liblinear",random_state=42)
finalModel2.fit(X,y)
pred = finalModel2.predict(dfTest)

print(pred,len(pred))

[0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0
 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 0 1
 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0
 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0
 0 1 1 1 1 1 0 1 0 0 1] 418

In [367]:
X

     Pclass  Name  Sex  Age  Parch  Ticket   Fare  Embarked
0         3    13    0  3.0      0       0    7.0         2
1         1    14    1  4.0      0       1   71.0         0
2         3    10    1  3.0      0       0    7.0         2
3         1    14    1  4.0      0       1   53.0         2
4         3    13    0  4.0      0       0    8.0         2
5         3    13    0  3.0      0       0    8.0         1
6         1    13    0  5.0      0       1   51.0         2
7         3     9    0  1.0      1       1   21.0         2
8         3    14    1  3.0      2       1   11.0         2
9         2    14    1  1.0      0       1   30.0         0
10        3    10    1  1.0      1       1   16.0         2
11        1    10    1  5.0      0       0   26.0         2
12        3    13    0  3.0      0       0    8.0         2
13        3    13    0  4.0      5       1   31.0         2
14        3    10    1  1.0      0       0    7.0         2
15        2    14    1  5.0      0       0   16.0         2
16        3     9    0  1.0      1       1   29.0         1
17        2    13    0  3.0      0       0   13.0         2
18        3    14    1  4.0      0       1   18.0         2
19        3    14    1  3.0      0       0    7.0         0
20        2    13    0  4.0      0       1   26.0         2
21        2    13    0  4.0      0       0   13.0         2
22        3    10    1  3.0      0       0    8.0         1
23        1    13    0  3.0      0       0   35.0         2
24        3    10    1  1.0      1       1   21.0         2
25        3    14    1  4.0      5       1   31.0         2
26        3    13    0  3.0      0       0    7.0         0
27        1    13    0  3.0      2       1  263.0         2
28        3    10    1  3.0      0       0    7.0         1
29        3    13    0  3.0      0       0    7.0         2
30        1     3    0  5.0      0       0   27.0         0
31        1    14    1  4.0      0       1  146.0         0
32        3    10    1  3.0      0       0    7.0         1
33        2    13    0  8.0      0       0   10.0         2
34        1    13    0  3.0      0       1   82.0         0
35        1    13    0  5.0      0       1   52.0         2
36        3    13    0  3.0      0       0    7.0         0
37        3    13    0  3.0      0       0    8.0         2
38        3    10    1  3.0      0       1   18.0         2
39        3    10    1  1.0      0       1   11.0         0
40        3    14    1  5.0      0       0    9.0         2
41        2    14    1  3.0      0       1   21.0         2
42        3    13    0  3.0      0       0    7.0         0
43        2    10    1  1.0      2       1   41.0         0
44        3    10    1  3.0      0       0    7.0         1
45        3    13    0  3.0      0       0    8.0         2
46        3    13    0  3.0      0       1   15.0         1
47        3    10    1  3.0      0       0    7.0         1
48        3    13    0  3.0      0       1   21.0         0
49        3    14    1  3.0      0       1   17.0         2
50        3     9    0  1.0      1       1   39.0         2
51        3    13    0  3.0      0       0    7.0         2
52        1    14    1  5.0      0       1   76.0         0
53        2    14    1  3.0      0       1   26.0         2
54        1    13    0  8.0      1       1   61.0         0
55        1    13    0  4.0      0       0   35.0         2
56        2    10    1  3.0      0       0   10.0         2
57        3    13    0  3.0      0       0    7.0         0
58        2    10    1  1.0      2       1   27.0         2
59        3     9    0  1.0      2       1   46.0         2
60        3    13    0  3.0      0       0    7.0         0
61        1    10    1  4.0      0       1   80.0         2
62        1    13    0  5.0      0       1   83.0         2
63        3     9    0  1.0      2       1   27.0         2
64        1    13    0  4.0      0       0   27.0         0
65        3     9    0  3.0      1       1   15.0         0
66        2    14    1  3.0      0       0   10.0         2
67        3    13    0  3.0      0       0    8.0         2
68        3    10    1  3.0      2       0    7.0         2
69        3    13    0  3.0      0       0    8.0         2
70        2    13    0  4.0      0       0   10.0         2
71        3    10    1  3.0      2       1   46.0         2
72        2    13    0  3.0      0       1   73.0         2
73        3    13    0  3.0      0       1   14.0         0
74        3    13    0  4.0      0       1   56.0         2
75        3    13    0  3.0      0       0    7.0         2
76        3    13    0  3.0      0       0    7.0         2
77        3    13    0  3.0      0       0    8.0         2
78        2     9    0  1.0      2       1   29.0         2
79        3    10    1  4.0      0       1   12.0         2
80        3    13    0  3.0      0       0    9.0         2
81        3    13    0  3.0      0       0    9.0         2
82        3    10    1  3.0      0       0    7.0         1
83        1    13    0  3.0      0       1   47.0         2
84        2    10    1  3.0      0       0   10.0         2
85        3    14    1  4.0      0       1   15.0         2
86        3    13    0  3.0      3       1   34.0         2
87        3    13    0  3.0      0       0    8.0         2
88        1    10    1  3.0      2       1  263.0         2
89        3    13    0  3.0      0       0    8.0         2
90        3    13    0  3.0      0       0    8.0         2
91        3    13    0  3.0      0       0    7.0         2
92        1    13    0  5.0      0       1   61.0         2
93        3    13    0  3.0      2       1   20.0         2
94        3    13    0  5.0      0       0    7.0         2
95        3    13    0  3.0      0       0    8.0         2
96        1    13    0  8.0      0       0   34.0         0
97        1    13    0  3.0      1       1   63.0         0
98        2    14    1  4.0      1       1   23.0         2
99        2    13    0  4.0      0       1   26.0         2
100       3    10    1  3.0      0       0    7.0         2
101       3    13    0  3.0      0       0    7.0         2
102       1    13    0  3.0      1       1   77.0         2
103       3    13    0  4.0      0       0    8.0         2
104       3    13    0  4.0      0       0    7.0         2
105       3    13    0  3.0      0       0    7.0         2
106       3    10    1  3.0      0       0    7.0         2
107       3    13    0  3.0      0       0    7.0         2
108       3    13    0  4.0      0       0    7.0         2
109       3    10    1  3.0      0       1   24.0         1
110       1    13    0  5.0      0       1   52.0         2
111       3    10    1  1.0      0       1   14.0         0
112       3    13    0  3.0      0       0    8.0         2
113       3    10    1  3.0      0       0    9.0         2
114       3    10    1  3.0      0       1   14.0         0
115       3    13    0  3.0      0       0    7.0         2
116       3    13    0  8.0      0       0    7.0         1
117       2    13    0  3.0      0       1   21.0         2
118       1    13    0  3.0      1       1  247.0         0
119       3    10    1  1.0      2       1   31.0         2
120       2    13    0  3.0      0       1   73.0         2
121       3    13    0  3.0      0       0    8.0         2
122       2    13    0  4.0      0       1   30.0         0
123       2    10    1  4.0      0       0   13.0         2
124       1    13    0  5.0      1       1   77.0         2
125       3     9    0  1.0      0       1   11.0         0
126       3    13    0  3.0      0       0    7.0         1
127       3    13    0  3.0      0       0    7.0         2
128       3    10    1  3.0      1       1   22.0         0
129       3    13    0  5.0      0       0    6.0         2
130       3    13    0  4.0      0       0    7.0         0
131       3    13    0  3.0      0       0    7.0         2
132       3    14    1  5.0      0       1   14.0         2
133       2    14    1  3.0      0       1   26.0         2
134       2    13    0  3.0      0       0   13.0         2
135       2    13    0  3.0      0       0   15.0         0
136       1    10    1  3.0      2       0   26.0         2
137       1    13    0  4.0      0       1   53.0         2
138       3    13    0  3.0      0       1    9.0         2
139       1    13    0  3.0      0       1   79.0         0
140       3    14    1  3.0      2       1   15.0         0
141       3    10    1  3.0      0       0    7.0         2
142       3    14    1  3.0      0       1   15.0         2
143       3    13    0  3.0      0       0    6.0         1
144       2    13    0  3.0      0       0   11.0         2
145       2    13    0  3.0      1       1   36.0         2
146       3    13    0  3.0      0       0    7.0         2
147       3    10    1  1.0      2       1   34.0         2
148       2    13    0  4.0      2       1   26.0         2
149       2    16    0  5.0      0       0   13.0         2
150       2    16    0  5.0      0       0   12.0         2
151       1    14    1  3.0      0       1   66.0         2
152       3    13    0  5.0      0       0    8.0         2
153       3    13    0  5.0      2       1   14.0         2
154       3    13    0  3.0      0       0    7.0         2
155       1    13    0  5.0      1       1   61.0         0
156       3    10    1  3.0      0       0    7.0         1
157       3    13    0  4.0      0       0    8.0         2
158       3    13    0  3.0      0       0    8.0         2
159       3     9    0  3.0      2       1   69.0         2
160       3    13    0  5.0      1       1   16.0         2
161       2    14    1  5.0      0       1   15.0         2
162       3    13    0  3.0      0       0    7.0         2
163       3    13    0  3.0      0       0    8.0         2
164       3     9    0  1.0      1       1   39.0         2
165       3     9    0  1.0      2       1   20.0         2
166       1    14    1  4.0      1       1   55.0         2
167       3    14    1  5.0      4       1   27.0         2
168       1    13    0  4.0      0       0   25.0         2
169       3    13    0  3.0      0       1   56.0         2
170       1    13    0  8.0      0       0   33.0         2
171       3     9    0  1.0      1       1   29.0         1
172       3    10    1  1.0      1       1   11.0         2
173       3    13    0  3.0      0       0    7.0         2
174       1    13    0  5.0      0       0   30.0         0
175       3    13    0  3.0      1       0    7.0         2
176       3     9    0  3.0      1       1   25.0         2
177       1    10    1  5.0      0       0   28.0         0
178       2    13    0  4.0      0       0   13.0         2
179       3    13    0  4.0      0       1    0.0         2
180       3    10    1  3.0      2       1   69.0         2
181       2    13    0  3.0      0       0   15.0         0
182       3     9    0  1.0      2       1   31.0         2
183       2     9    0  1.0      1       1   39.0         2
184       3    10    1  1.0      2       1   22.0         2
185       1    13    0  4.0      0       0   50.0         2
186       3    14    1  3.0      0       1   15.0         1
187       1    13    0  5.0      0       0   26.0         2
188       3    13    0  5.0      1       1   15.0         1
189       3    13    0  4.0      0       0    7.0         2
190       2    14    1  4.0      0       0   13.0         2
191       2    13    0  3.0      0       0   13.0         2
192       3    10    1  3.0      0       0    7.0         2
193       2     9    0  1.0      1       1   26.0         2
194       1    14    1  5.0      0       0   27.0         0
195       1    10    1  5.0      0       1  146.0         0
196       3    13    0  3.0      0       0    7.0         1
197       3    13    0  5.0      1       0    8.0         2
198       3    10    1  3.0      0       0    7.0         1
199       2    10    1  3.0      0       0   13.0         2
200       3    13    0  3.0      0       0    9.0         2
201       3    13    0  3.0      2       1   69.0         2
202       3    13    0  4.0      0       0    6.0         2
203       3    13    0  5.0      0       0    7.0         0
204       3    13    0  3.0      0       0    8.0         2
205       3    10    1  1.0      1       1   10.0         2
206       3    13    0  4.0      0       1   15.0         2
207       3    13    0  3.0      0       1   18.0         0
208       3    10    1  3.0      0       0    7.0         1
209       1    13    0  5.0      0       0   31.0         0
210       3    13    0  3.0      0       0    7.0         2
211       2    10    1  4.0      0       1   21.0         2
212       3    13    0  3.0      0       0    7.0         2
213       2    13    0  4.0      0       0   13.0         2
214       3    13    0  3.0      0       0    7.0         1
215       1    10    1  4.0      0       1  113.0         0
216       3    10    1  3.0      0       0    7.0         2
217       2    13    0  5.0      0       1   27.0         2
218       1    10    1  4.0      0       1   76.0         0
219       2    13    0  4.0      0       0   10.0         2
220       3    13    0  3.0      0       0    8.0         2
221       2    13    0  3.0      0       0   13.0         2
222       3    13    0  5.0      0       0    8.0         2
223       3    13    0  3.0      0       0    7.0         2
224       1    13    0  4.0      0       1   90.0         2
225       3    13    0  3.0      0       0    9.0         2
226       2    13    0  3.0      0       0   10.0         2
227       3    13    0  3.0      0       0    7.0         2
228       2    13    0  3.0      0       0   13.0         2
229       3    10    1  3.0      1       1   25.0         2
230       1    14    1  4.0      0       1   83.0         2
231       3    13    0  3.0      0       0    7.0         2
232       2    13    0  5.0      0       0   13.0         2
233       3    10    1  1.0      2       1   31.0         2
234       2    13    0  3.0      0       0   10.0         2
235       3    10    1  3.0      0       0    7.0         2
236       2    13    0  5.0      0       1   26.0         2
237       2    10    1  1.0      2       1   26.0         2
238       2    13    0  3.0      0       0   10.0         2
239       2    13    0  4.0      0       0   12.0         2
240       3    10    1  3.0      0       1   14.0         0
241       3    10    1  3.0      0       1   15.0         1
242       2    13    0  3.0      0       0   10.0         2
243       3    13    0  3.0      0       0    7.0         2
244       3    13    0  4.0      0       0    7.0         0
245       1     5    0  5.0      0       1   90.0         1
246       3    10    1  3.0      0       0    7.0         2
247       2    14    1  3.0      2       1   14.0         2
248       1    13    0  4.0      1       1   52.0         2
249       2    16    0  5.0      0       1   26.0         2
250       3    13    0  3.0      0       0    7.0         2
251       3    14    1  3.0      1       1   10.0         2
252       1    13    0  8.0      0       0   26.0         2
253       3    13    0  4.0      0       1   16.0         2
254       3    14    1  5.0      2       1   20.0         2
255       3    14    1  3.0      2       1   15.0         0
256       1    14    1  4.0      0       1   79.0         0
257       1    10    1  4.0      0       1   86.0         2
258       1    10    1  4.0      0       1  512.0         0
259       2    14    1  5.0      1       1   26.0         2
260       3    13    0  3.0      0       0    7.0         1
261       3     9    0  1.0      2       1   31.0         2
262       1    13    0  5.0      1       1   79.0         2
263       1    13    0  5.0      0       0    0.0         2
264       3    10    1  3.0      0       0    7.0         1
265       2    13    0  4.0      0       0   10.0         2
266       3    13    0  3.0      1       1   39.0         2
267       3    13    0  3.0      0       0    7.0         2
268       1    14    1  5.0      1       1  153.0         2
269       1    10    1  4.0      0       1  135.0         2
270       1    13    0  4.0      0       1   31.0         2
271       3    13    0  3.0      0       1    0.0         2
272       2    14    1  5.0      1       1   19.0         2
273       1    13    0  4.0      1       0   29.0         0
274       3    10    1  3.0      0       0    7.0         1
275       1    10    1  8.0      0       1   77.0         2
276       3    10    1  5.0      0       0    7.0         2
277       2    13    0  3.0      0       1    0.0         2
278       3     9    0  1.0      1       1   29.0         1
279       3    14    1  4.0      1       1   20.0         2
280       3    13    0  8.0      0       0    7.0         1
281       3    13    0  3.0      0       0    7.0         2
282       3    13    0  3.0      0       0    9.0         2
283       3    13    0  3.0      0       0    8.0         2
284       1    13    0  4.0      0       0   26.0         2
285       3    13    0  4.0      0       0    8.0         0
286       3    13    0  4.0      0       0    9.0         2
287       3    13    0  3.0      0       0    7.0         2
288       2    13    0  5.0      0       0   13.0         2
289       3    10    1  3.0      0       0    7.0         1
290       1    10    1  3.0      0       1   78.0         2
291       1    14    1  3.0      0       1   91.0         0
292       2    13    0  4.0      0       0   12.0         0
293       3    10    1  3.0      0       0    8.0         2
294       3    13    0  3.0      0       0    7.0         2
295       1    13    0  4.0      0       0   27.0         0
296       3    13    0  3.0      0       0    7.0         0
297       1    10    1  1.0      2       1  151.0         2
298       1    13    0  4.0      0       0   30.0         2
299       1    14    1  5.0      1       1  247.0         0
300       3    10    1  3.0      0       0    7.0         1
301       3    13    0  3.0      0       1   23.0         1
302       3    13    0  3.0      0       1    0.0         2
303       2    10    1  3.0      0       0   12.0         1
304       3    13    0  3.0      0       0    8.0         2
305       1     9    0  1.0      2       1  151.0         2
306       1    10    1  4.0      0       1  110.0         0
307       1    14    1  3.0      0       1  108.0         0
308       2    13    0  4.0      0       1   24.0         0
309       1    10    1  4.0      0       1   56.0         0
310       1    10    1  3.0      0       1   83.0         0
311       1    10    1  3.0      2       1  262.0         0
312       2    14    1  3.0      1       1   26.0         2
313       3    13    0  3.0      0       0    7.0         2
314       2    13    0  5.0      1       1   26.0         2
315       3    10    1  3.0      0       0    7.0         2
316       2    14    1  3.0      0       1   26.0         2
317       2     5    0  5.0      0       0   14.0         2
318       1    10    1  4.0      2       1  164.0         2
319       1    14    1  5.0      1       1  134.0         0
320       3    13    0  3.0      0       0    7.0         2
321       3    13    0  3.0      0       0    7.0         2
322       2    10    1  4.0      0       0   12.0         1
323       2    14    1  3.0      1       1   29.0         2
324       3    13    0  3.0      2       1   69.0         2
325       1    10    1  4.0      0       1  135.0         0
326       3    13    0  8.0      0       0    6.0         2
327       2    14    1  4.0      0       0   13.0         2
328       3    14    1  4.0      1       1   20.0         2
329       1    10    1  3.0      1       1   57.0         0
330       3    10    1  3.0      0       1   23.0         1
331       1    13    0  5.0      0       0   28.0         2

In [41]:
dfTest

,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Family Size,Cabin Letter
0,3,13,0,34.50,0,0,7.0,0,1,0,0.0
1,3,14,1,47.00,1,0,7.0,0,2,1,0.0
2,2,13,0,62.00,0,0,9.0,0,1,0,0.0
3,3,13,0,27.00,0,0,8.0,0,2,0,0.0
4,3,14,1,22.00,1,1,12.0,0,2,1,0.0
5,3,13,0,14.00,0,0,9.0,0,2,0,0.0
6,3,10,1,30.00,0,0,7.0,0,1,0,0.0
7,2,13,0,26.00,1,1,29.0,0,2,1,0.0
8,3,14,1,18.00,0,0,7.0,0,0,0,0.0
9,3,13,0,21.00,2,0,24.0,0,2,1,0.0
10,3,13,0,29.00,0,0,7.0,0,2,0,0.0
11,1,13,0,46.00,0,0,26.0,0,2,0,0.0
12,1,14,1,23.00,1,0,82.0,4,2,1,2.0
13,2,13,0,63.00,1,0,26.0,0,2,1,0.0
14,1,14,1,47.00,1,0,61.0,3,2,1,5.0
15,2,14,1,24.00,1,0,27.0,0,0,1,0.0
16,2,13,0,35.00,0,0,12.0,0,1,0,0.0
17,3,13,0,21.00,0,0,7.0,0,0,0,0.0
18,3,10,1,27.00,1,0,7.0,0,2,1,0.0
19,3,14,1,45.00,0,0,7.0,0,0,0,0.0
20,1,13,0,55.00,1,0,59.0,0,0,1,0.0
21,3,9,0,9.00,0,1,3.0,0,2,1,0.0
22,1,14,1,39.00,0,0,31.0,0,2,0,0.0
23,1,13,0,21.00,0,1,61.0,0,0,1,0.0
24,1,14,1,48.00,1,3,262.0,5,0,2,2.0
25,3,13,0,50.00,1,0,14.0,0,2,1,0.0
26,1,10,1,22.00,0,1,61.0,3,0,1,2.0
27,3,13,0,22.50,0,0,7.0,0,0,0,0.0
28,1,13,0,41.00,0,0,30.0,2,2,0,1.0
29,3,13,0,29.00,2,0,21.0,0,0,1,0.0
30,2,13,0,50.00,1,0,26.0,0,2,1,0.0
31,2,13,0,24.00,2,0,31.0,0,2,1,0.0
32,3,14,1,33.00,1,2,20.0,0,2,1,0.0
33,3,14,1,29.00,1,2,23.0,0,2,1,0.0
34,1,13,0,30.00,1,0,57.0,7,0,1,3.0
35,3,13,0,18.50,0,0,7.0,0,0,0,0.0
36,3,10,1,29.00,0,0,8.0,0,2,0,0.0
37,3,10,1,21.00,0,0,8.0,0,2,0,0.0
38,3,13,0,25.00,0,0,9.0,0,2,0,0.0
39,3,13,0,29.00,0,0,56.0,0,2,0,0.0
40,3,13,0,39.00,0,1,13.0,0,0,1,0.0
41,1,13,0,39.00,0,0,26.0,3,2,0,4.0
42,3,13,0,41.00,0,0,7.0,0,2,0,0.0
43,2,14,1,30.00,0,0,13.0,0,2,0,0.0
44,1,14,1,45.00,1,0,52.0,1,2,1,4.0
45,3,13,0,25.00,0,0,7.0,0,2,0,0.0
46,1,13,0,45.00,0,0,29.0,0,0,0,1.0
47,3,13,0,29.00,0,0,7.0,0,1,0,0.0
48,1,14,1,60.00,0,0,76.0,1,0,0,4.0
49,3,14,1,36.00,0,2,15.0,0,2,1,0.0
50,1,13,0,24.00,1,0,60.0,3,2,1,3.0
51,2,13,0,27.00,0,0,15.0,0,0,0,0.0
52,2,10,1,20.00,2,1,23.0,0,2,1,0.0
53,1,10,1,28.00,3,2,263.0,2,2,2,3.0
54,2,13,0,29.00,0,0,15.0,0,0,0,0.0
55,3,9,0,10.00,4,1,29.0,0,1,2,0.0
56,3,13,0,35.00,0,0,7.0,0,2,0,0.0
57,3,13,0,25.00,0,0,7.0,9,2,0,9.0
58,3,13,0,29.00,1,0,16.0,0,2,1,0.0
59,1,10,1,36.00,0,0,262.0,6,0,0,2.0
60,3,13,0,17.00,0,0,7.0,0,2,0,0.0
61,2,13,0,32.00,0,0,13.0,0,2,0,0.0
62,3,13,0,18.00,0,0,7.0,0,2,0,0.0
63,3,10,1,22.00,0,0,7.0,0,1,0,0.0
64,1,9,0,13.00,2,2,262.0,5,0,2,2.0
65,2,14,1,29.00,0,0,21.0,0,2,0,0.0
66,3,10,1,18.00,0,0,7.0,0,1,0,0.0
67,1,13,0,47.00,0,0,42.0,0,2,0,0.0
68,1,13,0,31.00,0,0,28.0,5,0,0,3.0
69,1,14,1,60.00,1,4,263.0,2,2,2,3.0
70,3,10,1,24.00,0,0,7.0,0,1,0,0.0
71,3,13,0,21.00,0,0,7.0,0,2,0,0.0
72,3,10,1,29.00,0,0,7.0,0,2,0,0.0
73,1,13,0,28.50,0,0,27.0,4,0,0,4.0
74,1,10,1,35.00,0,0,211.0,13,0,0,3.0
75,1,13,0,32.50,0,0,211.0,13,0,0,3.0
76,3,13,0,29.00,0,0,8.0,0,2,0,0.0
77,1,14,1,55.00,2,0,25.0,10,2,1,3.0
78,2,13,0,30.00,0,0,13.0,0,2,0,0.0
79,3,10,1,24.00,0,0,7.0,0,1,0,0.0
80,3,9,0,6.00,1,1,15.0,0,0,1,0.0
81,1,13,0,67.00,1,0,221.0,5,2,1,3.0
82,1,13,0,49.00,0,0,26.0,0,2,0,0.0
83,3,13,0,29.00,0,0,7.0,0,2,0,0.0
84,2,13,0,29.00,0,0,10.0,0,1,0,0.0
85,3,13,0,29.00,1,0,14.0,0,0,1,0.0
86,3,10,1,27.00,0,0,7.0,0,1,0,0.0
87,3,10,1,18.00,0,0,8.0,0,2,0,0.0
88,3,15,1,29.00,0,0,7.0,0,1,0,0.0
89,2,9,0,2.00,1,1,23.0,0,2,1,0.0
90,3,14,1,22.00,1,0,13.0,0,2,1,0.0
91,3,13,0,29.00,0,0,7.0,0,2,0,0.0
92,1,14,1,27.00,1,2,52.0,7,2,1,2.0
93,3,13,0,29.00,0,0,8.0,0,2,0,0.0
94,1,13,0,25.00,0,0,26.0,0,0,0,0.0
95,3,13,0,25.00,0,0,7.0,0,2,0,0.0
96,1,14,1,76.00,1,0,78.0,4,2,1,3.0
97,3,13,0,29.00,0,0,7.0,0,2,0,0.0
98,3,10,1,20.00,0,0,7.0,0,2,0,0.0
99,3,13,0,33.00,0,0,8.0,0,2,0,0.0
100,1,14,1,43.00,1,0,55.0,11,0,1,3.0
101,2,13,0,27.00,1,0,26.0,0,2,1,0.0
102,3,13,0,29.00,0,0,7.0,0,1,0,0.0
103,3,13,0,26.00,0,0,7.0,0,2,0,0.0
104,3,14,1,16.00,1,1,8.0,0,0,1,0.0
105,3,13,0,28.00,0,0,22.0,0,2,0,0.0
106,3,13,0,21.00,0,0,7.0,0,1,0,0.0
107,3,13,0,29.00,0,0,7.0,0,1,0,0.0
108,3,13,0,29.00,0,0,8.0,0,2,0,0.0
109,2,13,0,18.50,0,0,13.0,9,2,0,9.0
110,2,13,0,41.00,0,0,15.0,0,0,0,0.0
111,3,10,1,29.00,0,0,7.0,0,1,0,0.0
112,1,10,1,36.00,0,0,31.0,2,0,0,1.0
113,3,10,1,18.50,0,0,7.0,0,1,0,0.0
114,1,14,1,63.00,1,0,221.0,5,2,1,3.0
115,3,13,0,18.00,1,0,14.0,0,0,1,0.0
116,3,13,0,29.00,0,0,6.0,0,0,0,0.0
117,3,10,1,1.00,1,1,16.0,0,2,1,7.0
118,1,13,0,36.00,0,0,75.0,0,0,0,3.0
119,2,14,1,29.00,1,0,26.0,0,2,1,0.0
120,2,10,1,12.00,0,0,15.0,0,2,0,0.0
121,3,13,0,29.00,1,0,7.0,0,1,1,0.0
122,1,14,1,35.00,1,0,57.0,2,0,1,3.0
123,3,13,0,28.00,0,0,7.0,0,2,0,0.0
124,3,13,0,29.00,0,0,7.0,0,1,0,0.0
125,3,10,1,17.00,0,1,16.0,0,2,1,0.0
126,3,13,0,22.00,0,0,7.0,0,2,0,0.0
127,3,10,1,29.00,2,0,23.0,0,1,1,0.0
128,2,13,0,42.00,0,0,13.0,0,2,0,0.0
129,3,13,0,24.00,0,0,8.0,0,2,0,0.0
130,3,13,0,32.00,0,0,8.0,0,2,0,0.0
131,1,1,0,53.00,0,0,28.0,5,0,0,3.0
132,3,14,1,29.00,0,4,25.0,0,2,2,0.0
133,3,13,0,29.00,1,0,6.0,0,0,1,0.0
134,3,13,0,43.00,0,0,7.0,0,2,0,0.0
135,3,13,0,24.00,0,0,7.0,0,2,0,0.0
136,3,13,0,26.50,0,0,7.0,0,0,0,0.0
137,2,13,0,26.00,0,0,13.0,0,2,0,0.0
138,3,10,1,23.00,0,0,8.0,0,2,0,0.0
139,3,13,0,40.00,1,6,46.0,0,2,3,0.0
140,3,10,1,10.00,5,2,46.0,0,2,3,0.0
141,1,10,1,33.00,0,0,151.0,0,2,0,0.0
142,1,13,0,61.00,1,3,262.0,5,0,2,2.0
143,2,13,0,28.00,0,0,26.0,0,2,0,0.0
144,1,13,0,42.00,0,0,26.0,0,2,0,0.0
145,3,13,0,31.00,3,0,18.0,0,2,1,0.0
146,1,13,0,39.00,0,0,51.0,4,2,0,5.0
147,3,13,0,22.00,0,0,8.0,0,2,0,0.0
148,1,13,0,39.00,0,0,26.0,0,2,0,0.0
149,2,16,0,30.00,1,1,26.0,0,2,1,0.0
150,1,14,1,23.00,0,1,83.0,5,0,1,3.0
151,3,13,0,29.00,0,0,7.0,0,0,0,0.0
152,3,13,0,60.50,0,0,10.0,0,2,0,0.0
153,3,14,1,36.00,0,2,12.0,0,2,1,0.0
154,3,9,0,13.00,4,2,31.0,0,2,2,0.0
155,3,13,0,24.00,0,0,7.0,0,2,0,0.0
156,1,10,1,29.00,0,0,221.0,9,2,0,3.0
157,3,10,1,23.00,0,0,7.0,0,2,0,0.0
158,1,13,0,42.00,0,0,26.0,2,2,0,4.0
159,3,14,1,26.00,0,2,13.0,0,2,1,0.0
160,3,10,1,29.00,0,0,7.0,0,1,0,0.0
161,3,9,0,7.00,1,1,15.0,0,0,1,0.0
162,2,10,1,26.00,0,0,13.0,0,2,0,0.0
163,3,13,0,29.00,0,0,7.0,0,2,0,0.0
164,2,16,0,41.00,0,0,13.0,0,2,0,0.0
165,3,14,1,26.00,1,1,22.0,0,2,1,0.0
166,1,13,0,48.00,0,0,50.0,1,0,0,2.0
167,3,13,0,18.00,2,2,34.0,0,2,2,0.0
168,1,14,1,39.00,0,0,27.0,0,0,0,0.0
169,3,10,1,22.00,0,0,8.0,0,2,0,0.0
170,3,13,0,29.00,0,0,7.0,0,2,0,0.0
171,3,13,0,27.00,0,0,7.0,0,0,0,0.0
172,3,13,0,23.00,1,0,13.0,0,2,1,0.0
173,3,13,0,29.00,0,0,7.0,0,0,0,0.0
174,3,13,0,40.00,1,5,31.0,0,2,2,0.0
175,2,10,1,15.00,0,2,39.0,0,2,1,0.0
176,2,10,1,20.00,0,0,36.0,0,2,0,0.0
177,1,13,0,54.00,1,0,55.0,11,0,1,3.0
178,2,14,1,36.00,0,3,39.0,0,2,1,6.0
179,1,14,1,64.00,0,2,83.0,4,0,1,5.0
180,2,13,0,30.00,0,0,13.0,0,2,0,0.0
181,1,13,0,37.00,1,1,83.0,5,0,1,5.0
182,1,14,1,18.00,1,0,53.0,3,2,1,4.0
183,3,13,0,29.00,0,0,7.0,0,1,0,0.0
184,1,14,1,27.00,1,1,247.0,5,0,1,2.0
185,2,13,0,40.00,0,0,16.0,0,2,0,0.0
186,2,10,1,21.00,0,1,21.0,0,2,1,0.0
187,3,13,0,17.00,2,0,8.0,0,2,1,0.0
188,3,10,1,29.00,8,2,69.0,0,2,3,0.0
189,2,13,0,40.00,0,0,13.0,0,2,0,0.0
190,2,13,0,34.00,1,0,26.0,0,2,1,0.0
191,1,13,0,39.00,0,0,26.0,0,2,0,0.0
192,3,9,0,11.50,1,1,14.0,0,2,1,0.0
193,2,13,0,61.00,0,0,12.0,0,1,0,0.0
194,2,9,0,8.00,0,2,32.0,0,2,1,0.0
195,3,13,0,33.00,0,0,7.0,0,2,0,0.0
196,1,9,0,6.00,0,2,134.0,3,0,1,5.0
197,3,10,1,18.00,0,0,7.0,0,2,0,0.0
198,2,13,0,23.00,0,0,10.0,0,2,0,0.0
199,3,14,1,29.00,0,0,8.0,0,2,0,0.0
200,3,10,1,29.00,0,0,15.0,0,1,0,0.0
201,3,9,0,0.33,0,2,14.0,0,2,1,0.0
202,1,1,0,47.00,1,0,227.0,6,0,1,3.0
203,2,10,1,8.00,1,1,26.0,0,2,1,0.0
204,2,13,0,25.00,0,0,10.0,0,2,0,0.0
205,1,13,0,39.00,0,0,25.0,0,0,0,0.0
206,3,10,1,35.00,0,0,7.0,0,1,0,0.0
207,2,13,0,24.00,0,0,10.0,0,2,0,0.0
208,1,10,1,33.00,0,0,27.0,1,0,0,1.0
209,3,13,0,25.00,0,0,7.0,0,2,0,0.0
210,3,13,0,32.00,0,0,22.0,0,2,0,0.0
211,3,13,0,29.00,0,0,7.0,0,2,0,0.0
212,2,13,0,17.00,0,0,73.0,0,2,0,0.0
213,2,14,1,60.00,1,0,26.0,0,2,1,0.0
214,3,10,1,38.00,4,2,7.0,0,2,2,0.0
215,1,13,0,42.00,0,0,42.0,1,2,0,2.0
216,3,10,1,29.00,0,0,7.0,0,1,0,0.0
217,1,13,0,57.00,1,1,164.0,0,2,1,0.0
218,1,14,1,50.00,1,1,211.0,8,0,1,3.0
219,3,13,0,29.00,0,0,8.0,0,2,0,0.0
220,2,10,1,30.00,1,0,13.0,0,0,1,0.0
221,3,13,0,21.00,0,0,8.0,0,2,0,0.0
222,2,14,1,22.00,0,0,10.0,3,2,0,6.0
223,3,13,0,21.00,0,0,7.0,0,2,0,0.0
224,1,14,1,53.00,0,0,27.0,0,0,0,0.0
225,3,14,1,29.00,0,2,15.0,0,0,1,0.0
226,3,13,0,23.00,0,0,7.0,0,2,0,0.0
227,3,10,1,29.00,0,0,7.0,0,1,0,0.0
228,3,13,0,40.50,0,0,15.0,0,2,0,0.0
229,2,13,0,36.00,0,0,13.0,0,2,0,0.0
230,2,13,0,14.00,0,0,65.0,0,2,0,0.0
231,1,10,1,21.00,0,0,26.0,0,2,0,0.0
232,3,13,0,21.00,1,0,6.0,0,2,1,0.0
233,3,13,0,29.00,0,0,7.0,0,1,0,0.0
234,1,13,0,39.00,1,0,71.0,8,0,1,3.0
235,3,13,0,20.00,0,0,7.0,0,2,0,0.0
236,1,13,0,64.00,1,0,75.0,3,0,1,4.0
237,3,13,0,20.00,0,0,7.0,0,0,0,0.0
238,2,10,1,18.00,1,1,13.0,0,2,1,0.0
239,1,14,1,48.00,1,0,106.0,8,0,1,3.0
240,1,14,1,55.00,0,0,27.0,0,0,0,0.0
241,2,14,1,45.00,0,2,30.0,0,2,1,0.0
242,1,13,0,45.00,1,1,134.0,3,0,1,5.0
243,3,13,0,29.00,0,0,7.0,0,2,0,0.0
244,3,9,0,29.00,1,2,23.0,0,2,1,0.0
245,1,13,0,41.00,1,0,51.0,2,2,1,4.0
246,2,14,1,22.00,0,0,21.0,0,2,0,0.0
247,2,13,0,42.00,1,1,32.0,0,2,1,0.0
248,2,14,1,29.00,1,0,26.0,0,2,1,0.0
249,3,14,1,29.00,1,0,14.0,0,0,1,0.0
250,2,10,1,0.92,1,2,27.0,0,2,1,0.0
251,3,13,0,20.00,0,0,7.0,0,2,0,0.0
252,1,13,0,27.00,1,0,136.0,8,0,1,3.0
253,3,13,0,24.00,0,0,9.0,0,2,0,0.0
254,3,13,0,32.50,0,0,9.0,0,2,0,0.0
255,3,13,0,29.00,0,0,7.0,0,2,0,0.0
256,3,13,0,29.00,0,0,7.0,0,1,0,0.0
257,3,13,0,28.00,0,0,8.0,0,2,0,0.0
258,2,10,1,19.00,0,0,13.0,0,2,0,0.0
259,3,13,0,21.00,0,0,7.0,0,2,0,0.0
260,3,13,0,36.50,1,0,17.0,0,2,1,0.0
261,3,13,0,21.00,0,0,7.0,0,2,0,0.0
262,2,14,1,29.00,0,2,23.0,0,2,1,0.0
263,3,10,1,1.00,1,1,12.0,0,2,1,0.0
264,2,13,0,30.00,0,0,12.0,0,0,0,0.0
265,3,13,0,29.00,0,0,7.0,0,2,0,0.0
266,1,13,0,39.00,0,0,0.0,0,2,0,0.0
267,3,13,0,29.00,0,0,7.0,0,2,0,0.0
268,3,10,1,29.00,0,0,8.0,0,2,0,0.0
269,3,13,0,17.00,0,0,8.0,0,2,0,0.0
270,1,13,0,46.00,0,0,75.0,0,0,0,3.0
271,3,13,0,29.00,0,0,7.0,0,1,0,0.0
272,1,14,1,26.00,1,0,136.0,8,0,1,3.0
273,3,10,1,29.00,1,0,15.0,0,1,1,0.0
274,3,13,0,29.00,0,0,7.0,0,0,0,0.0
275,2,10,1,20.00,1,0,26.0,0,2,1,0.0
276,2,13,0,28.00,0,0,10.0,0,2,0,0.0
277,2,13,0,40.00,1,0,26.0,0,2,1,0.0
278,2,13,0,30.00,1,0,21.0,0,2,1,0.0
279,2,13,0,22.00,0,0,10.0,0,2,0,0.0
280,3,10,1,23.00,0,0,8.0,0,2,0,0.0
281,3,9,0,0.75,1,1,13.0,0,2,1,0.0
282,3,10,1,29.00,0,0,7.0,0,1,0,0.0
283,3,10,1,9.00,1,1,15.0,0,0,1,0.0
284,3,10,1,2.00,1,1,20.0,0,2,1,0.0
285,3,13,0,36.00,0,0,7.0,0,2,0,0.0
286,3,13,0,29.00,0,0,7.0,0,2,0,0.0
287,1,13,0,24.00,1,0,82.0,4,2,1,2.0
288,3,13,0,29.00,0,0,7.0,9,0,0,9.0
289,3,13,0,29.00,0,0,8.0,0,2,0,0.0
290,1,13,0,39.00,0,0,39.0,0,2,0,0.0
291,3,10,1,30.00,0,0,6.0,0,1,0,0.0
292,3,13,0,29.00,0,0,7.0,0,0,0,0.0
293,1,5,0,53.00,1,1,81.0,3,2,1,1.0
294,3,13,0,36.00,0,0,9.0,0,2,0,0.0
295,3,13,0,26.00,0,0,7.0,0,2,0,0.0
296,2,10,1,1.00,1,2,41.0,0,0,1,0.0
297,3,13,0,29.00,2,0,21.0,0,0,1,0.0
298,1,13,0,30.00,0,0,45.0,0,2,0,0.0
299,3,13,0,29.00,0,0,7.0,0,2,0,0.0
300,3,13,0,32.00,0,0,7.0,0,2,0,0.0
301,2,13,0,29.00,0,0,15.0,9,0,0,9.0
302,2,13,0,43.00,0,1,21.0,0,2,1,0.0
303,3,13,0,24.00,0,0,8.0,0,2,0,0.0
304,3,10,1,29.00,0,0,7.0,0,1,0,0.0
305,1,14,1,64.00,1,1,26.0,2,2,1,2.0
306,1,13,0,30.00,1,2,151.0,2,2,1,3.0
307,3,9,0,0.83,0,1,9.0,0,2,1,0.0
308,1,13,0,55.00,1,1,93.0,6,2,1,2.0
309,3,14,1,45.00,1,0,14.0,0,2,1,0.0
310,3,13,0,18.00,0,0,8.0,0,2,0,0.0
311,3,13,0,22.00,0,0,7.0,0,0,0,0.0
312,3,13,0,29.00,0,0,7.0,0,2,0,0.0
313,3,10,1,37.00,0,0,7.0,0,1,0,0.0
314,1,14,1,55.00,0,0,135.0,3,0,0,3.0
315,3,10,1,17.00,0,0,7.0,0,1,0,0.0
316,1,13,0,57.00,1,0,146.0,7,0,1,2.0
317,2,13,0,19.00,0,0,10.0,0,2,0,0.0
318,3,13,0,27.00,0,0,7.0,0,2,0,0.0
319,2,13,0,22.00,2,0,31.0,0,2,1,0.0
320,3,13,0,26.00,0,0,7.0,0,2,0,0.0
321,3,13,0,25.00,0,0,7.0,9,0,0,9.0
322,2,13,0,26.00,0,0,13.0,0,2,0,6.0
323,1,13,0,33.00,0,0,26.0,0,2,0,0.0
324,1,10,1,39.00,0,0,211.0,0,2,0,0.0
325,3,13,0,23.00,0,0,7.0,0,2,0,0.0
326,2,10,1,12.00,2,1,39.0,0,2,1,6.0
327,1,13,0,46.00,0,0,79.0,0,0,0,0.0
328,2,13,0,29.00,1,0,26.0,0,2,1,0.0
329,2,13,0,21.00,0,0,13.0,0,2,0,0.0
330,2,14,1,48.00,0,2,36.0,0,2,1,0.0
331,1,13,0,39.00,0,0,29.0,1,0,0,1.0
332,3,13,0,29.00,0,0,7.0,0,0,0,0.0
333,3,14,1,19.00,1,1,15.0,0,0,1,0.0
334,3,13,0,27.00,0,0,7.0,0,2,0,0.0
335,1,13,0,30.00,0,0,26.0,10,2,0,3.0
336,2,13,0,32.00,0,0,13.0,0,2,0,0.0
337,3,13,0,39.00,0,2,7.0,0,0,1,0.0
338,2,13,0,25.00,0,0,31.0,0,2,0,0.0
339,3,9,0,29.00,0,0,7.0,0,0,0,0.0
340,2,13,0,18.00,0,0,10.0,0,2,0,0.0
341,3,13,0,32.00,0,0,7.0,0,2,0,0.0
342,3,13,0,29.00,1,9,69.0,0,2,3,0.0
343,1,14,1,58.00,0,1,512.0,5,0,1,2.0
344,3,9,0,29.00,1,1,14.0,0,2,1,0.0
345,3,10,1,16.00,0,0,7.0,0,2,0,0.0
346,2,13,0,26.00,0,0,13.0,0,2,0,0.0
347,3,14,1,38.00,0,0,7.0,0,0,0,0.0
348,2,13,0,24.00,0,0,13.0,0,2,0,0.0
349,2,10,1,31.00,0,0,21.0,0,2,0,0.0
350,1,14,1,45.00,0,1,63.0,1,0,1,4.0
351,2,13,0,25.00,0,0,10.0,0,2,0,0.0
352,2,13,0,18.00,0,0,73.0,0,2,0,0.0
353,2,13,0,49.00,1,2,65.0,0,2,1,0.0
354,3,10,1,0.17,1,2,20.0,0,2,1,0.0
355,1,13,0,50.00,0,0,26.0,6,2,0,5.0
356,1,14,1,59.00,2,0,51.0,10,2,1,3.0
357,3,13,0,29.00,0,0,7.0,0,2,0,0.0
358,3,13,0,29.00,0,0,7.0,0,1,0,0.0
359,3,14,1,30.00,1,0,15.0,0,2,1,0.0
360,3,9,0,14.50,8,2,69.0,0,2,3,0.0
361,2,14,1,24.00,1,1,37.0,0,0,1,0.0
362,2,14,1,31.00,0,0,21.0,0,2,0,0.0
363,3,13,0,27.00,0,0,8.0,0,2,0,0.0
364,1,14,1,25.00,1,0,55.0,5,0,1,5.0
365,3,14,1,29.00,1,9,69.0,0,2,3,0.0
366,3,13,0,29.00,1,0,14.0,0,0,1,0.0
367,3,10,1,22.00,0,0,39.0,0,2,0,0.0
368,1,14,1,45.00,0,1,59.0,0,0,1,0.0
369,2,13,0,29.00,0,0,13.0,0,0,0,0.0
370,2,13,0,21.00,1,0,11.0,0,2,1,0.0
371,1,10,1,31.00,0,0,134.0,3,0,0,5.0
372,1,13,0,49.00,0,0,0.0,5,2,0,2.0
373,2,13,0,44.00,0,0,13.0,0,2,0,0.0
374,1,14,1,54.00,1,1,81.0,3,2,1,1.0
375,1,10,1,45.00,0,0,262.0,0,0,0,0.0
376,3,10,1,22.00,2,0,8.0,0,2,1,0.0
377,2,13,0,21.00,0,0,11.0,0,2,0,0.0
378,1,13,0,55.00,0,0,50.0,3,2,0,3.0
379,3,9,0,5.00,4,2,31.0,0,2,2,0.0
380,3,13,0,29.00,0,0,7.0,0,1,0,0.0
381,3,13,0,26.00,0,0,7.0,0,1,0,0.0
382,3,14,1,29.00,0,0,14.0,0,2,0,0.0
383,3,14,1,19.00,1,0,16.0,0,2,1,0.0
384,2,13,0,29.00,0,0,12.0,0,2,0,0.0
385,2,10,1,24.00,1,2,65.0,0,2,1,0.0
386,3,13,0,24.00,0,0,7.0,0,2,0,0.0
387,2,13,0,57.00,0,0,13.0,0,2,0,0.0
388,3,13,0,21.00,0,0,7.0,0,1,0,0.0
389,3,9,0,6.00,3,1,21.0,0,2,2,0.0
390,1,13,0,23.00,0,0,93.0,2,2,0,2.0
391,1,14,1,51.00,0,1,39.0,2,2,1,4.0
392,3,9,0,13.00,0,2,20.0,0,2,1,0.0
393,2,13,0,47.00,0,0,10.0,0,2,0,0.0
394,3,13,0,29.00,3,1,22.0,0,2,2,0.0
395,1,14,1,18.00,1,0,60.0,3,2,1,3.0
396,3,13,0,24.00,0,0,7.0,0,1,0,0.0
397,1,14,1,48.00,1,1,79.0,4,0,1,2.0
398,3,13,0,22.00,0,0,7.0,0,2,0,0.0
399,3,13,0,31.00,0,0,7.0,0,1,0,0.0
400,1,10,1,30.00,0,0,164.0,0,2,0,3.0
401,2,13,0,38.00,1,0,21.0,0,2,1,0.0
402,1,10,1,22.00,0,1,59.0,0,0,1,0.0
403,1,13,0,17.00,0,0,47.0,0,2,0,0.0
404,1,13,0,43.00,1,0,27.0,4,0,1,4.0
405,2,13,0,20.00,0,0,13.0,3,0,0,4.0
406,2,13,0,23.00,1,0,10.0,0,2,1,0.0
407,1,13,0,50.00,1,1,211.0,8,0,1,3.0
408,3,10,1,29.00,0,0,7.0,0,1,0,0.0
409,3,10,1,3.00,1,1,13.0,0,2,1,0.0
410,3,10,1,29.00,0,0,7.0,0,1,0,0.0
411,1,14,1,37.00,1,0,90.0,7,1,1,3.0
412,3,10,1,28.00,0,0,7.0,0,2,0,0.0
413,3,13,0,29.00,0,0,8.0,0,2,0,0.0
414,1,4,1,39.00,0,0,108.0,10,0,0,3.0
415,3,13,0,38.50,0,0,7.0,0,2,0,0.0
416,3,13,0,29.00,0,0,8.0,0,2,0,0.0
417,3,9,0,29.00,1,1,22.0,0,0,1,0.0

In [48]:
write= pd.read_csv("test.csv")
write

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.00,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.00,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.00,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.00,2,0,A/4 48871,24.1500,NaN,S
10,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
11,903,1,"Jones, Mr. Charles Cresson",male,46.00,0,0,694,26.0000,NaN,S
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00,1,0,21228,82.2667,B45,S
13,905,2,"Howard, Mr. Benjamin",male,63.00,1,0,24065,26.0000,NaN,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.00,1,0,W.E.P. 5734,61.1750,E31,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00,1,0,SC/PARIS 2167,27.7208,NaN,C
16,908,2,"Keane, Mr. Daniel",male,35.00,0,0,233734,12.3500,NaN,Q
17,909,3,"Assaf, Mr. Gerios",male,21.00,0,0,2692,7.2250,NaN,C
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.00,1,0,STON/O2. 3101270,7.9250,NaN,S
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00,0,0,2696,7.2250,NaN,C
20,912,1,"Rothschild, Mr. Martin",male,55.00,1,0,PC 17603,59.4000,NaN,C
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S
23,915,1,"Williams, Mr. Richard Norris II",male,21.00,0,1,PC 17597,61.3792,NaN,C
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
25,917,3,"Robins, Mr. Alexander A",male,50.00,1,0,A/5. 3337,14.5000,NaN,S
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.00,0,1,113509,61.9792,B36,C
27,919,3,"Daher, Mr. Shedid",male,22.50,0,0,2698,7.2250,NaN,C
28,920,1,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.5000,A21,S
29,921,3,"Samaan, Mr. Elias",male,NaN,2,0,2662,21.6792,NaN,C
30,922,2,"Louch, Mr. Charles Alexander",male,50.00,1,0,SC/AH 3085,26.0000,NaN,S
31,923,2,"Jefferys, Mr. Clifford Thomas",male,24.00,2,0,C.A. 31029,31.5000,NaN,S
32,924,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.00,1,2,C.A. 2315,20.5750,NaN,S
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
34,926,1,"Mock, Mr. Philipp Edmund",male,30.00,1,0,13236,57.7500,C78,C
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.50,0,0,2682,7.2292,NaN,C
36,928,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S
37,929,3,"Cacic, Miss. Manda",female,21.00,0,0,315087,8.6625,NaN,S
38,930,3,"Sap, Mr. Julius",male,25.00,0,0,345768,9.5000,NaN,S
39,931,3,"Hee, Mr. Ling",male,NaN,0,0,1601,56.4958,NaN,S
40,932,3,"Karun, Mr. Franz",male,39.00,0,1,349256,13.4167,NaN,C
41,933,1,"Franklin, Mr. Thomas Parham",male,NaN,0,0,113778,26.5500,D34,S
42,934,3,"Goldsmith, Mr. Nathan",male,41.00,0,0,SOTON/O.Q. 3101263,7.8500,NaN,S
43,935,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30.00,0,0,237249,13.0000,NaN,S
44,936,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.00,1,0,11753,52.5542,D19,S
45,937,3,"Peltomaki, Mr. Nikolai Johannes",male,25.00,0,0,STON/O 2. 3101291,7.9250,NaN,S
46,938,1,"Chevre, Mr. Paul Romaine",male,45.00,0,0,PC 17594,29.7000,A9,C
47,939,3,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q
48,940,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.2917,D15,C
49,941,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36.00,0,2,C.A. 37671,15.9000,NaN,S
50,942,1,"Smith, Mr. Lucien Philip",male,24.00,1,0,13695,60.0000,C31,S
51,943,2,"Pulbaum, Mr. Franz",male,27.00,0,0,SC/PARIS 2168,15.0333,NaN,C
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.00,2,1,29105,23.0000,NaN,S
53,945,1,"Fortune, Miss. Ethel Flora",female,28.00,3,2,19950,263.0000,C23 C25 C27,S
54,946,2,"Mangiavacchi, Mr. Serafino Emilio",male,NaN,0,0,SC/A.3 2861,15.5792,NaN,C
55,947,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.1250,NaN,Q
56,948,3,"Cor, Mr. Bartol",male,35.00,0,0,349230,7.8958,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.6500,F G63,S
58,950,3,"Davison, Mr. Thomas Henry",male,NaN,1,0,386525,16.1000,NaN,S
59,951,1,"Chaudanson, Miss. Victorine",female,36.00,0,0,PC 17608,262.3750,B61,C
60,952,3,"Dika, Mr. Mirko",male,17.00,0,0,349232,7.8958,NaN,S
61,953,2,"McCrae, Mr. Arthur Gordon",male,32.00,0,0,237216,13.5000,NaN,S
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.7500,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.00,0,0,334914,7.7250,NaN,Q
64,956,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
65,957,2,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Mi...",female,NaN,0,0,F.C.C. 13534,21.0000,NaN,S
66,958,3,"Burns, Miss. Mary Delia",female,18.00,0,0,330963,7.8792,NaN,Q
67,959,1,"Moore, Mr. Clarence Bloomfield",male,47.00,0,0,113796,42.4000,NaN,S
68,960,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00,0,0,2543,28.5375,C53,C
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.0000,C23 C25 C27,S
70,962,3,"Mulvihill, Miss. Bertha E",female,24.00,0,0,382653,7.7500,NaN,Q
71,963,3,"Minkoff, Mr. Lazar",male,21.00,0,0,349211,7.8958,NaN,S
72,964,3,"Nieminen, Miss. Manta Josefina",female,29.00,0,0,3101297,7.9250,NaN,S
73,965,1,"Ovies y Rodriguez, Mr. Servando",male,28.50,0,0,PC 17562,27.7208,D43,C
74,966,1,"Geiger, Miss. Amalie",female,35.00,0,0,113503,211.5000,C130,C
75,967,1,"Keeping, Mr. Edwin",male,32.50,0,0,113503,211.5000,C132,C
76,968,3,"Miles, Mr. Frank",male,NaN,0,0,359306,8.0500,NaN,S
77,969,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.00,2,0,11770,25.7000,C101,S
78,970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.0000,NaN,S
79,971,3,"Doyle, Miss. Elizabeth",female,24.00,0,0,368702,7.7500,NaN,Q
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C
81,973,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.7792,C55 C57,S
82,974,1,"Case, Mr. Howard Brown",male,49.00,0,0,19924,26.0000,NaN,S
83,975,3,"Demetri, Mr. Marinko",male,NaN,0,0,349238,7.8958,NaN,S
84,976,2,"Lamb, Mr. John Joseph",male,NaN,0,0,240261,10.7083,NaN,Q
85,977,3,"Khalil, Mr. Betros",male,NaN,1,0,2660,14.4542,NaN,C
86,978,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.8792,NaN,Q
87,979,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.0500,NaN,S
88,980,3,"O'Donoghue, Ms. Bridget",female,NaN,0,0,364856,7.7500,NaN,Q
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S
90,982,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.00,1,0,347072,13.9000,NaN,S
91,983,3,"Pedersen, Mr. Olaf",male,NaN,0,0,345498,7.7750,NaN,S
92,984,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27.00,1,2,F.C. 12750,52.0000,B71,S
93,985,3,"Guest, Mr. Robert",male,NaN,0,0,376563,8.0500,NaN,S
94,986,1,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.0000,NaN,C
95,987,3,"Tenglin, Mr. Gunnar Isidor",male,25.00,0,0,350033,7.7958,NaN,S
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.8500,C46,S
97,989,3,"Makinen, Mr. Kalle Edvard",male,29.00,0,0,STON/O 2. 3101268,7.9250,NaN,S
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.00,0,0,347471,7.8542,NaN,S
99,991,3,"Nancarrow, Mr. William Henry",male,33.00,0,0,A./5. 3338,8.0500,NaN,S
100,992,1,"Stengel, Mrs. Charles Emil Henry (Annie May Mo...",female,43.00,1,0,11778,55.4417,C116,C
101,993,2,"Weisz, Mr. Leopold",male,27.00,1,0,228414,26.0000,NaN,S
102,994,3,"Foley, Mr. William",male,NaN,0,0,365235,7.7500,NaN,Q
103,995,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.00,0,0,347070,7.7750,NaN,S
104,996,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.5167,NaN,C
105,997,3,"Holthen, Mr. Johan Martin",male,28.00,0,0,C 4001,22.5250,NaN,S
106,998,3,"Buckley, Mr. Daniel",male,21.00,0,0,330920,7.8208,NaN,Q
107,999,3,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.7500,NaN,Q
108,1000,3,"Willer, Mr. Aaron (Abi Weller"")""",male,NaN,0,0,3410,8.7125,NaN,S
109,1001,2,"Swane, Mr. George",male,18.50,0,0,248734,13.0000,F,S
110,1002,2,"Stanton, Mr. Samuel Ward",male,41.00,0,0,237734,15.0458,NaN,C
111,1003,3,"Shine, Miss. Ellen Natalia",female,NaN,0,0,330968,7.7792,NaN,Q
112,1004,1,"Evans, Miss. Edith Corse",female,36.00,0,0,PC 17531,31.6792,A29,C
113,1005,3,"Buckley, Miss. Katherine",female,18.50,0,0,329944,7.2833,NaN,Q
114,1006,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.7792,C55 C57,S
115,1007,3,"Chronopoulos, Mr. Demetrios",male,18.00,1,0,2680,14.4542,NaN,C
116,1008,3,"Thomas, Mr. John",male,NaN,0,0,2681,6.4375,NaN,C
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S
118,1010,1,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.2417,C6,C
119,1011,2,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)",female,29.00,1,0,SC/AH 29037,26.0000,NaN,S
120,1012,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.7500,NaN,S
121,1013,3,"Kiernan, Mr. John",male,NaN,1,0,367227,7.7500,NaN,Q
122,1014,1,"Schabert, Mrs. Paul (Emma Mock)",female,35.00,1,0,13236,57.7500,C28,C
123,1015,3,"Carver, Mr. Alfred John",male,28.00,0,0,392095,7.2500,NaN,S
124,1016,3,"Kennedy, Mr. John",male,NaN,0,0,368783,7.7500,NaN,Q
125,1017,3,"Cribb, Miss. Laura Alice",female,17.00,0,1,371362,16.1000,NaN,S
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.7958,NaN,S
127,1019,3,"McCoy, Miss. Alicia",female,NaN,2,0,367226,23.2500,NaN,Q
128,1020,2,"Bowenur, Mr. Solomon",male,42.00,0,0,211535,13.0000,NaN,S
129,1021,3,"Petersen, Mr. Marius",male,24.00,0,0,342441,8.0500,NaN,S
130,1022,3,"Spinner, Mr. Henry John",male,32.00,0,0,STON/OQ. 369943,8.0500,NaN,S
131,1023,1,"Gracie, Col. Archibald IV",male,53.00,0,0,113780,28.5000,C51,C
132,1024,3,"Lefebre, Mrs. Frank (Frances)",female,NaN,0,4,4133,25.4667,NaN,S
133,1025,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C
134,1026,3,"Dintcheff, Mr. Valtcho",male,43.00,0,0,349226,7.8958,NaN,S
135,1027,3,"Carlsson, Mr. Carl Robert",male,24.00,0,0,350409,7.8542,NaN,S
136,1028,3,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C
137,1029,2,"Schmidt, Mr. August",male,26.00,0,0,248659,13.0000,NaN,S
138,1030,3,"Drapkin, Miss. Jennie",female,23.00,0,0,SOTON/OQ 392083,8.0500,NaN,S
139,1031,3,"Goodwin, Mr. Charles Frederick",male,40.00,1,6,CA 2144,46.9000,NaN,S
140,1032,3,"Goodwin, Miss. Jessie Allis",female,10.00,5,2,CA 2144,46.9000,NaN,S
141,1033,1,"Daniels, Miss. Sarah",female,33.00,0,0,113781,151.5500,NaN,S
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
143,1035,2,"Beauchamp, Mr. Henry James",male,28.00,0,0,244358,26.0000,NaN,S
144,1036,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lin...",male,42.00,0,0,17475,26.5500,NaN,S
145,1037,3,"Vander Planke, Mr. Julius",male,31.00,3,0,345763,18.0000,NaN,S
146,1038,1,"Hilliard, Mr. Herbert Henry",male,NaN,0,0,17463,51.8625,E46,S
147,1039,3,"Davies, Mr. Evan",male,22.00,0,0,SC/A4 23568,8.0500,NaN,S
148,1040,1,"Crafton, Mr. John Bertram",male,NaN,0,0,113791,26.5500,NaN,S
149,1041,2,"Lahtinen, Rev. William",male,30.00,1,1,250651,26.0000,NaN,S
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00,0,1,11767,83.1583,C54,C
151,1043,3,"Matinoff, Mr. Nicola",male,NaN,0,0,349255,7.8958,NaN,C
152,1044,3,"Storey, Mr. Thomas",male,60.50,0,0,3701,NaN,NaN,S
153,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00,0,2,350405,12.1833,NaN,S
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.3875,NaN,S
155,1047,3,"Duquemin, Mr. Joseph",male,24.00,0,0,S.O./P.P. 752,7.5500,NaN,S
156,1048,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.7792,C97,S
157,1049,3,"Lundin, Miss. Olga Elida",female,23.00,0,0,347469,7.8542,NaN,S
158,1050,1,"Borebank, Mr. John James",male,42.00,0,0,110489,26.5500,D22,S
159,1051,3,"Peacock, Mrs. Benjamin (Edith Nile)",female,26.00,0,2,SOTON/O.Q. 3101315,13.7750,NaN,S
160,1052,3,"Smyth, Miss. Julia",female,NaN,0,0,335432,7.7333,NaN,Q
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C
162,1054,2,"Wright, Miss. Marion",female,26.00,0,0,220844,13.5000,NaN,S
163,1055,3,"Pearce, Mr. Ernest",male,NaN,0,0,343271,7.0000,NaN,S
164,1056,2,"Peruschitz, Rev. Joseph Maria",male,41.00,0,0,237393,13.0000,NaN,S
165,1057,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.00,1,1,315153,22.0250,NaN,S
166,1058,1,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.4958,B10,C
167,1059,3,"Ford, Mr. Edward Watson",male,18.00,2,2,W./C. 6608,34.3750,NaN,S
168,1060,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C
169,1061,3,"Hellstrom, Miss. Hilda Maria",female,22.00,0,0,7548,8.9625,NaN,S
170,1062,3,"Lithman, Mr. Simon",male,NaN,0,0,S.O./P.P. 251,7.5500,NaN,S
171,1063,3,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C
172,1064,3,"Dyker, Mr. Adolf Fredrik",male,23.00,1,0,347072,13.9000,NaN,S
173,1065,3,"Torfa, Mr. Assad",male,NaN,0,0,2673,7.2292,NaN,C
174,1066,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40.00,1,5,347077,31.3875,NaN,S
175,1067,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.0000,NaN,S
176,1068,2,"Sincock, Miss. Maude",female,20.00,0,0,C.A. 33112,36.7500,NaN,S
177,1069,1,"Stengel, Mr. Charles Emil Henry",male,54.00,1,0,11778,55.4417,C116,C
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.00,0,3,230136,39.0000,F4,S
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00,0,2,PC 17756,83.1583,E45,C
180,1072,2,"McCrie, Mr. James Matthew",male,30.00,0,0,233478,13.0000,NaN,S
181,1073,1,"Compton, Mr. Alexander Taylor Jr",male,37.00,1,1,PC 17756,83.1583,E52,C
182,1074,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmic...",female,18.00,1,0,113773,53.1000,D30,S
183,1075,3,"Lane, Mr. Patrick",male,NaN,0,0,7935,7.7500,NaN,Q
184,1076,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00,1,1,PC 17558,247.5208,B58 B60,C
185,1077,2,"Maybery, Mr. Frank Hubert",male,40.00,0,0,239059,16.0000,NaN,S
186,1078,2,"Phillips, Miss. Alice Frances Louisa",female,21.00,0,1,S.O./P.P. 2,21.0000,NaN,S
187,1079,3,"Davies, Mr. Joseph",male,17.00,2,0,A/4 48873,8.0500,NaN,S
188,1080,3,"Sage, Miss. Ada",female,NaN,8,2,CA. 2343,69.5500,NaN,S
189,1081,2,"Veal, Mr. James",male,40.00,0,0,28221,13.0000,NaN,S
190,1082,2,"Angle, Mr. William A",male,34.00,1,0,226875,26.0000,NaN,S
191,1083,1,"Salomon, Mr. Abraham L",male,NaN,0,0,111163,26.0000,NaN,S
192,1084,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,NaN,S
193,1085,2,"Lingane, Mr. John",male,61.00,0,0,235509,12.3500,NaN,Q
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S
195,1087,3,"Karlsson, Mr. Julius Konrad Eugen",male,33.00,0,0,347465,7.8542,NaN,S
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C
197,1089,3,"Nilsson, Miss. Berta Olivia",female,18.00,0,0,347066,7.7750,NaN,S
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.00,0,0,C.A. 31030,10.5000,NaN,S
199,1091,3,"Rasmussen, Mrs. (Lena Jacobsen Solvang)",female,NaN,0,0,65305,8.1125,NaN,S
200,1092,3,"Murphy, Miss. Nora",female,NaN,0,0,36568,15.5000,NaN,Q
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
202,1094,1,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.5250,C62 C64,C
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.0000,NaN,S
204,1096,2,"Andrew, Mr. Frank Thomas",male,25.00,0,0,C.A. 34050,10.5000,NaN,S
205,1097,1,"Omont, Mr. Alfred Fernand",male,NaN,0,0,F.C. 12998,25.7417,NaN,C
206,1098,3,"McGowan, Miss. Katherine",female,35.00,0,0,9232,7.7500,NaN,Q
207,1099,2,"Collett, Mr. Sidney C Stuart",male,24.00,0,0,28034,10.5000,NaN,S
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.00,0,0,PC 17613,27.7208,A11,C
209,1101,3,"Delalic, Mr. Redjo",male,25.00,0,0,349250,7.8958,NaN,S
210,1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.5250,NaN,S
211,1103,3,"Finoli, Mr. Luigi",male,NaN,0,0,SOTON/O.Q. 3101308,7.0500,NaN,S
212,1104,2,"Deacon, Mr. Percy William",male,17.00,0,0,S.O.C. 14879,73.5000,NaN,S
213,1105,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.00,1,0,24065,26.0000,NaN,S
214,1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.7750,NaN,S
215,1107,1,"Head, Mr. Christopher",male,42.00,0,0,113038,42.5000,B11,S
216,1108,3,"Mahon, Miss. Bridget Delia",female,NaN,0,0,330924,7.8792,NaN,Q
217,1109,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.8667,NaN,S
218,1110,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.5000,C80,C
219,1111,3,"Thomson, Mr. Alexander Morrison",male,NaN,0,0,32302,8.0500,NaN,S
220,1112,2,"Duran y More, Miss. Florentina",female,30.00,1,0,SC/PARIS 2148,13.8583,NaN,C
221,1113,3,"Reynolds, Mr. Harold J",male,21.00,0,0,342684,8.0500,NaN,S
222,1114,2,"Cook, Mrs. (Selena Rogers)",female,22.00,0,0,W./C. 14266,10.5000,F33,S
223,1115,3,"Karlsson, Mr. Einar Gervasius",male,21.00,0,0,350053,7.7958,NaN,S
224,1116,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.00,0,0,PC 17606,27.4458,NaN,C
225,1117,3,"Moubarek, Mrs. George (Omine Amenia"" Alexander)""",female,NaN,0,2,2661,15.2458,NaN,C
226,1118,3,"Asplund, Mr. Johan Charles",male,23.00,0,0,350054,7.7958,NaN,S
227,1119,3,"McNeill, Miss. Bridget",female,NaN,0,0,370368,7.7500,NaN,Q
228,1120,3,"Everett, Mr. Thomas James",male,40.50,0,0,C.A. 6212,15.1000,NaN,S
229,1121,2,"Hocking, Mr. Samuel James Metcalfe",male,36.00,0,0,242963,13.0000,NaN,S
230,1122,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.0000,NaN,S
231,1123,1,"Willard, Miss. Constance",female,21.00,0,0,113795,26.5500,NaN,S
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.00,1,0,3101266,6.4958,NaN,S
233,1125,3,"Linehan, Mr. Michael",male,NaN,0,0,330971,7.8792,NaN,Q
234,1126,1,"Cumings, Mr. John Bradley",male,39.00,1,0,PC 17599,71.2833,C85,C
235,1127,3,"Vendel, Mr. Olof Edvin",male,20.00,0,0,350416,7.8542,NaN,S
236,1128,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.2500,D37,C
237,1129,3,"Baccos, Mr. Raffull",male,20.00,0,0,2679,7.2250,NaN,C
238,1130,2,"Hiltunen, Miss. Marta",female,18.00,1,1,250650,13.0000,NaN,S
239,1131,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00,1,0,PC 17761,106.4250,C86,C
240,1132,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55.00,0,0,112377,27.7208,NaN,C
241,1133,2,"Christy, Mrs. (Alice Frances)",female,45.00,0,2,237789,30.0000,NaN,S
242,1134,1,"Spedden, Mr. Frederic Oakley",male,45.00,1,1,16966,134.5000,E34,C
243,1135,3,"Hyman, Mr. Abraham",male,NaN,0,0,3470,7.8875,NaN,S
244,1136,3,"Johnston, Master. William Arthur Willie""""",male,NaN,1,2,W./C. 6607,23.4500,NaN,S
245,1137,1,"Kenyon, Mr. Frederick R",male,41.00,1,0,17464,51.8625,D21,S
246,1138,2,"Karnes, Mrs. J Frank (Claire Bennett)",female,22.00,0,0,F.C.C. 13534,21.0000,NaN,S
247,1139,2,"Drew, Mr. James Vivian",male,42.00,1,1,28220,32.5000,NaN,S
248,1140,2,"Hold, Mrs. Stephen (Annie Margaret Hill)",female,29.00,1,0,26707,26.0000,NaN,S
249,1141,3,"Khalil, Mrs. Betros (Zahie Maria"" Elias)""",female,NaN,1,0,2660,14.4542,NaN,C
250,1142,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
251,1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.00,0,0,SOTON/O2 3101284,7.9250,NaN,S
252,1144,1,"Clark, Mr. Walter Miller",male,27.00,1,0,13508,136.7792,C89,C
253,1145,3,"Salander, Mr. Karl Johan",male,24.00,0,0,7266,9.3250,NaN,S
254,1146,3,"Wenzel, Mr. Linhart",male,32.50,0,0,345775,9.5000,NaN,S
255,1147,3,"MacKay, Mr. George William",male,NaN,0,0,C.A. 42795,7.5500,NaN,S

In [49]:
result=pd.DataFrame({"PassengerId":write['PassengerId'],"Survived":pred})
result

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         1
20           912         0
21           913         1
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         1
29           921         0
30           922         0
31           923         0
32           924         1
33           925         0
34           926         0
35           927         0
36           928         0
37           929         0
38           930         0
39           931         1
40           932         0
41           933         1
42           934         0
43           935         1
44           936         1
45           937         0
46           938         0
47           939         0
48           940         1
49           941         1
50           942         0
51           943         0
52           944         1
53           945         1
54           946         0
55           947         0
56           948         0
57           949         0
58           950         0
59           951         1
60           952         0
61           953         0
62           954         0
63           955         1
64           956         1
65           957         1
66           958         1
67           959         0
68           960         1
69           961         1
70           962         1
71           963         0
72           964         1
73           965         1
74           966         1
75           967         0
76           968         0
77           969         1
78           970         0
79           971         1
80           972         1
81           973         0
82           974         0
83           975         0
84           976         0
85           977         0
86           978         1
87           979         0
88           980         1
89           981         1
90           982         1
91           983         0
92           984         1
93           985         0
94           986         0
95           987         0
96           988         1
97           989         0
98           990         1
99           991         0
100          992         1
101          993         0
102          994         0
103          995         0
104          996         0
105          997         0
106          998         0
107          999         0
108         1000         0
109         1001         0
110         1002         0
111         1003         1
112         1004         1
113         1005         1
114         1006         1
115         1007         0
116         1008         0
117         1009         1
118         1010         0
119         1011         1
120         1012         1
121         1013         0
122         1014         1
123         1015         0
124         1016         0
125         1017         1
126         1018         0
127         1019         1
128         1020         0
129         1021         0
130         1022         0
131         1023         1
132         1024         0
133         1025         0
134         1026         0
135         1027         0
136         1028         0
137         1029         0
138         1030         0
139         1031         0
140         1032         0
141         1033         1
142         1034         0
143         1035         0
144         1036         0
145         1037         0
146         1038         0
147         1039         0
148         1040         1
149         1041         0
150         1042         1
151         1043         0
152         1044         0
153         1045         1
154         1046         0
155         1047         0
156         1048         1
157         1049         1
158         1050         1
159         1051         1
160         1052         1
161         1053         1
162         1054         1
163         1055         0
164         1056         0
165         1057         0
166         1058         0
167         1059         0
168         1060         1
169         1061         0
170         1062         0
171         1063         0
172         1064         0
173         1065         0
174         1066         0
175         1067         1
176         1068         1
177         1069         1
178         1070         1
179         1071         1
180         1072         0
181         1073         1
182         1074         1
183         1075         0
184         1076         1
185         1077         0
186         1078         1
187         1079         0
188         1080         0
189         1081         0
190         1082         0
191         1083         1
192         1084         1
193         1085         0
194         1086         1
195         1087         0
196         1088         1
197         1089         1
198         1090         0
199         1091         1
200         1092         1
201         1093         1
202         1094         0
203         1095         1
204         1096         0
205         1097         0
206         1098         1
207         1099         0
208         1100         1
209         1101         0
210         1102         0
211         1103         0
212         1104         0
213         1105         1
214         1106         0
215         1107         0
216         1108         1
217         1109         0
218         1110         1
219         1111         0
220         1112         1
221         1113         0
222         1114         1
223         1115         0
224         1116         1
225         1117         1
226         1118         0
227         1119         1
228         1120         0
229         1121         0
230         1122         0
231         1123         1
232         1124         0
233         1125         0
234         1126         0
235         1127         0
236         1128         1
237         1129         0
238         1130         1
239         1131         1
240         1132         1
241         1133         1
242         1134         0
243         1135         0
244         1136         1
245         1137         1
246         1138         1
247         1139         0
248         1140         1
249         1141         0
250         1142         1
251         1143         0
252         1144         0
253         1145         0
254         1146         0
255         1147         0
256         1148         0
257         1149         0
258         1150         1
259         1151         0
260         1152         0
261         1153         0
262         1154         1
263         1155         1
264         1156         0
265         1157         0
266         1158         0
267         1159         0
268         1160         0
269         1161         0
270         1162         0
271         1163         0
272         1164         1
273         1165         1
274         1166         0
275         1167         1
276         1168         0
277         1169         0
278         1170         0
279         1171         0
280         1172         0
281         1173         1
282         1174         1
283         1175         1
284         1176         1
285         1177         0
286         1178         0
287         1179         0
288         1180         0
289         1181         0
290         1182         0
291         1183         1
292         1184         0
293         1185         1
294         1186         0
295         1187         0
296         1188         1
297         1189         0
298         1190         0
299         1191         0
300         1192         0
301         1193         0
302         1194         0
303         1195         0
304         1196         1
305         1197         1
306         1198         0
307         1199         1
308         1200         0
309         1201         0
310         1202         0
311         1203         0
312         1204         0
313         1205         1
314         1206         1
315         1207         1
316         1208         0
317         1209         0
318         1210         0
319         1211         0
320         1212         0
321         1213         0
322         1214         0
323         1215         1
324         1216         1
325         1217         0
326         1218         1
327         1219         0
328         1220         0
329         1221         0
330         1222         1
331         1223         0
332         1224         0
333         1225         1
334         1226         0
335         1227         0
336         1228         0
337         1229         0
338         1230         0
339         1231         1
340         1232         0
341         1233         0
342         1234         0
343         1235         1
344         1236         1
345         1237         1
346         1238         0
347         1239         1
348         1240         0
349         1241         1
350         1242         1
351         1243         0
352         1244         0
353         1245         0
354         1246         1
355         1247         0
356         1248         1
357         1249         0
358         1250         0
359         1251         1
360         1252         0
361         1253         1
362         1254         1
363         1255         0
364         1256         1
365         1257         0
366         1258         0
367         1259         0
368         1260         1
369         1261         0
370         1262         0
371         1263         1
372         1264         0
373         1265         0
374         1266         1
375         1267         1
376         1268         0
377         1269         0
378         1270         0
379         1271         0
380         1272         0
381         1273         0
382         1274         1
383         1275         1
384         1276         0
385         1277         1
386         1278         0
387         1279         0
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         1
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         1
405         1297         1
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

In [50]:
result.to_csv("submission11.csv", index=False)

In [98]:
result

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         1
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         1
20           912         1
21           913         1
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
30           922         0
31           923         0
32           924         1
33           925         0
34           926         1
35           927         0
36           928         0
37           929         0
38           930         0
39           931         1
40           932         0
41           933         1
42           934         0
43           935         1
44           936         1
45           937         0
46           938         0
47           939         0
48           940         1
49           941         1
50           942         0
51           943         0
52           944         1
53           945         1
54           946         0
55           947         0
56           948         0
57           949         0
58           950         0
59           951         1
60           952         0
61           953         0
62           954         0
63           955         1
64           956         1
65           957         1
66           958         1
67           959         0
68           960         0
69           961         1
70           962         1
71           963         0
72           964         1
73           965         0
74           966         1
75           967         0
76           968         0
77           969         1
78           970         0
79           971         1
80           972         1
81           973         0
82           974         1
83           975         0
84           976         0
85           977         0
86           978         1
87           979         0
88           980         1
89           981         1
90           982         1
91           983         0
92           984         1
93           985         0
94           986         1
95           987         0
96           988         1
97           989         0
98           990         1
99           991         0
100          992         1
101          993         0
102          994         0
103          995         0
104          996         0
105          997         0
106          998         0
107          999         0
108         1000         0
109         1001         0
110         1002         0
111         1003         1
112         1004         1
113         1005         1
114         1006         1
115         1007         0
116         1008         0
117         1009         1
118         1010         0
119         1011         1
120         1012         1
121         1013         0
122         1014         1
123         1015         0
124         1016         0
125         1017         1
126         1018         0
127         1019         1
128         1020         0
129         1021         0
130         1022         0
131         1023         0
132         1024         0
133         1025         0
134         1026         0
135         1027         0
136         1028         0
137         1029         0
138         1030         0
139         1031         0
140         1032         0
141         1033         1
142         1034         0
143         1035         0
144         1036         1
145         1037         0
146         1038         0
147         1039         0
148         1040         1
149         1041         0
150         1042         1
151         1043         0
152         1044         0
153         1045         1
154         1046         0
155         1047         0
156         1048         1
157         1049         1
158         1050         1
159         1051         1
160         1052         1
161         1053         1
162         1054         1
163         1055         0
164         1056         0
165         1057         1
166         1058         0
167         1059         0
168         1060         1
169         1061         0
170         1062         0
171         1063         0
172         1064         0
173         1065         0
174         1066         0
175         1067         1
176         1068         1
177         1069         1
178         1070         1
179         1071         1
180         1072         0
181         1073         0
182         1074         1
183         1075         0
184         1076         1
185         1077         0
186         1078         1
187         1079         0
188         1080         0
189         1081         0
190         1082         0
191         1083         1
192         1084         1
193         1085         0
194         1086         1
195         1087         0
196         1088         1
197         1089         1
198         1090         0
199         1091         1
200         1092         1
201         1093         1
202         1094         1
203         1095         1
204         1096         0
205         1097         0
206         1098         1
207         1099         0
208         1100         1
209         1101         0
210         1102         0
211         1103         0
212         1104         0
213         1105         1
214         1106         0
215         1107         0
216         1108         1
217         1109         0
218         1110         1
219         1111         0
220         1112         1
221         1113         0
222         1114         1
223         1115         0
224         1116         1
225         1117         1
226         1118         0
227         1119         1
228         1120         0
229         1121         0
230         1122         0
231         1123         1
232         1124         0
233         1125         0
234         1126         1
235         1127         0
236         1128         0
237         1129         0
238         1130         1
239         1131         1
240         1132         1
241         1133         1
242         1134         0
243         1135         0
244         1136         1
245         1137         0
246         1138         1
247         1139         0
248         1140         1
249         1141         1
250         1142         1
251         1143         0
252         1144         0
253         1145         0
254         1146         0
255         1147         0
256         1148         0
257         1149         0
258         1150         1
259         1151         0
260         1152         0
261         1153         0
262         1154         1
263         1155         1
264         1156         0
265         1157         0
266         1158         0
267         1159         0
268         1160         0
269         1161         0
270         1162         0
271         1163         0
272         1164         1
273         1165         1
274         1166         0
275         1167         1
276         1168         0
277         1169         0
278         1170         0
279         1171         0
280         1172         0
281         1173         1
282         1174         1
283         1175         1
284         1176         1
285         1177         0
286         1178         0
287         1179         0
288         1180         0
289         1181         0
290         1182         0
291         1183         0
292         1184         0
293         1185         0
294         1186         0
295         1187         0
296         1188         1
297         1189         0
298         1190         0
299         1191         0
300         1192         0
301         1193         0
302         1194         0
303         1195         0
304         1196         1
305         1197         1
306         1198         0
307         1199         1
308         1200         0
309         1201         0
310         1202         0
311         1203         0
312         1204         0
313         1205         1
314         1206         1
315         1207         1
316         1208         0
317         1209         0
318         1210         0
319         1211         0
320         1212         0
321         1213         0
322         1214         0
323         1215         1
324         1216         1
325         1217         0
326         1218         1
327         1219         0
328         1220         0
329         1221         0
330         1222         1
331         1223         0
332         1224         0
333         1225         1
334         1226         0
335         1227         1
336         1228         0
337         1229         0
338         1230         0
339         1231         1
340         1232         0
341         1233         0
342         1234         0
343         1235         1
344         1236         1
345         1237         1
346         1238         0
347         1239         1
348         1240         0
349         1241         1
350         1242         1
351         1243         0
352         1244         0
353         1245         0
354         1246         1
355         1247         1
356         1248         1
357         1249         0
358         1250         0
359         1251         1
360         1252         0
361         1253         1
362         1254         1
363         1255         0
364         1256         1
365         1257         0
366         1258         0
367         1259         1
368         1260         1
369         1261         0
370         1262         0
371         1263         1
372         1264         0
373         1265         0
374         1266         1
375         1267         1
376         1268         0
377         1269         0
378         1270         0
379         1271         0
380         1272         0
381         1273         0
382         1274         1
383         1275         1
384         1276         0
385         1277         1
386         1278         0
387         1279         0
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         1
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1